// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pedal_top_generic_tanh_double_s (
        ap_clk,
        ap_rst,
        t_in,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [63:0] t_in;
output  [63:0] ap_return;
input   ap_ce;

reg[63:0] ap_return;

reg   [63:0] expx_reg_62;
reg   [63:0] expx_reg_62_pp0_iter22_reg;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] expx_reg_62_pp0_iter23_reg;
reg   [63:0] expx_reg_62_pp0_iter24_reg;
reg   [63:0] expx_reg_62_pp0_iter25_reg;
wire   [63:0] grp_fu_136_p2;
reg   [63:0] reg_146;
reg   [0:0] icmp_ln36_reg_434;
reg   [0:0] icmp_ln36_reg_434_pp0_iter45_reg;
reg   [0:0] icmp_ln45_reg_438;
reg   [0:0] icmp_ln45_reg_438_pp0_iter45_reg;
reg   [0:0] and_ln46_reg_442;
reg   [0:0] and_ln46_reg_442_pp0_iter45_reg;
reg   [0:0] tmp_7_reg_451;
reg   [0:0] tmp_7_reg_451_pp0_iter45_reg;
reg   [0:0] icmp_ln54_reg_455;
reg   [0:0] icmp_ln54_reg_455_pp0_iter45_reg;
reg    ap_predicate_pred49_state48;
reg    ap_predicate_pred59_state48;
reg   [0:0] din_sign_reg_409;
reg   [0:0] din_sign_reg_409_pp0_iter1_reg;
reg   [0:0] din_sign_reg_409_pp0_iter2_reg;
reg   [0:0] din_sign_reg_409_pp0_iter3_reg;
reg   [0:0] din_sign_reg_409_pp0_iter4_reg;
reg   [0:0] din_sign_reg_409_pp0_iter5_reg;
reg   [0:0] din_sign_reg_409_pp0_iter6_reg;
reg   [0:0] din_sign_reg_409_pp0_iter7_reg;
reg   [0:0] din_sign_reg_409_pp0_iter8_reg;
reg   [0:0] din_sign_reg_409_pp0_iter9_reg;
reg   [0:0] din_sign_reg_409_pp0_iter10_reg;
reg   [0:0] din_sign_reg_409_pp0_iter11_reg;
reg   [0:0] din_sign_reg_409_pp0_iter12_reg;
reg   [0:0] din_sign_reg_409_pp0_iter13_reg;
reg   [0:0] din_sign_reg_409_pp0_iter14_reg;
reg   [0:0] din_sign_reg_409_pp0_iter15_reg;
reg   [0:0] din_sign_reg_409_pp0_iter16_reg;
reg   [0:0] din_sign_reg_409_pp0_iter17_reg;
reg   [0:0] din_sign_reg_409_pp0_iter18_reg;
reg   [0:0] din_sign_reg_409_pp0_iter19_reg;
reg   [0:0] din_sign_reg_409_pp0_iter20_reg;
reg   [0:0] din_sign_reg_409_pp0_iter21_reg;
reg   [0:0] din_sign_reg_409_pp0_iter22_reg;
reg   [0:0] din_sign_reg_409_pp0_iter23_reg;
reg   [0:0] din_sign_reg_409_pp0_iter24_reg;
reg   [0:0] din_sign_reg_409_pp0_iter25_reg;
reg   [0:0] din_sign_reg_409_pp0_iter26_reg;
reg   [0:0] din_sign_reg_409_pp0_iter27_reg;
reg   [0:0] din_sign_reg_409_pp0_iter28_reg;
reg   [0:0] din_sign_reg_409_pp0_iter29_reg;
reg   [0:0] din_sign_reg_409_pp0_iter30_reg;
reg   [0:0] din_sign_reg_409_pp0_iter31_reg;
reg   [0:0] din_sign_reg_409_pp0_iter32_reg;
reg   [0:0] din_sign_reg_409_pp0_iter33_reg;
reg   [0:0] din_sign_reg_409_pp0_iter34_reg;
reg   [0:0] din_sign_reg_409_pp0_iter35_reg;
reg   [0:0] din_sign_reg_409_pp0_iter36_reg;
reg   [0:0] din_sign_reg_409_pp0_iter37_reg;
reg   [0:0] din_sign_reg_409_pp0_iter38_reg;
reg   [0:0] din_sign_reg_409_pp0_iter39_reg;
reg   [0:0] din_sign_reg_409_pp0_iter40_reg;
reg   [0:0] din_sign_reg_409_pp0_iter41_reg;
reg   [0:0] din_sign_reg_409_pp0_iter42_reg;
reg   [0:0] din_sign_reg_409_pp0_iter43_reg;
reg   [0:0] din_sign_reg_409_pp0_iter44_reg;
reg   [0:0] din_sign_reg_409_pp0_iter45_reg;
reg   [0:0] din_sign_reg_409_pp0_iter46_reg;
reg   [0:0] din_sign_reg_409_pp0_iter47_reg;
reg   [0:0] din_sign_reg_409_pp0_iter48_reg;
reg   [0:0] din_sign_reg_409_pp0_iter49_reg;
reg   [0:0] din_sign_reg_409_pp0_iter50_reg;
reg   [0:0] din_sign_reg_409_pp0_iter51_reg;
wire   [10:0] din_exp_fu_164_p4;
reg   [10:0] din_exp_reg_414;
wire   [62:0] trunc_ln479_fu_178_p1;
reg   [62:0] trunc_ln479_reg_419;
wire   [63:0] abst_in_fu_190_p1;
reg   [63:0] abst_in_reg_424;
reg   [63:0] abst_in_reg_424_pp0_iter1_reg;
reg   [63:0] abst_in_reg_424_pp0_iter2_reg;
reg   [63:0] abst_in_reg_424_pp0_iter3_reg;
reg   [63:0] abst_in_reg_424_pp0_iter4_reg;
wire   [0:0] icmp_ln36_fu_196_p2;
reg   [0:0] icmp_ln36_reg_434_pp0_iter1_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter2_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter3_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter4_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter5_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter6_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter7_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter8_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter9_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter10_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter11_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter12_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter13_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter14_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter15_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter16_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter17_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter18_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter19_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter20_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter21_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter22_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter23_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter24_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter25_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter26_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter27_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter28_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter29_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter30_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter31_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter32_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter33_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter34_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter35_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter36_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter37_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter38_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter39_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter40_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter41_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter42_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter43_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter44_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter46_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter47_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter48_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter49_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter50_reg;
reg   [0:0] icmp_ln36_reg_434_pp0_iter51_reg;
wire   [0:0] icmp_ln45_fu_202_p2;
reg   [0:0] icmp_ln45_reg_438_pp0_iter1_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter2_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter3_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter4_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter5_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter6_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter7_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter8_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter9_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter10_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter11_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter12_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter13_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter14_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter15_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter16_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter17_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter18_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter19_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter20_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter21_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter22_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter23_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter24_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter25_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter26_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter27_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter28_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter29_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter30_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter31_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter32_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter33_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter34_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter35_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter36_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter37_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter38_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter39_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter40_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter41_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter42_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter43_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter44_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter46_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter47_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter48_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter49_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter50_reg;
reg   [0:0] icmp_ln45_reg_438_pp0_iter51_reg;
wire   [0:0] and_ln46_fu_220_p2;
reg   [0:0] and_ln46_reg_442_pp0_iter1_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter2_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter3_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter4_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter5_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter6_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter7_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter8_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter9_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter10_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter11_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter12_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter13_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter14_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter15_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter16_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter17_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter18_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter19_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter20_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter21_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter22_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter23_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter24_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter25_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter26_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter27_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter28_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter29_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter30_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter31_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter32_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter33_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter34_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter35_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter36_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter37_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter38_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter39_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter40_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter41_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter42_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter43_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter44_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter46_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter47_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter48_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter49_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter50_reg;
reg   [0:0] and_ln46_reg_442_pp0_iter51_reg;
wire   [0:0] icmp_ln38_fu_226_p2;
reg   [0:0] icmp_ln38_reg_446;
reg   [0:0] icmp_ln38_reg_446_pp0_iter1_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter2_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter3_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter4_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter5_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter6_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter7_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter8_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter9_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter10_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter11_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter12_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter13_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter14_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter15_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter16_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter17_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter18_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter19_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter20_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter21_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter22_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter23_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter24_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter25_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter26_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter27_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter28_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter29_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter30_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter31_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter32_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter33_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter34_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter35_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter36_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter37_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter38_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter39_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter40_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter41_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter42_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter43_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter44_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter45_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter46_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter47_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter48_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter49_reg;
reg   [0:0] icmp_ln38_reg_446_pp0_iter50_reg;
wire   [0:0] grp_fu_141_p2;
reg   [0:0] tmp_7_reg_451_pp0_iter2_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter3_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter4_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter5_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter6_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter7_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter8_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter9_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter10_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter11_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter12_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter13_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter14_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter15_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter16_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter17_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter18_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter19_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter20_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter21_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter22_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter23_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter24_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter25_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter26_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter27_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter28_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter29_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter30_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter31_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter32_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter33_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter34_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter35_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter36_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter37_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter38_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter39_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter40_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter41_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter42_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter43_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter44_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter46_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter47_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter48_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter49_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter50_reg;
reg   [0:0] tmp_7_reg_451_pp0_iter51_reg;
wire   [0:0] icmp_ln54_fu_232_p2;
reg   [0:0] icmp_ln54_reg_455_pp0_iter2_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter3_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter4_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter5_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter6_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter7_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter8_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter9_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter10_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter11_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter12_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter13_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter14_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter15_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter16_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter17_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter18_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter19_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter20_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter21_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter22_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter23_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter24_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter25_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter26_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter27_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter28_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter29_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter30_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter31_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter32_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter33_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter34_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter35_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter36_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter37_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter38_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter39_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter40_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter41_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter42_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter43_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter44_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter46_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter47_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter48_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter49_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter50_reg;
reg   [0:0] icmp_ln54_reg_455_pp0_iter51_reg;
wire   [63:0] grp_fu_102_p2;
reg   [63:0] add_reg_465;
wire   [63:0] x_3_fu_249_p3;
reg   [63:0] x_3_reg_470;
wire   [0:0] and_ln9_1_fu_296_p2;
reg   [0:0] and_ln9_1_reg_477;
reg   [0:0] and_ln9_1_reg_477_pp0_iter6_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter7_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter8_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter9_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter10_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter11_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter12_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter13_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter14_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter15_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter16_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter17_reg;
reg   [0:0] and_ln9_1_reg_477_pp0_iter18_reg;
wire   [0:0] and_ln10_1_fu_320_p2;
reg   [0:0] and_ln10_1_reg_481;
reg   [0:0] and_ln10_1_reg_481_pp0_iter6_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter7_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter8_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter9_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter10_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter11_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter12_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter13_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter14_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter15_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter16_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter17_reg;
reg   [0:0] and_ln10_1_reg_481_pp0_iter18_reg;
wire   [63:0] grp_fu_132_p2;
reg   [63:0] resultf_reg_485;
wire   [63:0] grp_exp_generic_double_s_fu_91_ap_return;
reg   [63:0] tmp_2_reg_490;
wire   [63:0] grp_fu_115_p2;
wire   [63:0] grp_fu_120_p2;
reg   [63:0] add2_reg_500;
wire   [63:0] bitcast_ln66_1_fu_356_p1;
wire   [63:0] select_ln38_fu_361_p3;
reg    grp_exp_generic_double_s_fu_91_ap_ce;
reg    ap_predicate_op108_call_state7;
wire    ap_block_pp0_stage0_11001_ignoreCallOp108;
wire   [63:0] ap_phi_reg_pp0_iter0_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter1_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter2_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter3_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter4_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter5_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter6_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter7_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter8_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter9_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter10_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter11_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter12_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter13_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter14_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter15_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter16_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter17_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter18_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter19_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter20_expx_reg_62;
reg   [63:0] ap_phi_reg_pp0_iter21_expx_reg_62;
reg    ap_predicate_pred743_state21;
reg   [63:0] ap_phi_mux_resultf_3_phi_fu_78_p10;
wire   [63:0] ap_phi_reg_pp0_iter0_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter1_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter2_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter3_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter4_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter5_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter6_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter7_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter8_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter9_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter10_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter11_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter12_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter13_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter14_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter15_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter16_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter17_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter18_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter19_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter20_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter21_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter22_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter23_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter24_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter25_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter26_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter27_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter28_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter29_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter30_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter31_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter32_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter33_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter34_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter35_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter36_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter37_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter38_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter39_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter40_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter41_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter42_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter43_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter44_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter45_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter46_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter47_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter48_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter49_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter50_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter51_resultf_3_reg_74;
reg   [63:0] ap_phi_reg_pp0_iter52_resultf_3_reg_74;
wire   [63:0] grp_fu_126_p2;
wire    ap_block_pp0_stage0_ignoreCallOp108;
wire    ap_block_pp0_stage0;
wire   [63:0] grp_fu_107_p0;
reg   [63:0] grp_fu_136_p0;
reg    ap_predicate_pred897_state27;
reg    ap_predicate_pred902_state27;
wire   [63:0] data_fu_152_p1;
wire   [63:0] t_fu_182_p3;
wire   [51:0] din_sig_fu_174_p1;
wire   [0:0] icmp_ln46_fu_208_p2;
wire   [0:0] icmp_ln46_1_fu_214_p2;
wire   [63:0] or_ln_fu_237_p3;
wire   [63:0] grp_fu_107_p2;
wire   [63:0] grp_fu_111_p2;
wire   [63:0] data_2_fu_256_p1;
wire   [10:0] xs_exp_2_fu_260_p4;
wire   [0:0] icmp_ln9_fu_278_p2;
wire   [0:0] icmp_ln9_1_fu_284_p2;
wire   [0:0] and_ln9_fu_290_p2;
wire   [0:0] tmp_fu_270_p3;
wire   [0:0] xor_ln10_fu_302_p2;
wire   [0:0] and_ln10_fu_314_p2;
wire   [0:0] icmp_ln10_fu_308_p2;
wire   [63:0] bitcast_ln66_fu_326_p1;
wire   [0:0] bit_sel_fu_330_p3;
wire   [0:0] xor_ln66_fu_338_p2;
wire   [62:0] trunc_ln66_fu_344_p1;
wire   [63:0] xor_ln_fu_348_p3;
wire   [63:0] bitcast_ln83_fu_368_p1;
wire   [0:0] bit_sel1_fu_372_p3;
wire   [0:0] xor_ln83_fu_380_p2;
wire   [62:0] trunc_ln83_fu_386_p1;
wire   [63:0] xor_ln1_fu_390_p3;
wire   [63:0] bitcast_ln83_1_fu_398_p1;
reg    grp_fu_102_ce;
reg    grp_fu_107_ce;
reg    grp_fu_111_ce;
reg    grp_fu_115_ce;
reg    grp_fu_120_ce;
reg    grp_fu_126_ce;
reg    grp_fu_132_ce;
reg    grp_fu_136_ce;
reg    grp_fu_141_ce;
reg    ap_predicate_op70_dcmp_state1;
wire    ap_block_pp0_stage0_00001;
wire   [63:0] select_ln79_fu_402_p3;
reg    ap_ce_reg;
reg   [63:0] t_in_int_reg;
reg   [63:0] ap_return_int_reg;
reg    ap_condition_828;
reg    ap_condition_861;

pedal_top_exp_generic_double_s grp_exp_generic_double_s_fu_91(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(x_3_reg_470),
    .ap_return(grp_exp_generic_double_s_fu_91_ap_return),
    .ap_ce(grp_exp_generic_double_s_fu_91_ap_ce)
);

pedal_top_dadd_64ns_64ns_64_5_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_0_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_fu_190_p1),
    .din1(64'd4607182418800017408),
    .ce(grp_fu_102_ce),
    .dout(grp_fu_102_p2)
);

pedal_top_dsub_64ns_64ns_64_5_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsub_64ns_64ns_64_5_full_dsp_0_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_107_p0),
    .din1(abst_in_reg_424),
    .ce(grp_fu_107_ce),
    .dout(grp_fu_107_p2)
);

pedal_top_dadd_64ns_64ns_64_5_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_0_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_reg_424),
    .din1(abst_in_reg_424),
    .ce(grp_fu_111_ce),
    .dout(grp_fu_111_p2)
);

pedal_top_dadd_64ns_64ns_64_5_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_0_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_reg_490),
    .din1(64'd13830554455654793216),
    .ce(grp_fu_115_ce),
    .dout(grp_fu_115_p2)
);

pedal_top_dadd_64ns_64ns_64_5_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_0_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_reg_pp0_iter21_expx_reg_62),
    .din1(64'd4611686018427387904),
    .ce(grp_fu_120_ce),
    .dout(grp_fu_120_p2)
);

pedal_top_dsub_64ns_64ns_64_5_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsub_64ns_64ns_64_5_full_dsp_0_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(64'd4607182418800017408),
    .din1(reg_146),
    .ce(grp_fu_126_ce),
    .dout(grp_fu_126_p2)
);

pedal_top_dmul_64ns_64ns_64_5_max_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_5_max_dsp_0_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_reg_424_pp0_iter4_reg),
    .din1(add_reg_465),
    .ce(grp_fu_132_ce),
    .dout(grp_fu_132_p2)
);

pedal_top_ddiv_64ns_64ns_64_22_no_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 22 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_22_no_dsp_0_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_136_p0),
    .din1(add2_reg_500),
    .ce(grp_fu_136_ce),
    .dout(grp_fu_136_p2)
);

pedal_top_dcmp_64ns_64ns_1_2_no_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_0_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_fu_190_p1),
    .din1(64'd4626885667169763328),
    .ce(grp_fu_141_ce),
    .opcode(5'd4),
    .dout(grp_fu_141_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_828)) begin
            ap_phi_reg_pp0_iter11_resultf_3_reg_74 <= resultf_reg_485;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter11_resultf_3_reg_74 <= ap_phi_reg_pp0_iter10_resultf_3_reg_74;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_predicate_pred743_state21 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_expx_reg_62 <= grp_fu_115_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_expx_reg_62 <= ap_phi_reg_pp0_iter20_expx_reg_62;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_861)) begin
            ap_phi_reg_pp0_iter2_resultf_3_reg_74 <= 64'd4607182418800017408;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_resultf_3_reg_74 <= ap_phi_reg_pp0_iter1_resultf_3_reg_74;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_predicate_pred59_state48 == 1'b1)) begin
            ap_phi_reg_pp0_iter48_resultf_3_reg_74 <= grp_fu_136_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter48_resultf_3_reg_74 <= ap_phi_reg_pp0_iter47_resultf_3_reg_74;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((icmp_ln36_reg_434_pp0_iter50_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter52_resultf_3_reg_74 <= select_ln38_fu_361_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter52_resultf_3_reg_74 <= ap_phi_reg_pp0_iter51_resultf_3_reg_74;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd1 == and_ln10_1_fu_320_p2) & (tmp_7_reg_451_pp0_iter4_reg == 1'd1) & (1'd0 == and_ln9_1_fu_296_p2) & (1'd0 == and_ln46_reg_442_pp0_iter4_reg) & (1'b1 == ap_ce_reg) & (icmp_ln45_reg_438_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln36_reg_434_pp0_iter4_reg == 1'd0)) | ((1'd1 == and_ln9_1_fu_296_p2) & (tmp_7_reg_451_pp0_iter4_reg == 1'd1) & (1'd0 == and_ln46_reg_442_pp0_iter4_reg) & (1'b1 == ap_ce_reg) & (icmp_ln45_reg_438_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln36_reg_434_pp0_iter4_reg == 1'd0)))) begin
        ap_phi_reg_pp0_iter6_expx_reg_62 <= x_3_fu_249_p3;
    end else if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_expx_reg_62 <= ap_phi_reg_pp0_iter5_expx_reg_62;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        abst_in_reg_424[62 : 0] <= abst_in_fu_190_p1[62 : 0];
        abst_in_reg_424_pp0_iter1_reg[62 : 0] <= abst_in_reg_424[62 : 0];
        abst_in_reg_424_pp0_iter2_reg[62 : 0] <= abst_in_reg_424_pp0_iter1_reg[62 : 0];
        abst_in_reg_424_pp0_iter3_reg[62 : 0] <= abst_in_reg_424_pp0_iter2_reg[62 : 0];
        abst_in_reg_424_pp0_iter4_reg[62 : 0] <= abst_in_reg_424_pp0_iter3_reg[62 : 0];
        add2_reg_500 <= grp_fu_120_p2;
        add_reg_465 <= grp_fu_102_p2;
        and_ln10_1_reg_481 <= and_ln10_1_fu_320_p2;
        and_ln10_1_reg_481_pp0_iter10_reg <= and_ln10_1_reg_481_pp0_iter9_reg;
        and_ln10_1_reg_481_pp0_iter11_reg <= and_ln10_1_reg_481_pp0_iter10_reg;
        and_ln10_1_reg_481_pp0_iter12_reg <= and_ln10_1_reg_481_pp0_iter11_reg;
        and_ln10_1_reg_481_pp0_iter13_reg <= and_ln10_1_reg_481_pp0_iter12_reg;
        and_ln10_1_reg_481_pp0_iter14_reg <= and_ln10_1_reg_481_pp0_iter13_reg;
        and_ln10_1_reg_481_pp0_iter15_reg <= and_ln10_1_reg_481_pp0_iter14_reg;
        and_ln10_1_reg_481_pp0_iter16_reg <= and_ln10_1_reg_481_pp0_iter15_reg;
        and_ln10_1_reg_481_pp0_iter17_reg <= and_ln10_1_reg_481_pp0_iter16_reg;
        and_ln10_1_reg_481_pp0_iter18_reg <= and_ln10_1_reg_481_pp0_iter17_reg;
        and_ln10_1_reg_481_pp0_iter6_reg <= and_ln10_1_reg_481;
        and_ln10_1_reg_481_pp0_iter7_reg <= and_ln10_1_reg_481_pp0_iter6_reg;
        and_ln10_1_reg_481_pp0_iter8_reg <= and_ln10_1_reg_481_pp0_iter7_reg;
        and_ln10_1_reg_481_pp0_iter9_reg <= and_ln10_1_reg_481_pp0_iter8_reg;
        and_ln46_reg_442 <= and_ln46_fu_220_p2;
        and_ln46_reg_442_pp0_iter10_reg <= and_ln46_reg_442_pp0_iter9_reg;
        and_ln46_reg_442_pp0_iter11_reg <= and_ln46_reg_442_pp0_iter10_reg;
        and_ln46_reg_442_pp0_iter12_reg <= and_ln46_reg_442_pp0_iter11_reg;
        and_ln46_reg_442_pp0_iter13_reg <= and_ln46_reg_442_pp0_iter12_reg;
        and_ln46_reg_442_pp0_iter14_reg <= and_ln46_reg_442_pp0_iter13_reg;
        and_ln46_reg_442_pp0_iter15_reg <= and_ln46_reg_442_pp0_iter14_reg;
        and_ln46_reg_442_pp0_iter16_reg <= and_ln46_reg_442_pp0_iter15_reg;
        and_ln46_reg_442_pp0_iter17_reg <= and_ln46_reg_442_pp0_iter16_reg;
        and_ln46_reg_442_pp0_iter18_reg <= and_ln46_reg_442_pp0_iter17_reg;
        and_ln46_reg_442_pp0_iter19_reg <= and_ln46_reg_442_pp0_iter18_reg;
        and_ln46_reg_442_pp0_iter1_reg <= and_ln46_reg_442;
        and_ln46_reg_442_pp0_iter20_reg <= and_ln46_reg_442_pp0_iter19_reg;
        and_ln46_reg_442_pp0_iter21_reg <= and_ln46_reg_442_pp0_iter20_reg;
        and_ln46_reg_442_pp0_iter22_reg <= and_ln46_reg_442_pp0_iter21_reg;
        and_ln46_reg_442_pp0_iter23_reg <= and_ln46_reg_442_pp0_iter22_reg;
        and_ln46_reg_442_pp0_iter24_reg <= and_ln46_reg_442_pp0_iter23_reg;
        and_ln46_reg_442_pp0_iter25_reg <= and_ln46_reg_442_pp0_iter24_reg;
        and_ln46_reg_442_pp0_iter26_reg <= and_ln46_reg_442_pp0_iter25_reg;
        and_ln46_reg_442_pp0_iter27_reg <= and_ln46_reg_442_pp0_iter26_reg;
        and_ln46_reg_442_pp0_iter28_reg <= and_ln46_reg_442_pp0_iter27_reg;
        and_ln46_reg_442_pp0_iter29_reg <= and_ln46_reg_442_pp0_iter28_reg;
        and_ln46_reg_442_pp0_iter2_reg <= and_ln46_reg_442_pp0_iter1_reg;
        and_ln46_reg_442_pp0_iter30_reg <= and_ln46_reg_442_pp0_iter29_reg;
        and_ln46_reg_442_pp0_iter31_reg <= and_ln46_reg_442_pp0_iter30_reg;
        and_ln46_reg_442_pp0_iter32_reg <= and_ln46_reg_442_pp0_iter31_reg;
        and_ln46_reg_442_pp0_iter33_reg <= and_ln46_reg_442_pp0_iter32_reg;
        and_ln46_reg_442_pp0_iter34_reg <= and_ln46_reg_442_pp0_iter33_reg;
        and_ln46_reg_442_pp0_iter35_reg <= and_ln46_reg_442_pp0_iter34_reg;
        and_ln46_reg_442_pp0_iter36_reg <= and_ln46_reg_442_pp0_iter35_reg;
        and_ln46_reg_442_pp0_iter37_reg <= and_ln46_reg_442_pp0_iter36_reg;
        and_ln46_reg_442_pp0_iter38_reg <= and_ln46_reg_442_pp0_iter37_reg;
        and_ln46_reg_442_pp0_iter39_reg <= and_ln46_reg_442_pp0_iter38_reg;
        and_ln46_reg_442_pp0_iter3_reg <= and_ln46_reg_442_pp0_iter2_reg;
        and_ln46_reg_442_pp0_iter40_reg <= and_ln46_reg_442_pp0_iter39_reg;
        and_ln46_reg_442_pp0_iter41_reg <= and_ln46_reg_442_pp0_iter40_reg;
        and_ln46_reg_442_pp0_iter42_reg <= and_ln46_reg_442_pp0_iter41_reg;
        and_ln46_reg_442_pp0_iter43_reg <= and_ln46_reg_442_pp0_iter42_reg;
        and_ln46_reg_442_pp0_iter44_reg <= and_ln46_reg_442_pp0_iter43_reg;
        and_ln46_reg_442_pp0_iter45_reg <= and_ln46_reg_442_pp0_iter44_reg;
        and_ln46_reg_442_pp0_iter46_reg <= and_ln46_reg_442_pp0_iter45_reg;
        and_ln46_reg_442_pp0_iter47_reg <= and_ln46_reg_442_pp0_iter46_reg;
        and_ln46_reg_442_pp0_iter48_reg <= and_ln46_reg_442_pp0_iter47_reg;
        and_ln46_reg_442_pp0_iter49_reg <= and_ln46_reg_442_pp0_iter48_reg;
        and_ln46_reg_442_pp0_iter4_reg <= and_ln46_reg_442_pp0_iter3_reg;
        and_ln46_reg_442_pp0_iter50_reg <= and_ln46_reg_442_pp0_iter49_reg;
        and_ln46_reg_442_pp0_iter51_reg <= and_ln46_reg_442_pp0_iter50_reg;
        and_ln46_reg_442_pp0_iter5_reg <= and_ln46_reg_442_pp0_iter4_reg;
        and_ln46_reg_442_pp0_iter6_reg <= and_ln46_reg_442_pp0_iter5_reg;
        and_ln46_reg_442_pp0_iter7_reg <= and_ln46_reg_442_pp0_iter6_reg;
        and_ln46_reg_442_pp0_iter8_reg <= and_ln46_reg_442_pp0_iter7_reg;
        and_ln46_reg_442_pp0_iter9_reg <= and_ln46_reg_442_pp0_iter8_reg;
        and_ln9_1_reg_477 <= and_ln9_1_fu_296_p2;
        and_ln9_1_reg_477_pp0_iter10_reg <= and_ln9_1_reg_477_pp0_iter9_reg;
        and_ln9_1_reg_477_pp0_iter11_reg <= and_ln9_1_reg_477_pp0_iter10_reg;
        and_ln9_1_reg_477_pp0_iter12_reg <= and_ln9_1_reg_477_pp0_iter11_reg;
        and_ln9_1_reg_477_pp0_iter13_reg <= and_ln9_1_reg_477_pp0_iter12_reg;
        and_ln9_1_reg_477_pp0_iter14_reg <= and_ln9_1_reg_477_pp0_iter13_reg;
        and_ln9_1_reg_477_pp0_iter15_reg <= and_ln9_1_reg_477_pp0_iter14_reg;
        and_ln9_1_reg_477_pp0_iter16_reg <= and_ln9_1_reg_477_pp0_iter15_reg;
        and_ln9_1_reg_477_pp0_iter17_reg <= and_ln9_1_reg_477_pp0_iter16_reg;
        and_ln9_1_reg_477_pp0_iter18_reg <= and_ln9_1_reg_477_pp0_iter17_reg;
        and_ln9_1_reg_477_pp0_iter6_reg <= and_ln9_1_reg_477;
        and_ln9_1_reg_477_pp0_iter7_reg <= and_ln9_1_reg_477_pp0_iter6_reg;
        and_ln9_1_reg_477_pp0_iter8_reg <= and_ln9_1_reg_477_pp0_iter7_reg;
        and_ln9_1_reg_477_pp0_iter9_reg <= and_ln9_1_reg_477_pp0_iter8_reg;
        ap_phi_reg_pp0_iter10_expx_reg_62 <= ap_phi_reg_pp0_iter9_expx_reg_62;
        ap_phi_reg_pp0_iter10_resultf_3_reg_74 <= ap_phi_reg_pp0_iter9_resultf_3_reg_74;
        ap_phi_reg_pp0_iter11_expx_reg_62 <= ap_phi_reg_pp0_iter10_expx_reg_62;
        ap_phi_reg_pp0_iter12_expx_reg_62 <= ap_phi_reg_pp0_iter11_expx_reg_62;
        ap_phi_reg_pp0_iter12_resultf_3_reg_74 <= ap_phi_reg_pp0_iter11_resultf_3_reg_74;
        ap_phi_reg_pp0_iter13_expx_reg_62 <= ap_phi_reg_pp0_iter12_expx_reg_62;
        ap_phi_reg_pp0_iter13_resultf_3_reg_74 <= ap_phi_reg_pp0_iter12_resultf_3_reg_74;
        ap_phi_reg_pp0_iter14_expx_reg_62 <= ap_phi_reg_pp0_iter13_expx_reg_62;
        ap_phi_reg_pp0_iter14_resultf_3_reg_74 <= ap_phi_reg_pp0_iter13_resultf_3_reg_74;
        ap_phi_reg_pp0_iter15_expx_reg_62 <= ap_phi_reg_pp0_iter14_expx_reg_62;
        ap_phi_reg_pp0_iter15_resultf_3_reg_74 <= ap_phi_reg_pp0_iter14_resultf_3_reg_74;
        ap_phi_reg_pp0_iter16_expx_reg_62 <= ap_phi_reg_pp0_iter15_expx_reg_62;
        ap_phi_reg_pp0_iter16_resultf_3_reg_74 <= ap_phi_reg_pp0_iter15_resultf_3_reg_74;
        ap_phi_reg_pp0_iter17_expx_reg_62 <= ap_phi_reg_pp0_iter16_expx_reg_62;
        ap_phi_reg_pp0_iter17_resultf_3_reg_74 <= ap_phi_reg_pp0_iter16_resultf_3_reg_74;
        ap_phi_reg_pp0_iter18_expx_reg_62 <= ap_phi_reg_pp0_iter17_expx_reg_62;
        ap_phi_reg_pp0_iter18_resultf_3_reg_74 <= ap_phi_reg_pp0_iter17_resultf_3_reg_74;
        ap_phi_reg_pp0_iter19_expx_reg_62 <= ap_phi_reg_pp0_iter18_expx_reg_62;
        ap_phi_reg_pp0_iter19_resultf_3_reg_74 <= ap_phi_reg_pp0_iter18_resultf_3_reg_74;
        ap_phi_reg_pp0_iter1_expx_reg_62 <= ap_phi_reg_pp0_iter0_expx_reg_62;
        ap_phi_reg_pp0_iter1_resultf_3_reg_74 <= ap_phi_reg_pp0_iter0_resultf_3_reg_74;
        ap_phi_reg_pp0_iter20_expx_reg_62 <= ap_phi_reg_pp0_iter19_expx_reg_62;
        ap_phi_reg_pp0_iter20_resultf_3_reg_74 <= ap_phi_reg_pp0_iter19_resultf_3_reg_74;
        ap_phi_reg_pp0_iter21_resultf_3_reg_74 <= ap_phi_reg_pp0_iter20_resultf_3_reg_74;
        ap_phi_reg_pp0_iter22_resultf_3_reg_74 <= ap_phi_reg_pp0_iter21_resultf_3_reg_74;
        ap_phi_reg_pp0_iter23_resultf_3_reg_74 <= ap_phi_reg_pp0_iter22_resultf_3_reg_74;
        ap_phi_reg_pp0_iter24_resultf_3_reg_74 <= ap_phi_reg_pp0_iter23_resultf_3_reg_74;
        ap_phi_reg_pp0_iter25_resultf_3_reg_74 <= ap_phi_reg_pp0_iter24_resultf_3_reg_74;
        ap_phi_reg_pp0_iter26_resultf_3_reg_74 <= ap_phi_reg_pp0_iter25_resultf_3_reg_74;
        ap_phi_reg_pp0_iter27_resultf_3_reg_74 <= ap_phi_reg_pp0_iter26_resultf_3_reg_74;
        ap_phi_reg_pp0_iter28_resultf_3_reg_74 <= ap_phi_reg_pp0_iter27_resultf_3_reg_74;
        ap_phi_reg_pp0_iter29_resultf_3_reg_74 <= ap_phi_reg_pp0_iter28_resultf_3_reg_74;
        ap_phi_reg_pp0_iter2_expx_reg_62 <= ap_phi_reg_pp0_iter1_expx_reg_62;
        ap_phi_reg_pp0_iter30_resultf_3_reg_74 <= ap_phi_reg_pp0_iter29_resultf_3_reg_74;
        ap_phi_reg_pp0_iter31_resultf_3_reg_74 <= ap_phi_reg_pp0_iter30_resultf_3_reg_74;
        ap_phi_reg_pp0_iter32_resultf_3_reg_74 <= ap_phi_reg_pp0_iter31_resultf_3_reg_74;
        ap_phi_reg_pp0_iter33_resultf_3_reg_74 <= ap_phi_reg_pp0_iter32_resultf_3_reg_74;
        ap_phi_reg_pp0_iter34_resultf_3_reg_74 <= ap_phi_reg_pp0_iter33_resultf_3_reg_74;
        ap_phi_reg_pp0_iter35_resultf_3_reg_74 <= ap_phi_reg_pp0_iter34_resultf_3_reg_74;
        ap_phi_reg_pp0_iter36_resultf_3_reg_74 <= ap_phi_reg_pp0_iter35_resultf_3_reg_74;
        ap_phi_reg_pp0_iter37_resultf_3_reg_74 <= ap_phi_reg_pp0_iter36_resultf_3_reg_74;
        ap_phi_reg_pp0_iter38_resultf_3_reg_74 <= ap_phi_reg_pp0_iter37_resultf_3_reg_74;
        ap_phi_reg_pp0_iter39_resultf_3_reg_74 <= ap_phi_reg_pp0_iter38_resultf_3_reg_74;
        ap_phi_reg_pp0_iter3_expx_reg_62 <= ap_phi_reg_pp0_iter2_expx_reg_62;
        ap_phi_reg_pp0_iter3_resultf_3_reg_74 <= ap_phi_reg_pp0_iter2_resultf_3_reg_74;
        ap_phi_reg_pp0_iter40_resultf_3_reg_74 <= ap_phi_reg_pp0_iter39_resultf_3_reg_74;
        ap_phi_reg_pp0_iter41_resultf_3_reg_74 <= ap_phi_reg_pp0_iter40_resultf_3_reg_74;
        ap_phi_reg_pp0_iter42_resultf_3_reg_74 <= ap_phi_reg_pp0_iter41_resultf_3_reg_74;
        ap_phi_reg_pp0_iter43_resultf_3_reg_74 <= ap_phi_reg_pp0_iter42_resultf_3_reg_74;
        ap_phi_reg_pp0_iter44_resultf_3_reg_74 <= ap_phi_reg_pp0_iter43_resultf_3_reg_74;
        ap_phi_reg_pp0_iter45_resultf_3_reg_74 <= ap_phi_reg_pp0_iter44_resultf_3_reg_74;
        ap_phi_reg_pp0_iter46_resultf_3_reg_74 <= ap_phi_reg_pp0_iter45_resultf_3_reg_74;
        ap_phi_reg_pp0_iter47_resultf_3_reg_74 <= ap_phi_reg_pp0_iter46_resultf_3_reg_74;
        ap_phi_reg_pp0_iter49_resultf_3_reg_74 <= ap_phi_reg_pp0_iter48_resultf_3_reg_74;
        ap_phi_reg_pp0_iter4_expx_reg_62 <= ap_phi_reg_pp0_iter3_expx_reg_62;
        ap_phi_reg_pp0_iter4_resultf_3_reg_74 <= ap_phi_reg_pp0_iter3_resultf_3_reg_74;
        ap_phi_reg_pp0_iter50_resultf_3_reg_74 <= ap_phi_reg_pp0_iter49_resultf_3_reg_74;
        ap_phi_reg_pp0_iter51_resultf_3_reg_74 <= ap_phi_reg_pp0_iter50_resultf_3_reg_74;
        ap_phi_reg_pp0_iter5_expx_reg_62 <= ap_phi_reg_pp0_iter4_expx_reg_62;
        ap_phi_reg_pp0_iter5_resultf_3_reg_74 <= ap_phi_reg_pp0_iter4_resultf_3_reg_74;
        ap_phi_reg_pp0_iter6_resultf_3_reg_74 <= ap_phi_reg_pp0_iter5_resultf_3_reg_74;
        ap_phi_reg_pp0_iter7_expx_reg_62 <= ap_phi_reg_pp0_iter6_expx_reg_62;
        ap_phi_reg_pp0_iter7_resultf_3_reg_74 <= ap_phi_reg_pp0_iter6_resultf_3_reg_74;
        ap_phi_reg_pp0_iter8_expx_reg_62 <= ap_phi_reg_pp0_iter7_expx_reg_62;
        ap_phi_reg_pp0_iter8_resultf_3_reg_74 <= ap_phi_reg_pp0_iter7_resultf_3_reg_74;
        ap_phi_reg_pp0_iter9_expx_reg_62 <= ap_phi_reg_pp0_iter8_expx_reg_62;
        ap_phi_reg_pp0_iter9_resultf_3_reg_74 <= ap_phi_reg_pp0_iter8_resultf_3_reg_74;
        ap_predicate_pred49_state48 <= ((icmp_ln54_reg_455_pp0_iter45_reg == 1'd0) & (tmp_7_reg_451_pp0_iter45_reg == 1'd1) & (icmp_ln45_reg_438_pp0_iter45_reg == 1'd0) & (1'd0 == and_ln46_reg_442_pp0_iter45_reg) & (icmp_ln36_reg_434_pp0_iter45_reg == 1'd0));
        ap_predicate_pred59_state48 <= ((icmp_ln54_reg_455_pp0_iter45_reg == 1'd1) & (tmp_7_reg_451_pp0_iter45_reg == 1'd1) & (icmp_ln45_reg_438_pp0_iter45_reg == 1'd0) & (1'd0 == and_ln46_reg_442_pp0_iter45_reg) & (icmp_ln36_reg_434_pp0_iter45_reg == 1'd0));
        ap_predicate_pred743_state21 <= ((tmp_7_reg_451_pp0_iter18_reg == 1'd1) & (1'd0 == and_ln10_1_reg_481_pp0_iter18_reg) & (1'd0 == and_ln9_1_reg_477_pp0_iter18_reg) & (1'd0 == and_ln46_reg_442_pp0_iter18_reg) & (icmp_ln45_reg_438_pp0_iter18_reg == 1'd0) & (icmp_ln36_reg_434_pp0_iter18_reg == 1'd0));
        ap_predicate_pred897_state27 <= ((icmp_ln54_reg_455_pp0_iter24_reg == 1'd0) & (tmp_7_reg_451_pp0_iter24_reg == 1'd1) & (1'd0 == and_ln46_reg_442_pp0_iter24_reg) & (icmp_ln45_reg_438_pp0_iter24_reg == 1'd0) & (icmp_ln36_reg_434_pp0_iter24_reg == 1'd0));
        ap_predicate_pred902_state27 <= ((icmp_ln54_reg_455_pp0_iter24_reg == 1'd1) & (tmp_7_reg_451_pp0_iter24_reg == 1'd1) & (1'd0 == and_ln46_reg_442_pp0_iter24_reg) & (icmp_ln45_reg_438_pp0_iter24_reg == 1'd0) & (icmp_ln36_reg_434_pp0_iter24_reg == 1'd0));
        din_exp_reg_414 <= {{data_fu_152_p1[62:52]}};
        din_sign_reg_409 <= data_fu_152_p1[32'd63];
        din_sign_reg_409_pp0_iter10_reg <= din_sign_reg_409_pp0_iter9_reg;
        din_sign_reg_409_pp0_iter11_reg <= din_sign_reg_409_pp0_iter10_reg;
        din_sign_reg_409_pp0_iter12_reg <= din_sign_reg_409_pp0_iter11_reg;
        din_sign_reg_409_pp0_iter13_reg <= din_sign_reg_409_pp0_iter12_reg;
        din_sign_reg_409_pp0_iter14_reg <= din_sign_reg_409_pp0_iter13_reg;
        din_sign_reg_409_pp0_iter15_reg <= din_sign_reg_409_pp0_iter14_reg;
        din_sign_reg_409_pp0_iter16_reg <= din_sign_reg_409_pp0_iter15_reg;
        din_sign_reg_409_pp0_iter17_reg <= din_sign_reg_409_pp0_iter16_reg;
        din_sign_reg_409_pp0_iter18_reg <= din_sign_reg_409_pp0_iter17_reg;
        din_sign_reg_409_pp0_iter19_reg <= din_sign_reg_409_pp0_iter18_reg;
        din_sign_reg_409_pp0_iter1_reg <= din_sign_reg_409;
        din_sign_reg_409_pp0_iter20_reg <= din_sign_reg_409_pp0_iter19_reg;
        din_sign_reg_409_pp0_iter21_reg <= din_sign_reg_409_pp0_iter20_reg;
        din_sign_reg_409_pp0_iter22_reg <= din_sign_reg_409_pp0_iter21_reg;
        din_sign_reg_409_pp0_iter23_reg <= din_sign_reg_409_pp0_iter22_reg;
        din_sign_reg_409_pp0_iter24_reg <= din_sign_reg_409_pp0_iter23_reg;
        din_sign_reg_409_pp0_iter25_reg <= din_sign_reg_409_pp0_iter24_reg;
        din_sign_reg_409_pp0_iter26_reg <= din_sign_reg_409_pp0_iter25_reg;
        din_sign_reg_409_pp0_iter27_reg <= din_sign_reg_409_pp0_iter26_reg;
        din_sign_reg_409_pp0_iter28_reg <= din_sign_reg_409_pp0_iter27_reg;
        din_sign_reg_409_pp0_iter29_reg <= din_sign_reg_409_pp0_iter28_reg;
        din_sign_reg_409_pp0_iter2_reg <= din_sign_reg_409_pp0_iter1_reg;
        din_sign_reg_409_pp0_iter30_reg <= din_sign_reg_409_pp0_iter29_reg;
        din_sign_reg_409_pp0_iter31_reg <= din_sign_reg_409_pp0_iter30_reg;
        din_sign_reg_409_pp0_iter32_reg <= din_sign_reg_409_pp0_iter31_reg;
        din_sign_reg_409_pp0_iter33_reg <= din_sign_reg_409_pp0_iter32_reg;
        din_sign_reg_409_pp0_iter34_reg <= din_sign_reg_409_pp0_iter33_reg;
        din_sign_reg_409_pp0_iter35_reg <= din_sign_reg_409_pp0_iter34_reg;
        din_sign_reg_409_pp0_iter36_reg <= din_sign_reg_409_pp0_iter35_reg;
        din_sign_reg_409_pp0_iter37_reg <= din_sign_reg_409_pp0_iter36_reg;
        din_sign_reg_409_pp0_iter38_reg <= din_sign_reg_409_pp0_iter37_reg;
        din_sign_reg_409_pp0_iter39_reg <= din_sign_reg_409_pp0_iter38_reg;
        din_sign_reg_409_pp0_iter3_reg <= din_sign_reg_409_pp0_iter2_reg;
        din_sign_reg_409_pp0_iter40_reg <= din_sign_reg_409_pp0_iter39_reg;
        din_sign_reg_409_pp0_iter41_reg <= din_sign_reg_409_pp0_iter40_reg;
        din_sign_reg_409_pp0_iter42_reg <= din_sign_reg_409_pp0_iter41_reg;
        din_sign_reg_409_pp0_iter43_reg <= din_sign_reg_409_pp0_iter42_reg;
        din_sign_reg_409_pp0_iter44_reg <= din_sign_reg_409_pp0_iter43_reg;
        din_sign_reg_409_pp0_iter45_reg <= din_sign_reg_409_pp0_iter44_reg;
        din_sign_reg_409_pp0_iter46_reg <= din_sign_reg_409_pp0_iter45_reg;
        din_sign_reg_409_pp0_iter47_reg <= din_sign_reg_409_pp0_iter46_reg;
        din_sign_reg_409_pp0_iter48_reg <= din_sign_reg_409_pp0_iter47_reg;
        din_sign_reg_409_pp0_iter49_reg <= din_sign_reg_409_pp0_iter48_reg;
        din_sign_reg_409_pp0_iter4_reg <= din_sign_reg_409_pp0_iter3_reg;
        din_sign_reg_409_pp0_iter50_reg <= din_sign_reg_409_pp0_iter49_reg;
        din_sign_reg_409_pp0_iter51_reg <= din_sign_reg_409_pp0_iter50_reg;
        din_sign_reg_409_pp0_iter5_reg <= din_sign_reg_409_pp0_iter4_reg;
        din_sign_reg_409_pp0_iter6_reg <= din_sign_reg_409_pp0_iter5_reg;
        din_sign_reg_409_pp0_iter7_reg <= din_sign_reg_409_pp0_iter6_reg;
        din_sign_reg_409_pp0_iter8_reg <= din_sign_reg_409_pp0_iter7_reg;
        din_sign_reg_409_pp0_iter9_reg <= din_sign_reg_409_pp0_iter8_reg;
        expx_reg_62 <= ap_phi_reg_pp0_iter21_expx_reg_62;
        expx_reg_62_pp0_iter22_reg <= expx_reg_62;
        expx_reg_62_pp0_iter23_reg <= expx_reg_62_pp0_iter22_reg;
        expx_reg_62_pp0_iter24_reg <= expx_reg_62_pp0_iter23_reg;
        expx_reg_62_pp0_iter25_reg <= expx_reg_62_pp0_iter24_reg;
        icmp_ln36_reg_434 <= icmp_ln36_fu_196_p2;
        icmp_ln36_reg_434_pp0_iter10_reg <= icmp_ln36_reg_434_pp0_iter9_reg;
        icmp_ln36_reg_434_pp0_iter11_reg <= icmp_ln36_reg_434_pp0_iter10_reg;
        icmp_ln36_reg_434_pp0_iter12_reg <= icmp_ln36_reg_434_pp0_iter11_reg;
        icmp_ln36_reg_434_pp0_iter13_reg <= icmp_ln36_reg_434_pp0_iter12_reg;
        icmp_ln36_reg_434_pp0_iter14_reg <= icmp_ln36_reg_434_pp0_iter13_reg;
        icmp_ln36_reg_434_pp0_iter15_reg <= icmp_ln36_reg_434_pp0_iter14_reg;
        icmp_ln36_reg_434_pp0_iter16_reg <= icmp_ln36_reg_434_pp0_iter15_reg;
        icmp_ln36_reg_434_pp0_iter17_reg <= icmp_ln36_reg_434_pp0_iter16_reg;
        icmp_ln36_reg_434_pp0_iter18_reg <= icmp_ln36_reg_434_pp0_iter17_reg;
        icmp_ln36_reg_434_pp0_iter19_reg <= icmp_ln36_reg_434_pp0_iter18_reg;
        icmp_ln36_reg_434_pp0_iter1_reg <= icmp_ln36_reg_434;
        icmp_ln36_reg_434_pp0_iter20_reg <= icmp_ln36_reg_434_pp0_iter19_reg;
        icmp_ln36_reg_434_pp0_iter21_reg <= icmp_ln36_reg_434_pp0_iter20_reg;
        icmp_ln36_reg_434_pp0_iter22_reg <= icmp_ln36_reg_434_pp0_iter21_reg;
        icmp_ln36_reg_434_pp0_iter23_reg <= icmp_ln36_reg_434_pp0_iter22_reg;
        icmp_ln36_reg_434_pp0_iter24_reg <= icmp_ln36_reg_434_pp0_iter23_reg;
        icmp_ln36_reg_434_pp0_iter25_reg <= icmp_ln36_reg_434_pp0_iter24_reg;
        icmp_ln36_reg_434_pp0_iter26_reg <= icmp_ln36_reg_434_pp0_iter25_reg;
        icmp_ln36_reg_434_pp0_iter27_reg <= icmp_ln36_reg_434_pp0_iter26_reg;
        icmp_ln36_reg_434_pp0_iter28_reg <= icmp_ln36_reg_434_pp0_iter27_reg;
        icmp_ln36_reg_434_pp0_iter29_reg <= icmp_ln36_reg_434_pp0_iter28_reg;
        icmp_ln36_reg_434_pp0_iter2_reg <= icmp_ln36_reg_434_pp0_iter1_reg;
        icmp_ln36_reg_434_pp0_iter30_reg <= icmp_ln36_reg_434_pp0_iter29_reg;
        icmp_ln36_reg_434_pp0_iter31_reg <= icmp_ln36_reg_434_pp0_iter30_reg;
        icmp_ln36_reg_434_pp0_iter32_reg <= icmp_ln36_reg_434_pp0_iter31_reg;
        icmp_ln36_reg_434_pp0_iter33_reg <= icmp_ln36_reg_434_pp0_iter32_reg;
        icmp_ln36_reg_434_pp0_iter34_reg <= icmp_ln36_reg_434_pp0_iter33_reg;
        icmp_ln36_reg_434_pp0_iter35_reg <= icmp_ln36_reg_434_pp0_iter34_reg;
        icmp_ln36_reg_434_pp0_iter36_reg <= icmp_ln36_reg_434_pp0_iter35_reg;
        icmp_ln36_reg_434_pp0_iter37_reg <= icmp_ln36_reg_434_pp0_iter36_reg;
        icmp_ln36_reg_434_pp0_iter38_reg <= icmp_ln36_reg_434_pp0_iter37_reg;
        icmp_ln36_reg_434_pp0_iter39_reg <= icmp_ln36_reg_434_pp0_iter38_reg;
        icmp_ln36_reg_434_pp0_iter3_reg <= icmp_ln36_reg_434_pp0_iter2_reg;
        icmp_ln36_reg_434_pp0_iter40_reg <= icmp_ln36_reg_434_pp0_iter39_reg;
        icmp_ln36_reg_434_pp0_iter41_reg <= icmp_ln36_reg_434_pp0_iter40_reg;
        icmp_ln36_reg_434_pp0_iter42_reg <= icmp_ln36_reg_434_pp0_iter41_reg;
        icmp_ln36_reg_434_pp0_iter43_reg <= icmp_ln36_reg_434_pp0_iter42_reg;
        icmp_ln36_reg_434_pp0_iter44_reg <= icmp_ln36_reg_434_pp0_iter43_reg;
        icmp_ln36_reg_434_pp0_iter45_reg <= icmp_ln36_reg_434_pp0_iter44_reg;
        icmp_ln36_reg_434_pp0_iter46_reg <= icmp_ln36_reg_434_pp0_iter45_reg;
        icmp_ln36_reg_434_pp0_iter47_reg <= icmp_ln36_reg_434_pp0_iter46_reg;
        icmp_ln36_reg_434_pp0_iter48_reg <= icmp_ln36_reg_434_pp0_iter47_reg;
        icmp_ln36_reg_434_pp0_iter49_reg <= icmp_ln36_reg_434_pp0_iter48_reg;
        icmp_ln36_reg_434_pp0_iter4_reg <= icmp_ln36_reg_434_pp0_iter3_reg;
        icmp_ln36_reg_434_pp0_iter50_reg <= icmp_ln36_reg_434_pp0_iter49_reg;
        icmp_ln36_reg_434_pp0_iter51_reg <= icmp_ln36_reg_434_pp0_iter50_reg;
        icmp_ln36_reg_434_pp0_iter5_reg <= icmp_ln36_reg_434_pp0_iter4_reg;
        icmp_ln36_reg_434_pp0_iter6_reg <= icmp_ln36_reg_434_pp0_iter5_reg;
        icmp_ln36_reg_434_pp0_iter7_reg <= icmp_ln36_reg_434_pp0_iter6_reg;
        icmp_ln36_reg_434_pp0_iter8_reg <= icmp_ln36_reg_434_pp0_iter7_reg;
        icmp_ln36_reg_434_pp0_iter9_reg <= icmp_ln36_reg_434_pp0_iter8_reg;
        icmp_ln38_reg_446 <= icmp_ln38_fu_226_p2;
        icmp_ln38_reg_446_pp0_iter10_reg <= icmp_ln38_reg_446_pp0_iter9_reg;
        icmp_ln38_reg_446_pp0_iter11_reg <= icmp_ln38_reg_446_pp0_iter10_reg;
        icmp_ln38_reg_446_pp0_iter12_reg <= icmp_ln38_reg_446_pp0_iter11_reg;
        icmp_ln38_reg_446_pp0_iter13_reg <= icmp_ln38_reg_446_pp0_iter12_reg;
        icmp_ln38_reg_446_pp0_iter14_reg <= icmp_ln38_reg_446_pp0_iter13_reg;
        icmp_ln38_reg_446_pp0_iter15_reg <= icmp_ln38_reg_446_pp0_iter14_reg;
        icmp_ln38_reg_446_pp0_iter16_reg <= icmp_ln38_reg_446_pp0_iter15_reg;
        icmp_ln38_reg_446_pp0_iter17_reg <= icmp_ln38_reg_446_pp0_iter16_reg;
        icmp_ln38_reg_446_pp0_iter18_reg <= icmp_ln38_reg_446_pp0_iter17_reg;
        icmp_ln38_reg_446_pp0_iter19_reg <= icmp_ln38_reg_446_pp0_iter18_reg;
        icmp_ln38_reg_446_pp0_iter1_reg <= icmp_ln38_reg_446;
        icmp_ln38_reg_446_pp0_iter20_reg <= icmp_ln38_reg_446_pp0_iter19_reg;
        icmp_ln38_reg_446_pp0_iter21_reg <= icmp_ln38_reg_446_pp0_iter20_reg;
        icmp_ln38_reg_446_pp0_iter22_reg <= icmp_ln38_reg_446_pp0_iter21_reg;
        icmp_ln38_reg_446_pp0_iter23_reg <= icmp_ln38_reg_446_pp0_iter22_reg;
        icmp_ln38_reg_446_pp0_iter24_reg <= icmp_ln38_reg_446_pp0_iter23_reg;
        icmp_ln38_reg_446_pp0_iter25_reg <= icmp_ln38_reg_446_pp0_iter24_reg;
        icmp_ln38_reg_446_pp0_iter26_reg <= icmp_ln38_reg_446_pp0_iter25_reg;
        icmp_ln38_reg_446_pp0_iter27_reg <= icmp_ln38_reg_446_pp0_iter26_reg;
        icmp_ln38_reg_446_pp0_iter28_reg <= icmp_ln38_reg_446_pp0_iter27_reg;
        icmp_ln38_reg_446_pp0_iter29_reg <= icmp_ln38_reg_446_pp0_iter28_reg;
        icmp_ln38_reg_446_pp0_iter2_reg <= icmp_ln38_reg_446_pp0_iter1_reg;
        icmp_ln38_reg_446_pp0_iter30_reg <= icmp_ln38_reg_446_pp0_iter29_reg;
        icmp_ln38_reg_446_pp0_iter31_reg <= icmp_ln38_reg_446_pp0_iter30_reg;
        icmp_ln38_reg_446_pp0_iter32_reg <= icmp_ln38_reg_446_pp0_iter31_reg;
        icmp_ln38_reg_446_pp0_iter33_reg <= icmp_ln38_reg_446_pp0_iter32_reg;
        icmp_ln38_reg_446_pp0_iter34_reg <= icmp_ln38_reg_446_pp0_iter33_reg;
        icmp_ln38_reg_446_pp0_iter35_reg <= icmp_ln38_reg_446_pp0_iter34_reg;
        icmp_ln38_reg_446_pp0_iter36_reg <= icmp_ln38_reg_446_pp0_iter35_reg;
        icmp_ln38_reg_446_pp0_iter37_reg <= icmp_ln38_reg_446_pp0_iter36_reg;
        icmp_ln38_reg_446_pp0_iter38_reg <= icmp_ln38_reg_446_pp0_iter37_reg;
        icmp_ln38_reg_446_pp0_iter39_reg <= icmp_ln38_reg_446_pp0_iter38_reg;
        icmp_ln38_reg_446_pp0_iter3_reg <= icmp_ln38_reg_446_pp0_iter2_reg;
        icmp_ln38_reg_446_pp0_iter40_reg <= icmp_ln38_reg_446_pp0_iter39_reg;
        icmp_ln38_reg_446_pp0_iter41_reg <= icmp_ln38_reg_446_pp0_iter40_reg;
        icmp_ln38_reg_446_pp0_iter42_reg <= icmp_ln38_reg_446_pp0_iter41_reg;
        icmp_ln38_reg_446_pp0_iter43_reg <= icmp_ln38_reg_446_pp0_iter42_reg;
        icmp_ln38_reg_446_pp0_iter44_reg <= icmp_ln38_reg_446_pp0_iter43_reg;
        icmp_ln38_reg_446_pp0_iter45_reg <= icmp_ln38_reg_446_pp0_iter44_reg;
        icmp_ln38_reg_446_pp0_iter46_reg <= icmp_ln38_reg_446_pp0_iter45_reg;
        icmp_ln38_reg_446_pp0_iter47_reg <= icmp_ln38_reg_446_pp0_iter46_reg;
        icmp_ln38_reg_446_pp0_iter48_reg <= icmp_ln38_reg_446_pp0_iter47_reg;
        icmp_ln38_reg_446_pp0_iter49_reg <= icmp_ln38_reg_446_pp0_iter48_reg;
        icmp_ln38_reg_446_pp0_iter4_reg <= icmp_ln38_reg_446_pp0_iter3_reg;
        icmp_ln38_reg_446_pp0_iter50_reg <= icmp_ln38_reg_446_pp0_iter49_reg;
        icmp_ln38_reg_446_pp0_iter5_reg <= icmp_ln38_reg_446_pp0_iter4_reg;
        icmp_ln38_reg_446_pp0_iter6_reg <= icmp_ln38_reg_446_pp0_iter5_reg;
        icmp_ln38_reg_446_pp0_iter7_reg <= icmp_ln38_reg_446_pp0_iter6_reg;
        icmp_ln38_reg_446_pp0_iter8_reg <= icmp_ln38_reg_446_pp0_iter7_reg;
        icmp_ln38_reg_446_pp0_iter9_reg <= icmp_ln38_reg_446_pp0_iter8_reg;
        icmp_ln45_reg_438 <= icmp_ln45_fu_202_p2;
        icmp_ln45_reg_438_pp0_iter10_reg <= icmp_ln45_reg_438_pp0_iter9_reg;
        icmp_ln45_reg_438_pp0_iter11_reg <= icmp_ln45_reg_438_pp0_iter10_reg;
        icmp_ln45_reg_438_pp0_iter12_reg <= icmp_ln45_reg_438_pp0_iter11_reg;
        icmp_ln45_reg_438_pp0_iter13_reg <= icmp_ln45_reg_438_pp0_iter12_reg;
        icmp_ln45_reg_438_pp0_iter14_reg <= icmp_ln45_reg_438_pp0_iter13_reg;
        icmp_ln45_reg_438_pp0_iter15_reg <= icmp_ln45_reg_438_pp0_iter14_reg;
        icmp_ln45_reg_438_pp0_iter16_reg <= icmp_ln45_reg_438_pp0_iter15_reg;
        icmp_ln45_reg_438_pp0_iter17_reg <= icmp_ln45_reg_438_pp0_iter16_reg;
        icmp_ln45_reg_438_pp0_iter18_reg <= icmp_ln45_reg_438_pp0_iter17_reg;
        icmp_ln45_reg_438_pp0_iter19_reg <= icmp_ln45_reg_438_pp0_iter18_reg;
        icmp_ln45_reg_438_pp0_iter1_reg <= icmp_ln45_reg_438;
        icmp_ln45_reg_438_pp0_iter20_reg <= icmp_ln45_reg_438_pp0_iter19_reg;
        icmp_ln45_reg_438_pp0_iter21_reg <= icmp_ln45_reg_438_pp0_iter20_reg;
        icmp_ln45_reg_438_pp0_iter22_reg <= icmp_ln45_reg_438_pp0_iter21_reg;
        icmp_ln45_reg_438_pp0_iter23_reg <= icmp_ln45_reg_438_pp0_iter22_reg;
        icmp_ln45_reg_438_pp0_iter24_reg <= icmp_ln45_reg_438_pp0_iter23_reg;
        icmp_ln45_reg_438_pp0_iter25_reg <= icmp_ln45_reg_438_pp0_iter24_reg;
        icmp_ln45_reg_438_pp0_iter26_reg <= icmp_ln45_reg_438_pp0_iter25_reg;
        icmp_ln45_reg_438_pp0_iter27_reg <= icmp_ln45_reg_438_pp0_iter26_reg;
        icmp_ln45_reg_438_pp0_iter28_reg <= icmp_ln45_reg_438_pp0_iter27_reg;
        icmp_ln45_reg_438_pp0_iter29_reg <= icmp_ln45_reg_438_pp0_iter28_reg;
        icmp_ln45_reg_438_pp0_iter2_reg <= icmp_ln45_reg_438_pp0_iter1_reg;
        icmp_ln45_reg_438_pp0_iter30_reg <= icmp_ln45_reg_438_pp0_iter29_reg;
        icmp_ln45_reg_438_pp0_iter31_reg <= icmp_ln45_reg_438_pp0_iter30_reg;
        icmp_ln45_reg_438_pp0_iter32_reg <= icmp_ln45_reg_438_pp0_iter31_reg;
        icmp_ln45_reg_438_pp0_iter33_reg <= icmp_ln45_reg_438_pp0_iter32_reg;
        icmp_ln45_reg_438_pp0_iter34_reg <= icmp_ln45_reg_438_pp0_iter33_reg;
        icmp_ln45_reg_438_pp0_iter35_reg <= icmp_ln45_reg_438_pp0_iter34_reg;
        icmp_ln45_reg_438_pp0_iter36_reg <= icmp_ln45_reg_438_pp0_iter35_reg;
        icmp_ln45_reg_438_pp0_iter37_reg <= icmp_ln45_reg_438_pp0_iter36_reg;
        icmp_ln45_reg_438_pp0_iter38_reg <= icmp_ln45_reg_438_pp0_iter37_reg;
        icmp_ln45_reg_438_pp0_iter39_reg <= icmp_ln45_reg_438_pp0_iter38_reg;
        icmp_ln45_reg_438_pp0_iter3_reg <= icmp_ln45_reg_438_pp0_iter2_reg;
        icmp_ln45_reg_438_pp0_iter40_reg <= icmp_ln45_reg_438_pp0_iter39_reg;
        icmp_ln45_reg_438_pp0_iter41_reg <= icmp_ln45_reg_438_pp0_iter40_reg;
        icmp_ln45_reg_438_pp0_iter42_reg <= icmp_ln45_reg_438_pp0_iter41_reg;
        icmp_ln45_reg_438_pp0_iter43_reg <= icmp_ln45_reg_438_pp0_iter42_reg;
        icmp_ln45_reg_438_pp0_iter44_reg <= icmp_ln45_reg_438_pp0_iter43_reg;
        icmp_ln45_reg_438_pp0_iter45_reg <= icmp_ln45_reg_438_pp0_iter44_reg;
        icmp_ln45_reg_438_pp0_iter46_reg <= icmp_ln45_reg_438_pp0_iter45_reg;
        icmp_ln45_reg_438_pp0_iter47_reg <= icmp_ln45_reg_438_pp0_iter46_reg;
        icmp_ln45_reg_438_pp0_iter48_reg <= icmp_ln45_reg_438_pp0_iter47_reg;
        icmp_ln45_reg_438_pp0_iter49_reg <= icmp_ln45_reg_438_pp0_iter48_reg;
        icmp_ln45_reg_438_pp0_iter4_reg <= icmp_ln45_reg_438_pp0_iter3_reg;
        icmp_ln45_reg_438_pp0_iter50_reg <= icmp_ln45_reg_438_pp0_iter49_reg;
        icmp_ln45_reg_438_pp0_iter51_reg <= icmp_ln45_reg_438_pp0_iter50_reg;
        icmp_ln45_reg_438_pp0_iter5_reg <= icmp_ln45_reg_438_pp0_iter4_reg;
        icmp_ln45_reg_438_pp0_iter6_reg <= icmp_ln45_reg_438_pp0_iter5_reg;
        icmp_ln45_reg_438_pp0_iter7_reg <= icmp_ln45_reg_438_pp0_iter6_reg;
        icmp_ln45_reg_438_pp0_iter8_reg <= icmp_ln45_reg_438_pp0_iter7_reg;
        icmp_ln45_reg_438_pp0_iter9_reg <= icmp_ln45_reg_438_pp0_iter8_reg;
        icmp_ln54_reg_455 <= icmp_ln54_fu_232_p2;
        icmp_ln54_reg_455_pp0_iter10_reg <= icmp_ln54_reg_455_pp0_iter9_reg;
        icmp_ln54_reg_455_pp0_iter11_reg <= icmp_ln54_reg_455_pp0_iter10_reg;
        icmp_ln54_reg_455_pp0_iter12_reg <= icmp_ln54_reg_455_pp0_iter11_reg;
        icmp_ln54_reg_455_pp0_iter13_reg <= icmp_ln54_reg_455_pp0_iter12_reg;
        icmp_ln54_reg_455_pp0_iter14_reg <= icmp_ln54_reg_455_pp0_iter13_reg;
        icmp_ln54_reg_455_pp0_iter15_reg <= icmp_ln54_reg_455_pp0_iter14_reg;
        icmp_ln54_reg_455_pp0_iter16_reg <= icmp_ln54_reg_455_pp0_iter15_reg;
        icmp_ln54_reg_455_pp0_iter17_reg <= icmp_ln54_reg_455_pp0_iter16_reg;
        icmp_ln54_reg_455_pp0_iter18_reg <= icmp_ln54_reg_455_pp0_iter17_reg;
        icmp_ln54_reg_455_pp0_iter19_reg <= icmp_ln54_reg_455_pp0_iter18_reg;
        icmp_ln54_reg_455_pp0_iter20_reg <= icmp_ln54_reg_455_pp0_iter19_reg;
        icmp_ln54_reg_455_pp0_iter21_reg <= icmp_ln54_reg_455_pp0_iter20_reg;
        icmp_ln54_reg_455_pp0_iter22_reg <= icmp_ln54_reg_455_pp0_iter21_reg;
        icmp_ln54_reg_455_pp0_iter23_reg <= icmp_ln54_reg_455_pp0_iter22_reg;
        icmp_ln54_reg_455_pp0_iter24_reg <= icmp_ln54_reg_455_pp0_iter23_reg;
        icmp_ln54_reg_455_pp0_iter25_reg <= icmp_ln54_reg_455_pp0_iter24_reg;
        icmp_ln54_reg_455_pp0_iter26_reg <= icmp_ln54_reg_455_pp0_iter25_reg;
        icmp_ln54_reg_455_pp0_iter27_reg <= icmp_ln54_reg_455_pp0_iter26_reg;
        icmp_ln54_reg_455_pp0_iter28_reg <= icmp_ln54_reg_455_pp0_iter27_reg;
        icmp_ln54_reg_455_pp0_iter29_reg <= icmp_ln54_reg_455_pp0_iter28_reg;
        icmp_ln54_reg_455_pp0_iter2_reg <= icmp_ln54_reg_455;
        icmp_ln54_reg_455_pp0_iter30_reg <= icmp_ln54_reg_455_pp0_iter29_reg;
        icmp_ln54_reg_455_pp0_iter31_reg <= icmp_ln54_reg_455_pp0_iter30_reg;
        icmp_ln54_reg_455_pp0_iter32_reg <= icmp_ln54_reg_455_pp0_iter31_reg;
        icmp_ln54_reg_455_pp0_iter33_reg <= icmp_ln54_reg_455_pp0_iter32_reg;
        icmp_ln54_reg_455_pp0_iter34_reg <= icmp_ln54_reg_455_pp0_iter33_reg;
        icmp_ln54_reg_455_pp0_iter35_reg <= icmp_ln54_reg_455_pp0_iter34_reg;
        icmp_ln54_reg_455_pp0_iter36_reg <= icmp_ln54_reg_455_pp0_iter35_reg;
        icmp_ln54_reg_455_pp0_iter37_reg <= icmp_ln54_reg_455_pp0_iter36_reg;
        icmp_ln54_reg_455_pp0_iter38_reg <= icmp_ln54_reg_455_pp0_iter37_reg;
        icmp_ln54_reg_455_pp0_iter39_reg <= icmp_ln54_reg_455_pp0_iter38_reg;
        icmp_ln54_reg_455_pp0_iter3_reg <= icmp_ln54_reg_455_pp0_iter2_reg;
        icmp_ln54_reg_455_pp0_iter40_reg <= icmp_ln54_reg_455_pp0_iter39_reg;
        icmp_ln54_reg_455_pp0_iter41_reg <= icmp_ln54_reg_455_pp0_iter40_reg;
        icmp_ln54_reg_455_pp0_iter42_reg <= icmp_ln54_reg_455_pp0_iter41_reg;
        icmp_ln54_reg_455_pp0_iter43_reg <= icmp_ln54_reg_455_pp0_iter42_reg;
        icmp_ln54_reg_455_pp0_iter44_reg <= icmp_ln54_reg_455_pp0_iter43_reg;
        icmp_ln54_reg_455_pp0_iter45_reg <= icmp_ln54_reg_455_pp0_iter44_reg;
        icmp_ln54_reg_455_pp0_iter46_reg <= icmp_ln54_reg_455_pp0_iter45_reg;
        icmp_ln54_reg_455_pp0_iter47_reg <= icmp_ln54_reg_455_pp0_iter46_reg;
        icmp_ln54_reg_455_pp0_iter48_reg <= icmp_ln54_reg_455_pp0_iter47_reg;
        icmp_ln54_reg_455_pp0_iter49_reg <= icmp_ln54_reg_455_pp0_iter48_reg;
        icmp_ln54_reg_455_pp0_iter4_reg <= icmp_ln54_reg_455_pp0_iter3_reg;
        icmp_ln54_reg_455_pp0_iter50_reg <= icmp_ln54_reg_455_pp0_iter49_reg;
        icmp_ln54_reg_455_pp0_iter51_reg <= icmp_ln54_reg_455_pp0_iter50_reg;
        icmp_ln54_reg_455_pp0_iter5_reg <= icmp_ln54_reg_455_pp0_iter4_reg;
        icmp_ln54_reg_455_pp0_iter6_reg <= icmp_ln54_reg_455_pp0_iter5_reg;
        icmp_ln54_reg_455_pp0_iter7_reg <= icmp_ln54_reg_455_pp0_iter6_reg;
        icmp_ln54_reg_455_pp0_iter8_reg <= icmp_ln54_reg_455_pp0_iter7_reg;
        icmp_ln54_reg_455_pp0_iter9_reg <= icmp_ln54_reg_455_pp0_iter8_reg;
        resultf_reg_485 <= grp_fu_132_p2;
        tmp_2_reg_490 <= grp_exp_generic_double_s_fu_91_ap_return;
        tmp_7_reg_451 <= grp_fu_141_p2;
        tmp_7_reg_451_pp0_iter10_reg <= tmp_7_reg_451_pp0_iter9_reg;
        tmp_7_reg_451_pp0_iter11_reg <= tmp_7_reg_451_pp0_iter10_reg;
        tmp_7_reg_451_pp0_iter12_reg <= tmp_7_reg_451_pp0_iter11_reg;
        tmp_7_reg_451_pp0_iter13_reg <= tmp_7_reg_451_pp0_iter12_reg;
        tmp_7_reg_451_pp0_iter14_reg <= tmp_7_reg_451_pp0_iter13_reg;
        tmp_7_reg_451_pp0_iter15_reg <= tmp_7_reg_451_pp0_iter14_reg;
        tmp_7_reg_451_pp0_iter16_reg <= tmp_7_reg_451_pp0_iter15_reg;
        tmp_7_reg_451_pp0_iter17_reg <= tmp_7_reg_451_pp0_iter16_reg;
        tmp_7_reg_451_pp0_iter18_reg <= tmp_7_reg_451_pp0_iter17_reg;
        tmp_7_reg_451_pp0_iter19_reg <= tmp_7_reg_451_pp0_iter18_reg;
        tmp_7_reg_451_pp0_iter20_reg <= tmp_7_reg_451_pp0_iter19_reg;
        tmp_7_reg_451_pp0_iter21_reg <= tmp_7_reg_451_pp0_iter20_reg;
        tmp_7_reg_451_pp0_iter22_reg <= tmp_7_reg_451_pp0_iter21_reg;
        tmp_7_reg_451_pp0_iter23_reg <= tmp_7_reg_451_pp0_iter22_reg;
        tmp_7_reg_451_pp0_iter24_reg <= tmp_7_reg_451_pp0_iter23_reg;
        tmp_7_reg_451_pp0_iter25_reg <= tmp_7_reg_451_pp0_iter24_reg;
        tmp_7_reg_451_pp0_iter26_reg <= tmp_7_reg_451_pp0_iter25_reg;
        tmp_7_reg_451_pp0_iter27_reg <= tmp_7_reg_451_pp0_iter26_reg;
        tmp_7_reg_451_pp0_iter28_reg <= tmp_7_reg_451_pp0_iter27_reg;
        tmp_7_reg_451_pp0_iter29_reg <= tmp_7_reg_451_pp0_iter28_reg;
        tmp_7_reg_451_pp0_iter2_reg <= tmp_7_reg_451;
        tmp_7_reg_451_pp0_iter30_reg <= tmp_7_reg_451_pp0_iter29_reg;
        tmp_7_reg_451_pp0_iter31_reg <= tmp_7_reg_451_pp0_iter30_reg;
        tmp_7_reg_451_pp0_iter32_reg <= tmp_7_reg_451_pp0_iter31_reg;
        tmp_7_reg_451_pp0_iter33_reg <= tmp_7_reg_451_pp0_iter32_reg;
        tmp_7_reg_451_pp0_iter34_reg <= tmp_7_reg_451_pp0_iter33_reg;
        tmp_7_reg_451_pp0_iter35_reg <= tmp_7_reg_451_pp0_iter34_reg;
        tmp_7_reg_451_pp0_iter36_reg <= tmp_7_reg_451_pp0_iter35_reg;
        tmp_7_reg_451_pp0_iter37_reg <= tmp_7_reg_451_pp0_iter36_reg;
        tmp_7_reg_451_pp0_iter38_reg <= tmp_7_reg_451_pp0_iter37_reg;
        tmp_7_reg_451_pp0_iter39_reg <= tmp_7_reg_451_pp0_iter38_reg;
        tmp_7_reg_451_pp0_iter3_reg <= tmp_7_reg_451_pp0_iter2_reg;
        tmp_7_reg_451_pp0_iter40_reg <= tmp_7_reg_451_pp0_iter39_reg;
        tmp_7_reg_451_pp0_iter41_reg <= tmp_7_reg_451_pp0_iter40_reg;
        tmp_7_reg_451_pp0_iter42_reg <= tmp_7_reg_451_pp0_iter41_reg;
        tmp_7_reg_451_pp0_iter43_reg <= tmp_7_reg_451_pp0_iter42_reg;
        tmp_7_reg_451_pp0_iter44_reg <= tmp_7_reg_451_pp0_iter43_reg;
        tmp_7_reg_451_pp0_iter45_reg <= tmp_7_reg_451_pp0_iter44_reg;
        tmp_7_reg_451_pp0_iter46_reg <= tmp_7_reg_451_pp0_iter45_reg;
        tmp_7_reg_451_pp0_iter47_reg <= tmp_7_reg_451_pp0_iter46_reg;
        tmp_7_reg_451_pp0_iter48_reg <= tmp_7_reg_451_pp0_iter47_reg;
        tmp_7_reg_451_pp0_iter49_reg <= tmp_7_reg_451_pp0_iter48_reg;
        tmp_7_reg_451_pp0_iter4_reg <= tmp_7_reg_451_pp0_iter3_reg;
        tmp_7_reg_451_pp0_iter50_reg <= tmp_7_reg_451_pp0_iter49_reg;
        tmp_7_reg_451_pp0_iter51_reg <= tmp_7_reg_451_pp0_iter50_reg;
        tmp_7_reg_451_pp0_iter5_reg <= tmp_7_reg_451_pp0_iter4_reg;
        tmp_7_reg_451_pp0_iter6_reg <= tmp_7_reg_451_pp0_iter5_reg;
        tmp_7_reg_451_pp0_iter7_reg <= tmp_7_reg_451_pp0_iter6_reg;
        tmp_7_reg_451_pp0_iter8_reg <= tmp_7_reg_451_pp0_iter7_reg;
        tmp_7_reg_451_pp0_iter9_reg <= tmp_7_reg_451_pp0_iter8_reg;
        trunc_ln479_reg_419 <= trunc_ln479_fu_178_p1;
        x_3_reg_470 <= x_3_fu_249_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln79_fu_402_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_pred59_state48 == 1'b1) & (1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_pred49_state48 == 1'b1) & (1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_146 <= grp_fu_136_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        t_in_int_reg <= t_in;
    end
end

always @ (*) begin
    if (((icmp_ln54_reg_455_pp0_iter51_reg == 1'd0) & (tmp_7_reg_451_pp0_iter51_reg == 1'd1) & (1'd0 == and_ln46_reg_442_pp0_iter51_reg) & (icmp_ln45_reg_438_pp0_iter51_reg == 1'd0) & (icmp_ln36_reg_434_pp0_iter51_reg == 1'd0))) begin
        ap_phi_mux_resultf_3_phi_fu_78_p10 = grp_fu_126_p2;
    end else begin
        ap_phi_mux_resultf_3_phi_fu_78_p10 = ap_phi_reg_pp0_iter52_resultf_3_reg_74;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln79_fu_402_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp108))) begin
        grp_exp_generic_double_s_fu_91_ap_ce = 1'b1;
    end else begin
        grp_exp_generic_double_s_fu_91_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_102_ce = 1'b1;
    end else begin
        grp_fu_102_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_107_ce = 1'b1;
    end else begin
        grp_fu_107_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_111_ce = 1'b1;
    end else begin
        grp_fu_111_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_115_ce = 1'b1;
    end else begin
        grp_fu_115_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_120_ce = 1'b1;
    end else begin
        grp_fu_120_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_126_ce = 1'b1;
    end else begin
        grp_fu_126_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_132_ce = 1'b1;
    end else begin
        grp_fu_132_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_136_ce = 1'b1;
    end else begin
        grp_fu_136_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_pred902_state27 == 1'b1)) begin
            grp_fu_136_p0 = bitcast_ln66_1_fu_356_p1;
        end else if ((ap_predicate_pred897_state27 == 1'b1)) begin
            grp_fu_136_p0 = 64'd4611686018427387904;
        end else begin
            grp_fu_136_p0 = 'bx;
        end
    end else begin
        grp_fu_136_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_141_ce = 1'b1;
    end else begin
        grp_fu_141_ce = 1'b0;
    end
end

assign abst_in_fu_190_p1 = t_fu_182_p3;

assign and_ln10_1_fu_320_p2 = (icmp_ln10_fu_308_p2 & and_ln10_fu_314_p2);

assign and_ln10_fu_314_p2 = (xor_ln10_fu_302_p2 & icmp_ln9_1_fu_284_p2);

assign and_ln46_fu_220_p2 = (icmp_ln46_fu_208_p2 & icmp_ln46_1_fu_214_p2);

assign and_ln9_1_fu_296_p2 = (tmp_fu_270_p3 & and_ln9_fu_290_p2);

assign and_ln9_fu_290_p2 = (icmp_ln9_fu_278_p2 & icmp_ln9_1_fu_284_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp108 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp108 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_828 = (((icmp_ln45_reg_438_pp0_iter9_reg == 1'd1) & (icmp_ln36_reg_434_pp0_iter9_reg == 1'd0)) | ((1'd1 == and_ln46_reg_442_pp0_iter9_reg) & (icmp_ln36_reg_434_pp0_iter9_reg == 1'd0)));
end

always @ (*) begin
    ap_condition_861 = ((grp_fu_141_p2 == 1'd0) & (icmp_ln45_reg_438 == 1'd0) & (1'd0 == and_ln46_reg_442) & (icmp_ln36_reg_434 == 1'd0));
end

assign ap_phi_reg_pp0_iter0_expx_reg_62 = 'bx;

assign ap_phi_reg_pp0_iter0_resultf_3_reg_74 = 'bx;

always @ (*) begin
    ap_predicate_op108_call_state7 = ((tmp_7_reg_451_pp0_iter5_reg == 1'd1) & (1'd0 == and_ln10_1_reg_481) & (1'd0 == and_ln9_1_reg_477) & (1'd0 == and_ln46_reg_442_pp0_iter5_reg) & (icmp_ln45_reg_438_pp0_iter5_reg == 1'd0) & (icmp_ln36_reg_434_pp0_iter5_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op70_dcmp_state1 = ((1'd0 == and_ln46_fu_220_p2) & (icmp_ln45_fu_202_p2 == 1'd0) & (icmp_ln36_fu_196_p2 == 1'd0));
end

assign bit_sel1_fu_372_p3 = bitcast_ln83_fu_368_p1[64'd63];

assign bit_sel_fu_330_p3 = bitcast_ln66_fu_326_p1[64'd63];

assign bitcast_ln66_1_fu_356_p1 = xor_ln_fu_348_p3;

assign bitcast_ln66_fu_326_p1 = expx_reg_62_pp0_iter25_reg;

assign bitcast_ln83_1_fu_398_p1 = xor_ln1_fu_390_p3;

assign bitcast_ln83_fu_368_p1 = ap_phi_mux_resultf_3_phi_fu_78_p10;

assign data_2_fu_256_p1 = x_3_fu_249_p3;

assign data_fu_152_p1 = t_in_int_reg;

assign din_exp_fu_164_p4 = {{data_fu_152_p1[62:52]}};

assign din_sig_fu_174_p1 = data_fu_152_p1[51:0];

assign grp_fu_107_p0 = or_ln_fu_237_p3;

assign icmp_ln10_fu_308_p2 = ((xs_exp_2_fu_260_p4 < 11'd997) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_196_p2 = ((din_exp_fu_164_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_226_p2 = ((din_sig_fu_174_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_202_p2 = ((din_exp_fu_164_p4 < 11'd968) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_214_p2 = ((din_sig_fu_174_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_208_p2 = ((din_exp_fu_164_p4 == 11'd968) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_232_p2 = ((din_exp_reg_414 < 11'd1023) ? 1'b1 : 1'b0);

assign icmp_ln9_1_fu_284_p2 = ((xs_exp_2_fu_260_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_278_p2 = ((xs_exp_2_fu_260_p4 < 11'd996) ? 1'b1 : 1'b0);

assign or_ln_fu_237_p3 = {{1'd1}, {trunc_ln479_reg_419}};

assign select_ln38_fu_361_p3 = ((icmp_ln38_reg_446_pp0_iter50_reg[0:0] == 1'b1) ? 64'd9223372036854775807 : 64'd4607182418800017408);

assign select_ln79_fu_402_p3 = ((din_sign_reg_409_pp0_iter51_reg[0:0] == 1'b1) ? bitcast_ln83_1_fu_398_p1 : ap_phi_mux_resultf_3_phi_fu_78_p10);

assign t_fu_182_p3 = {{1'd0}, {trunc_ln479_fu_178_p1}};

assign tmp_fu_270_p3 = data_2_fu_256_p1[32'd63];

assign trunc_ln479_fu_178_p1 = data_fu_152_p1[62:0];

assign trunc_ln66_fu_344_p1 = bitcast_ln66_fu_326_p1[62:0];

assign trunc_ln83_fu_386_p1 = bitcast_ln83_fu_368_p1[62:0];

assign x_3_fu_249_p3 = ((icmp_ln54_reg_455_pp0_iter4_reg[0:0] == 1'b1) ? grp_fu_107_p2 : grp_fu_111_p2);

assign xor_ln10_fu_302_p2 = (tmp_fu_270_p3 ^ 1'd1);

assign xor_ln1_fu_390_p3 = {{xor_ln83_fu_380_p2}, {trunc_ln83_fu_386_p1}};

assign xor_ln66_fu_338_p2 = (bit_sel_fu_330_p3 ^ 1'd1);

assign xor_ln83_fu_380_p2 = (bit_sel1_fu_372_p3 ^ 1'd1);

assign xor_ln_fu_348_p3 = {{xor_ln66_fu_338_p2}, {trunc_ln66_fu_344_p1}};

assign xs_exp_2_fu_260_p4 = {{data_2_fu_256_p1[62:52]}};

always @ (posedge ap_clk) begin
    abst_in_reg_424[63] <= 1'b0;
    abst_in_reg_424_pp0_iter1_reg[63] <= 1'b0;
    abst_in_reg_424_pp0_iter2_reg[63] <= 1'b0;
    abst_in_reg_424_pp0_iter3_reg[63] <= 1'b0;
    abst_in_reg_424_pp0_iter4_reg[63] <= 1'b0;
end

endmodule //pedal_top_generic_tanh_double_s
