-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pedal_top_generic_fmod_mult_float_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of pedal_top_generic_fmod_mult_float_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_89 : STD_LOGIC_VECTOR (7 downto 0) := "10001001";
    constant ap_const_lv23_9BFFF : STD_LOGIC_VECTOR (22 downto 0) := "00010011011111111111111";
    constant ap_const_lv23_9C000 : STD_LOGIC_VECTOR (22 downto 0) := "00010011100000000000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv7_77 : STD_LOGIC_VECTOR (6 downto 0) := "1110111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv9_B : STD_LOGIC_VECTOR (8 downto 0) := "000001011";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv10_382 : STD_LOGIC_VECTOR (9 downto 0) := "1110000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ret_5_fu_117_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ret_5_reg_444_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_5_reg_444_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal fz_sig_fu_131_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451 : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter1_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter2_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter3_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter4_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter5_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter6_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter7_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter8_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter9_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal fz_sig_reg_451_pp0_iter10_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal isF_e_x_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457 : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isF_e_x_reg_457_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461 : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal isyBx_e_reg_461_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_fu_159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_reg_465_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln168_reg_469_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal n_fu_187_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal n_reg_473 : STD_LOGIC_VECTOR (6 downto 0);
    signal t_6_fu_201_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_7_fu_210_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mod_rcp_mult_24_36_8_s_fu_97_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal res_reg_493 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln206_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln206_reg_499 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_fu_224_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mod_rcp_mult_24_36_8_s_fu_97_r_sh : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_mod_rcp_mult_24_36_8_s_fu_97_ap_ce : STD_LOGIC;
    signal ap_predicate_op32_call_state2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp32 : BOOLEAN;
    signal ap_phi_mux_retval_1_in_phi_fu_83_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter4_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter5_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter6_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter7_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter8_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter9_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter10_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter11_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter12_retval_1_in_reg_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_8_fu_431_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_9_fu_420_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_ignoreCallOp32 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal fz_exp_fu_121_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln164_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln164_1_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln168_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fz_exp_cast_fu_177_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_103_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln204_fu_232_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_s_fu_235_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_132_fu_245_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln211_fu_253_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_133_fu_257_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln211_fu_265_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln212_fu_287_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln212_fu_275_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln212_fu_296_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln212_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln212_fu_290_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln212_fu_302_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln212_fu_308_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal iy_fu_269_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln214_fu_326_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln217_fu_336_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal n_1_fu_340_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_mx_2_1_fu_316_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sub_ln218_fu_358_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln218_fu_354_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln218_1_fu_364_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln218_2_fu_374_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln213_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fz_exp_1_fu_330_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln218_fu_368_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln218_fu_378_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_156_fu_346_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_81_fu_396_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal empty_82_fu_400_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal empty_fu_392_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal empty_83_fu_404_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_fu_110_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal fz_exp_2_fu_384_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal fz_sig_1_fu_412_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal bitcast_ln327_fu_440_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_288 : BOOLEAN;
    signal ap_condition_276 : BOOLEAN;
    signal ap_condition_279 : BOOLEAN;

    component pedal_top_mod_rcp_mult_24_36_8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        r_sh : IN STD_LOGIC_VECTOR (23 downto 0);
        n : IN STD_LOGIC_VECTOR (6 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (23 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_mod_rcp_mult_24_36_8_s_fu_97 : component pedal_top_mod_rcp_mult_24_36_8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        r_sh => grp_mod_rcp_mult_24_36_8_s_fu_97_r_sh,
        n => n_reg_473,
        ap_return => grp_mod_rcp_mult_24_36_8_s_fu_97_ap_return,
        ap_ce => grp_mod_rcp_mult_24_36_8_s_fu_97_ap_ce);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;

    ap_phi_reg_pp0_iter12_retval_1_in_reg_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_279)) then 
                    ap_phi_reg_pp0_iter12_retval_1_in_reg_80 <= t_7_fu_210_p3;
                elsif ((ap_const_boolean_1 = ap_condition_276)) then 
                    ap_phi_reg_pp0_iter12_retval_1_in_reg_80 <= t_6_fu_201_p4;
                elsif ((isF_e_x_reg_457_pp0_iter10_reg = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter12_retval_1_in_reg_80 <= t_fu_224_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter12_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter11_retval_1_in_reg_80;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_retval_1_in_reg_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((isyBx_e_fu_141_p2 = ap_const_lv1_1) and (isF_e_x_fu_135_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_retval_1_in_reg_80 <= ret_5_fu_117_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter0_retval_1_in_reg_80;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter10_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter9_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter11_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter10_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter2_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter1_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter3_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter2_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter4_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter3_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter5_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter4_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter6_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter5_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter7_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter6_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter8_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter7_retval_1_in_reg_80;
                ap_phi_reg_pp0_iter9_retval_1_in_reg_80 <= ap_phi_reg_pp0_iter8_retval_1_in_reg_80;
                fz_sig_reg_451 <= fz_sig_fu_131_p1;
                fz_sig_reg_451_pp0_iter10_reg <= fz_sig_reg_451_pp0_iter9_reg;
                fz_sig_reg_451_pp0_iter1_reg <= fz_sig_reg_451;
                fz_sig_reg_451_pp0_iter2_reg <= fz_sig_reg_451_pp0_iter1_reg;
                fz_sig_reg_451_pp0_iter3_reg <= fz_sig_reg_451_pp0_iter2_reg;
                fz_sig_reg_451_pp0_iter4_reg <= fz_sig_reg_451_pp0_iter3_reg;
                fz_sig_reg_451_pp0_iter5_reg <= fz_sig_reg_451_pp0_iter4_reg;
                fz_sig_reg_451_pp0_iter6_reg <= fz_sig_reg_451_pp0_iter5_reg;
                fz_sig_reg_451_pp0_iter7_reg <= fz_sig_reg_451_pp0_iter6_reg;
                fz_sig_reg_451_pp0_iter8_reg <= fz_sig_reg_451_pp0_iter7_reg;
                fz_sig_reg_451_pp0_iter9_reg <= fz_sig_reg_451_pp0_iter8_reg;
                icmp_ln206_reg_499 <= icmp_ln206_fu_218_p2;
                isF_e_x_reg_457 <= isF_e_x_fu_135_p2;
                isF_e_x_reg_457_pp0_iter10_reg <= isF_e_x_reg_457_pp0_iter9_reg;
                isF_e_x_reg_457_pp0_iter11_reg <= isF_e_x_reg_457_pp0_iter10_reg;
                isF_e_x_reg_457_pp0_iter1_reg <= isF_e_x_reg_457;
                isF_e_x_reg_457_pp0_iter2_reg <= isF_e_x_reg_457_pp0_iter1_reg;
                isF_e_x_reg_457_pp0_iter3_reg <= isF_e_x_reg_457_pp0_iter2_reg;
                isF_e_x_reg_457_pp0_iter4_reg <= isF_e_x_reg_457_pp0_iter3_reg;
                isF_e_x_reg_457_pp0_iter5_reg <= isF_e_x_reg_457_pp0_iter4_reg;
                isF_e_x_reg_457_pp0_iter6_reg <= isF_e_x_reg_457_pp0_iter5_reg;
                isF_e_x_reg_457_pp0_iter7_reg <= isF_e_x_reg_457_pp0_iter6_reg;
                isF_e_x_reg_457_pp0_iter8_reg <= isF_e_x_reg_457_pp0_iter7_reg;
                isF_e_x_reg_457_pp0_iter9_reg <= isF_e_x_reg_457_pp0_iter8_reg;
                isyBx_e_reg_461 <= isyBx_e_fu_141_p2;
                isyBx_e_reg_461_pp0_iter10_reg <= isyBx_e_reg_461_pp0_iter9_reg;
                isyBx_e_reg_461_pp0_iter11_reg <= isyBx_e_reg_461_pp0_iter10_reg;
                isyBx_e_reg_461_pp0_iter1_reg <= isyBx_e_reg_461;
                isyBx_e_reg_461_pp0_iter2_reg <= isyBx_e_reg_461_pp0_iter1_reg;
                isyBx_e_reg_461_pp0_iter3_reg <= isyBx_e_reg_461_pp0_iter2_reg;
                isyBx_e_reg_461_pp0_iter4_reg <= isyBx_e_reg_461_pp0_iter3_reg;
                isyBx_e_reg_461_pp0_iter5_reg <= isyBx_e_reg_461_pp0_iter4_reg;
                isyBx_e_reg_461_pp0_iter6_reg <= isyBx_e_reg_461_pp0_iter5_reg;
                isyBx_e_reg_461_pp0_iter7_reg <= isyBx_e_reg_461_pp0_iter6_reg;
                isyBx_e_reg_461_pp0_iter8_reg <= isyBx_e_reg_461_pp0_iter7_reg;
                isyBx_e_reg_461_pp0_iter9_reg <= isyBx_e_reg_461_pp0_iter8_reg;
                n_reg_473 <= n_fu_187_p2;
                or_ln164_reg_465 <= or_ln164_fu_159_p2;
                or_ln164_reg_465_pp0_iter10_reg <= or_ln164_reg_465_pp0_iter9_reg;
                or_ln164_reg_465_pp0_iter11_reg <= or_ln164_reg_465_pp0_iter10_reg;
                or_ln164_reg_465_pp0_iter1_reg <= or_ln164_reg_465;
                or_ln164_reg_465_pp0_iter2_reg <= or_ln164_reg_465_pp0_iter1_reg;
                or_ln164_reg_465_pp0_iter3_reg <= or_ln164_reg_465_pp0_iter2_reg;
                or_ln164_reg_465_pp0_iter4_reg <= or_ln164_reg_465_pp0_iter3_reg;
                or_ln164_reg_465_pp0_iter5_reg <= or_ln164_reg_465_pp0_iter4_reg;
                or_ln164_reg_465_pp0_iter6_reg <= or_ln164_reg_465_pp0_iter5_reg;
                or_ln164_reg_465_pp0_iter7_reg <= or_ln164_reg_465_pp0_iter6_reg;
                or_ln164_reg_465_pp0_iter8_reg <= or_ln164_reg_465_pp0_iter7_reg;
                or_ln164_reg_465_pp0_iter9_reg <= or_ln164_reg_465_pp0_iter8_reg;
                or_ln168_reg_469 <= or_ln168_fu_171_p2;
                or_ln168_reg_469_pp0_iter10_reg <= or_ln168_reg_469_pp0_iter9_reg;
                or_ln168_reg_469_pp0_iter11_reg <= or_ln168_reg_469_pp0_iter10_reg;
                or_ln168_reg_469_pp0_iter1_reg <= or_ln168_reg_469;
                or_ln168_reg_469_pp0_iter2_reg <= or_ln168_reg_469_pp0_iter1_reg;
                or_ln168_reg_469_pp0_iter3_reg <= or_ln168_reg_469_pp0_iter2_reg;
                or_ln168_reg_469_pp0_iter4_reg <= or_ln168_reg_469_pp0_iter3_reg;
                or_ln168_reg_469_pp0_iter5_reg <= or_ln168_reg_469_pp0_iter4_reg;
                or_ln168_reg_469_pp0_iter6_reg <= or_ln168_reg_469_pp0_iter5_reg;
                or_ln168_reg_469_pp0_iter7_reg <= or_ln168_reg_469_pp0_iter6_reg;
                or_ln168_reg_469_pp0_iter8_reg <= or_ln168_reg_469_pp0_iter7_reg;
                or_ln168_reg_469_pp0_iter9_reg <= or_ln168_reg_469_pp0_iter8_reg;
                res_reg_493 <= grp_mod_rcp_mult_24_36_8_s_fu_97_ap_return;
                ret_5_reg_444 <= ret_5_fu_117_p1;
                ret_5_reg_444_pp0_iter10_reg <= ret_5_reg_444_pp0_iter9_reg;
                ret_5_reg_444_pp0_iter11_reg <= ret_5_reg_444_pp0_iter10_reg;
                ret_5_reg_444_pp0_iter1_reg <= ret_5_reg_444;
                ret_5_reg_444_pp0_iter2_reg <= ret_5_reg_444_pp0_iter1_reg;
                ret_5_reg_444_pp0_iter3_reg <= ret_5_reg_444_pp0_iter2_reg;
                ret_5_reg_444_pp0_iter4_reg <= ret_5_reg_444_pp0_iter3_reg;
                ret_5_reg_444_pp0_iter5_reg <= ret_5_reg_444_pp0_iter4_reg;
                ret_5_reg_444_pp0_iter6_reg <= ret_5_reg_444_pp0_iter5_reg;
                ret_5_reg_444_pp0_iter7_reg <= ret_5_reg_444_pp0_iter6_reg;
                ret_5_reg_444_pp0_iter8_reg <= ret_5_reg_444_pp0_iter7_reg;
                ret_5_reg_444_pp0_iter9_reg <= ret_5_reg_444_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= bitcast_ln327_fu_440_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_int_reg <= x;
            end if;
        end if;
    end process;
    add_ln212_fu_275_p2 <= std_logic_vector(unsigned(tmp_133_fu_257_p3) + unsigned(ap_const_lv32_FFFFFFFF));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp32 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_276_assign_proc : process(isF_e_x_reg_457_pp0_iter10_reg, isyBx_e_reg_461_pp0_iter10_reg, or_ln164_reg_465_pp0_iter10_reg)
    begin
                ap_condition_276 <= ((or_ln164_reg_465_pp0_iter10_reg = ap_const_lv1_0) and (isyBx_e_reg_461_pp0_iter10_reg = ap_const_lv1_0) and (isF_e_x_reg_457_pp0_iter10_reg = ap_const_lv1_0));
    end process;


    ap_condition_279_assign_proc : process(isF_e_x_reg_457_pp0_iter10_reg, isyBx_e_reg_461_pp0_iter10_reg, or_ln164_reg_465_pp0_iter10_reg, or_ln168_reg_469_pp0_iter10_reg)
    begin
                ap_condition_279 <= ((or_ln164_reg_465_pp0_iter10_reg = ap_const_lv1_1) and (isyBx_e_reg_461_pp0_iter10_reg = ap_const_lv1_0) and (isF_e_x_reg_457_pp0_iter10_reg = ap_const_lv1_0) and (or_ln168_reg_469_pp0_iter10_reg = ap_const_lv1_0));
    end process;


    ap_condition_288_assign_proc : process(isF_e_x_reg_457_pp0_iter11_reg, isyBx_e_reg_461_pp0_iter11_reg, or_ln164_reg_465_pp0_iter11_reg, or_ln168_reg_469_pp0_iter11_reg)
    begin
                ap_condition_288 <= ((or_ln164_reg_465_pp0_iter11_reg = ap_const_lv1_1) and (isyBx_e_reg_461_pp0_iter11_reg = ap_const_lv1_0) and (isF_e_x_reg_457_pp0_iter11_reg = ap_const_lv1_0) and (or_ln168_reg_469_pp0_iter11_reg = ap_const_lv1_1));
    end process;

    ap_mx_2_1_fu_316_p1 <= select_ln212_fu_308_p3(25 - 1 downto 0);

    ap_phi_mux_retval_1_in_phi_fu_83_p12_assign_proc : process(icmp_ln206_reg_499, ap_phi_reg_pp0_iter12_retval_1_in_reg_80, t_8_fu_431_p3, t_9_fu_420_p4, ap_condition_288)
    begin
        if ((ap_const_boolean_1 = ap_condition_288)) then
            if ((icmp_ln206_reg_499 = ap_const_lv1_0)) then 
                ap_phi_mux_retval_1_in_phi_fu_83_p12 <= t_9_fu_420_p4;
            elsif ((icmp_ln206_reg_499 = ap_const_lv1_1)) then 
                ap_phi_mux_retval_1_in_phi_fu_83_p12 <= t_8_fu_431_p3;
            else 
                ap_phi_mux_retval_1_in_phi_fu_83_p12 <= ap_phi_reg_pp0_iter12_retval_1_in_reg_80;
            end if;
        else 
            ap_phi_mux_retval_1_in_phi_fu_83_p12 <= ap_phi_reg_pp0_iter12_retval_1_in_reg_80;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_retval_1_in_reg_80 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op32_call_state2_assign_proc : process(isF_e_x_reg_457, isyBx_e_reg_461, or_ln164_reg_465, or_ln168_reg_469)
    begin
                ap_predicate_op32_call_state2 <= ((or_ln168_reg_469 = ap_const_lv1_1) and (or_ln164_reg_465 = ap_const_lv1_1) and (isyBx_e_reg_461 = ap_const_lv1_0) and (isF_e_x_reg_457 = ap_const_lv1_0));
    end process;


    ap_return_assign_proc : process(bitcast_ln327_fu_440_p1, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= bitcast_ln327_fu_440_p1;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bitcast_ln327_fu_440_p1 <= ap_phi_mux_retval_1_in_phi_fu_83_p12;
    empty_81_fu_396_p1 <= shl_ln218_fu_368_p2(23 - 1 downto 0);
    empty_82_fu_400_p1 <= lshr_ln218_fu_378_p2(23 - 1 downto 0);
    empty_83_fu_404_p3 <= 
        empty_81_fu_396_p1 when (tmp_156_fu_346_p3(0) = '1') else 
        empty_82_fu_400_p1;
    empty_fu_392_p1 <= select_ln212_fu_308_p3(23 - 1 downto 0);
    fz_exp_1_fu_330_p2 <= std_logic_vector(unsigned(trunc_ln214_fu_326_p1) + unsigned(ap_const_lv8_7F));
    fz_exp_2_fu_384_p3 <= 
        fz_exp_1_fu_330_p2 when (icmp_ln213_fu_320_p2(0) = '1') else 
        ap_const_lv8_0;
    fz_exp_cast_fu_177_p4 <= ret_5_fu_117_p1(29 downto 23);
    fz_exp_fu_121_p4 <= ret_5_fu_117_p1(30 downto 23);
    fz_sig_1_fu_412_p3 <= 
        empty_fu_392_p1 when (icmp_ln213_fu_320_p2(0) = '1') else 
        empty_83_fu_404_p3;
    fz_sig_fu_131_p1 <= ret_5_fu_117_p1(23 - 1 downto 0);
    grp_fu_103_p3 <= ret_5_reg_444_pp0_iter10_reg(31 downto 31);
    grp_fu_110_p3 <= ret_5_reg_444_pp0_iter11_reg(31 downto 31);

    grp_mod_rcp_mult_24_36_8_s_fu_97_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp32, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp32))) then 
            grp_mod_rcp_mult_24_36_8_s_fu_97_ap_ce <= ap_const_logic_1;
        else 
            grp_mod_rcp_mult_24_36_8_s_fu_97_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_mod_rcp_mult_24_36_8_s_fu_97_r_sh <= (ap_const_lv1_1 & fz_sig_reg_451);
    icmp_ln164_1_fu_153_p2 <= "1" when (unsigned(fz_sig_fu_131_p1) > unsigned(ap_const_lv23_9BFFF)) else "0";
    icmp_ln164_fu_147_p2 <= "0" when (fz_exp_fu_121_p4 = ap_const_lv8_89) else "1";
    icmp_ln168_fu_165_p2 <= "0" when (fz_sig_fu_131_p1 = ap_const_lv23_9C000) else "1";
    icmp_ln206_fu_218_p2 <= "1" when (grp_mod_rcp_mult_24_36_8_s_fu_97_ap_return = ap_const_lv24_0) else "0";
    icmp_ln212_fu_281_p2 <= "0" when (tmp_133_fu_257_p3 = ap_const_lv32_0) else "1";
    icmp_ln213_fu_320_p2 <= "1" when (signed(iy_fu_269_p2) > signed(ap_const_lv9_181)) else "0";
    isF_e_x_fu_135_p2 <= "1" when (fz_exp_fu_121_p4 = ap_const_lv8_FF) else "0";
    isyBx_e_fu_141_p2 <= "1" when (unsigned(fz_exp_fu_121_p4) < unsigned(ap_const_lv8_89)) else "0";
    iy_fu_269_p2 <= std_logic_vector(unsigned(ap_const_lv9_B) - unsigned(trunc_ln211_fu_265_p1));
    lshr_ln212_fu_302_p2 <= std_logic_vector(shift_right(unsigned(zext_ln212_fu_287_p1),to_integer(unsigned('0' & sub_ln212_fu_296_p2(31-1 downto 0)))));
    lshr_ln218_fu_378_p2 <= std_logic_vector(shift_right(unsigned(zext_ln218_fu_354_p1),to_integer(unsigned('0' & zext_ln218_2_fu_374_p1(31-1 downto 0)))));
    n_1_fu_340_p2 <= std_logic_vector(signed(ap_const_lv10_382) - signed(sext_ln217_fu_336_p1));
    n_fu_187_p2 <= std_logic_vector(unsigned(fz_exp_cast_fu_177_p4) + unsigned(ap_const_lv7_77));
    or_ln164_fu_159_p2 <= (icmp_ln164_fu_147_p2 or icmp_ln164_1_fu_153_p2);
    or_ln168_fu_171_p2 <= (icmp_ln168_fu_165_p2 or icmp_ln164_fu_147_p2);
    ret_5_fu_117_p1 <= x_int_reg;
    select_ln212_fu_308_p3 <= 
        shl_ln212_fu_290_p2 when (icmp_ln212_fu_281_p2(0) = '1') else 
        lshr_ln212_fu_302_p2;
        sext_ln211_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_132_fu_245_p3),32));

        sext_ln217_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(iy_fu_269_p2),10));

    shl_ln212_fu_290_p2 <= std_logic_vector(shift_left(unsigned(zext_ln212_fu_287_p1),to_integer(unsigned('0' & add_ln212_fu_275_p2(31-1 downto 0)))));
    shl_ln218_fu_368_p2 <= std_logic_vector(shift_left(unsigned(zext_ln218_fu_354_p1),to_integer(unsigned('0' & zext_ln218_1_fu_364_p1(31-1 downto 0)))));
    sub_ln212_fu_296_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) - unsigned(tmp_133_fu_257_p3));
    sub_ln218_fu_358_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(n_1_fu_340_p2));
    t_6_fu_201_p4 <= ((grp_fu_103_p3 & ap_const_lv8_89) & fz_sig_reg_451_pp0_iter10_reg);
    t_7_fu_210_p3 <= (grp_fu_103_p3 & ap_const_lv31_0);
    t_8_fu_431_p3 <= (grp_fu_110_p3 & ap_const_lv31_0);
    t_9_fu_420_p4 <= ((grp_fu_110_p3 & fz_exp_2_fu_384_p3) & fz_sig_1_fu_412_p3);
    t_fu_224_p3 <= (grp_fu_103_p3 & ap_const_lv31_7FFFFFFF);
    tmp_132_fu_245_p3 <= (ap_const_lv1_1 & tmp_s_fu_235_p4);
    
    tmp_133_fu_257_p3_proc : process(sext_ln211_fu_253_p1)
    begin
        tmp_133_fu_257_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if sext_ln211_fu_253_p1(i) = '1' then
                tmp_133_fu_257_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    tmp_156_fu_346_p3 <= n_1_fu_340_p2(9 downto 9);
    
    tmp_s_fu_235_p4_proc : process(zext_ln204_fu_232_p1)
    variable vlo_cpy : STD_LOGIC_VECTOR(25+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(25+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(25 - 1 downto 0);
    variable tmp_s_fu_235_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(25 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(25 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(25 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_18(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := zext_ln204_fu_232_p1;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(25-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(25-1-unsigned(ap_const_lv32_18(5-1 downto 0)));
            for tmp_s_fu_235_p4_i in 0 to 25-1 loop
                v0_cpy(tmp_s_fu_235_p4_i) := zext_ln204_fu_232_p1(25-1-tmp_s_fu_235_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(25-1 downto 0)))));
        res_mask := res_mask(25-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_s_fu_235_p4 <= resvalue(25-1 downto 0);
    end process;

    trunc_ln211_fu_265_p1 <= tmp_133_fu_257_p3(9 - 1 downto 0);
    trunc_ln214_fu_326_p1 <= iy_fu_269_p2(8 - 1 downto 0);
    zext_ln204_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_reg_493),25));
    zext_ln212_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_reg_493),32));
    zext_ln218_1_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln218_fu_358_p2),32));
    zext_ln218_2_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_1_fu_340_p2),32));
    zext_ln218_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_mx_2_1_fu_316_p1),32));
end behav;
