// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pedal_top_tremolo (
        ap_clk,
        ap_rst,
        data,
        count,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] data;
input  [31:0] count;
output  [31:0] ap_return;
input   ap_ce;

reg[31:0] ap_return;

wire   [3:0] ref_4oPi_table_100_address0;
wire   [99:0] ref_4oPi_table_100_q0;
wire   [7:0] second_order_float_sin_cos_K0_address0;
wire   [29:0] second_order_float_sin_cos_K0_q0;
wire   [7:0] second_order_float_sin_cos_K1_address0;
wire  signed [22:0] second_order_float_sin_cos_K1_q0;
wire   [7:0] second_order_float_sin_cos_K2_address0;
wire  signed [14:0] second_order_float_sin_cos_K2_q0;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] select_ln40_1_fu_519_p3;
reg   [31:0] select_ln40_1_reg_2503;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter1_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter2_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter3_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter4_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter5_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter6_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter7_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter8_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter9_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter10_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter11_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter12_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter13_reg;
reg   [31:0] select_ln40_1_reg_2503_pp0_iter14_reg;
reg  signed [31:0] select_ln40_1_reg_2503_pp0_iter15_reg;
wire   [31:0] grp_fu_402_p1;
reg   [31:0] conv1_reg_2508;
wire   [31:0] grp_fu_397_p2;
reg   [31:0] div_reg_2513;
reg   [0:0] din_sign_reg_2518;
wire   [7:0] din_exp_fu_539_p4;
reg   [7:0] din_exp_reg_2524;
wire   [22:0] din_sig_fu_549_p1;
reg   [22:0] din_sig_reg_2531;
wire   [0:0] closepath_fu_553_p2;
reg   [0:0] closepath_reg_2537;
wire   [3:0] trunc_ln379_fu_588_p1;
reg   [3:0] trunc_ln379_reg_2548;
reg   [28:0] Mx_reg_2553;
reg   [28:0] Mx_reg_2553_pp0_iter12_reg;
wire   [7:0] Ex_1_fu_757_p2;
reg   [7:0] Ex_1_reg_2559;
reg   [7:0] Ex_1_reg_2559_pp0_iter12_reg;
reg   [0:0] tmp_2_reg_2566;
wire   [0:0] cos_basis_fu_771_p19;
reg   [0:0] cos_basis_reg_2572;
reg   [0:0] cos_basis_reg_2572_pp0_iter12_reg;
wire   [0:0] and_ln271_fu_980_p2;
reg   [0:0] and_ln271_reg_2579;
reg   [0:0] and_ln271_reg_2579_pp0_iter12_reg;
reg   [0:0] and_ln271_reg_2579_pp0_iter13_reg;
wire   [0:0] icmp_ln282_fu_986_p2;
reg   [0:0] icmp_ln282_reg_2585;
reg   [0:0] icmp_ln282_reg_2585_pp0_iter12_reg;
reg   [0:0] icmp_ln282_reg_2585_pp0_iter13_reg;
wire   [0:0] results_sign_2_fu_1003_p3;
reg   [0:0] results_sign_2_reg_2592;
reg   [0:0] results_sign_2_reg_2592_pp0_iter12_reg;
reg   [0:0] results_sign_2_reg_2592_pp0_iter13_reg;
wire   [21:0] B_fu_1047_p1;
reg   [21:0] B_reg_2597;
reg   [14:0] B_squared_reg_2602;
wire   [31:0] shl_ln291_fu_1299_p2;
reg   [31:0] shl_ln291_reg_2622;
wire   [0:0] icmp_ln292_fu_1309_p2;
reg   [0:0] icmp_ln292_reg_2627;
wire   [31:0] shl_ln291_1_fu_1325_p2;
reg   [31:0] shl_ln291_1_reg_2632;
wire   [0:0] or_ln282_fu_1386_p2;
reg   [0:0] or_ln282_reg_2637;
wire   [7:0] results_exp_1_fu_1399_p3;
reg   [7:0] results_exp_1_reg_2642;
wire   [62:0] trunc_ln37_fu_1469_p1;
reg   [62:0] trunc_ln37_reg_2647;
reg   [0:0] tmp_4_reg_2652;
reg   [10:0] tmp_1_reg_2662;
wire   [51:0] trunc_ln37_1_fu_1491_p1;
reg   [51:0] trunc_ln37_1_reg_2667;
wire   [32:0] add_ln39_fu_2290_p2;
reg   [32:0] add_ln39_reg_2672;
wire   [63:0] zext_ln378_fu_583_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln28_fu_1104_p1;
reg    ref_4oPi_table_100_ce0_local;
reg    second_order_float_sin_cos_K0_ce0_local;
reg    second_order_float_sin_cos_K1_ce0_local;
reg    second_order_float_sin_cos_K2_ce0_local;
wire   [31:0] pf_fu_406_p0;
wire   [21:0] mul_ln29_fu_409_p1;
wire   [28:0] mul_ln32_fu_413_p1;
wire  signed [79:0] h_fu_421_p0;
wire   [23:0] h_fu_421_p1;
wire   [15:0] tmp_20_fu_447_p4;
wire   [0:0] tmp_19_fu_439_p3;
wire   [0:0] icmp_ln40_fu_457_p2;
wire   [0:0] tmp_18_fu_425_p3;
wire   [0:0] or_ln40_fu_463_p2;
wire   [0:0] xor_ln40_fu_469_p2;
wire   [0:0] icmp_ln40_1_fu_487_p2;
wire   [0:0] xor_ln40_1_fu_481_p2;
wire   [0:0] or_ln40_1_fu_493_p2;
wire   [0:0] and_ln40_fu_475_p2;
wire   [0:0] and_ln40_1_fu_499_p2;
wire   [0:0] or_ln40_2_fu_513_p2;
wire   [31:0] select_ln40_fu_505_p3;
wire   [31:0] shl_ln40_fu_433_p2;
wire   [31:0] grp_fu_392_p2;
wire   [31:0] data_1_fu_527_p1;
wire   [7:0] add_ln376_fu_559_p2;
wire   [7:0] addr_fu_565_p3;
wire   [3:0] lshr_ln_fu_573_p4;
wire   [7:0] Ex_fu_592_p2;
wire   [99:0] zext_ln379_fu_611_p1;
wire   [99:0] shl_ln379_fu_614_p2;
wire   [23:0] X_fu_604_p3;
wire   [79:0] h_fu_421_p2;
wire   [2:0] k_fu_646_p4;
wire   [2:0] k_1_fu_656_p3;
wire   [57:0] Mx_bits_fu_636_p4;
wire   [0:0] trunc_ln491_fu_663_p1;
wire   [57:0] Mx_bits_1_fu_667_p2;
wire   [57:0] Mx_bits_2_fu_673_p3;
wire   [28:0] tmp_136_i3_fu_681_p4;
wire   [29:0] t_fu_691_p3;
reg   [29:0] tmp_137_i_fu_699_p4;
wire   [30:0] tmp_138_i_fu_709_p3;
wire  signed [31:0] sext_ln75_fu_717_p1;
reg   [31:0] tmp_139_i_fu_721_p3;
wire   [5:0] Mx_zeros_fu_729_p1;
wire   [57:0] zext_ln504_fu_733_p1;
wire   [57:0] shl_ln504_fu_737_p2;
wire   [7:0] select_ln453_fu_597_p3;
wire   [7:0] zext_ln505_fu_753_p1;
wire   [0:0] cos_basis_fu_771_p17;
wire   [0:0] tmp_145_i_fu_818_p33;
wire   [3:0] index_fu_811_p3;
wire   [0:0] tmp_146_i_fu_890_p33;
wire   [0:0] tmp_145_i_fu_818_p35;
wire   [0:0] tmp_146_i_fu_890_p35;
wire   [0:0] icmp_ln271_fu_970_p2;
wire   [0:0] icmp_ln271_1_fu_975_p2;
wire   [0:0] results_sign_fu_962_p3;
wire   [0:0] xor_ln282_fu_991_p2;
wire   [0:0] results_sign_1_fu_997_p2;
wire   [7:0] sub_ln506_fu_1010_p2;
wire   [7:0] select_ln506_fu_1015_p3;
wire   [31:0] zext_ln506_1_fu_1025_p1;
wire   [31:0] zext_ln506_fu_1021_p1;
wire   [31:0] lshr_ln506_fu_1028_p2;
wire   [31:0] shl_ln506_fu_1034_p2;
wire   [31:0] select_ln506_1_fu_1040_p3;
wire   [14:0] B_trunc_fu_1061_p4;
wire   [14:0] mul_ln23_fu_1075_p0;
wire   [29:0] zext_ln23_fu_1071_p1;
wire   [14:0] mul_ln23_fu_1075_p1;
wire   [29:0] mul_ln23_fu_1075_p2;
wire   [0:0] sin_basis_fu_1091_p2;
wire   [6:0] tmp_140_i_fu_1051_p4;
wire   [7:0] A_fu_1096_p3;
wire   [44:0] mul_ln29_fu_409_p2;
wire   [14:0] mul_ln30_fu_1159_p0;
wire   [29:0] mul_ln30_fu_1159_p2;
wire   [28:0] t1_fu_1126_p4;
wire   [21:0] trunc_ln_fu_1145_p4;
wire  signed [29:0] sext_ln32_fu_1175_p1;
wire  signed [29:0] sext_ln32_1_fu_1179_p1;
wire   [13:0] trunc_ln1_fu_1165_p4;
wire   [29:0] add_ln32_fu_1183_p2;
wire  signed [29:0] sext_ln32_2_fu_1189_p1;
wire  signed [29:0] add_ln32_1_fu_1193_p2;
wire   [28:0] Mx_1_fu_1111_p3;
wire   [57:0] mul_ln32_fu_413_p2;
wire   [7:0] Ex_2_fu_1117_p3;
wire   [15:0] tmp_141_i_fu_1223_p4;
wire   [12:0] tmp_142_i_fu_1241_p4;
wire   [31:0] out_bits_fu_1233_p3;
reg   [31:0] tmp_143_i_fu_1259_p4;
wire   [31:0] out_bits_2_fu_1251_p3;
reg   [31:0] tmp_144_i_fu_1277_p4;
wire   [28:0] result_fu_1209_p4;
wire   [31:0] zext_ln291_fu_1295_p1;
reg   [31:0] c_fu_1269_p3;
reg   [31:0] c_1_fu_1287_p3;
wire   [27:0] in_shift_1_fu_1305_p1;
wire   [31:0] zext_ln291_1_fu_1321_p1;
wire   [31:0] shift_1_fu_1315_p2;
wire  signed [8:0] sext_ln252_fu_1219_p1;
wire   [8:0] add_ln300_fu_1339_p2;
wire  signed [31:0] sext_ln300_fu_1345_p1;
wire   [31:0] shift_2_fu_1331_p3;
wire   [31:0] newexp_fu_1349_p2;
wire   [0:0] tmp_3_fu_1355_p3;
wire   [0:0] icmp_ln306_fu_1363_p2;
wire   [0:0] or_ln306_fu_1369_p2;
wire   [7:0] select_ln282_fu_1379_p3;
wire   [7:0] empty_fu_1375_p1;
wire   [7:0] results_exp_fu_1391_p3;
wire   [22:0] tmp_fu_1406_p4;
wire   [22:0] tmp_s_fu_1415_p4;
wire   [22:0] select_ln282_2_fu_1431_p3;
wire   [22:0] empty_75_fu_1424_p3;
wire   [22:0] results_sig_fu_1438_p3;
wire   [22:0] results_sig_1_fu_1445_p3;
wire   [31:0] t_2_fu_1452_p4;
wire   [63:0] pf_fu_406_p1;
wire   [63:0] bitcast_ln716_fu_1465_p1;
wire   [11:0] zext_ln37_fu_1495_p1;
wire   [52:0] zext_ln37_1_cast_fu_1504_p3;
wire   [53:0] zext_ln37_1_fu_1511_p1;
wire   [53:0] sub_ln37_fu_1515_p2;
wire   [11:0] sub_ln37_1_fu_1533_p2;
wire   [11:0] add_ln37_1_fu_1549_p2;
wire   [10:0] trunc_ln37_2_fu_1539_p1;
wire   [0:0] icmp_ln37_1_fu_1543_p2;
wire   [10:0] trunc_ln37_3_fu_1555_p1;
wire   [10:0] sub_ln37_2_fu_1559_p2;
wire   [10:0] select_ln37_1_fu_1565_p3;
wire   [53:0] select_ln37_fu_1521_p3;
wire   [53:0] zext_ln37_2_fu_1600_p1;
wire   [53:0] ashr_ln37_fu_1604_p2;
wire   [0:0] icmp_ln37_3_fu_1587_p2;
wire   [31:0] trunc_ln37_5_fu_1610_p1;
wire   [31:0] select_ln37_3_fu_1593_p3;
wire   [5:0] tmp_5_fu_1628_p4;
wire   [11:0] add_ln37_2_fu_1644_p2;
wire  signed [31:0] sext_ln37_fu_1650_p1;
wire   [31:0] trunc_ln37_4_fu_1583_p1;
wire   [31:0] zext_ln37_4_fu_1573_p1;
wire   [0:0] icmp_ln37_4_fu_1622_p2;
wire   [0:0] tmp_6_fu_1654_p3;
wire   [11:0] add_ln37_3_fu_1681_p2;
wire   [5:0] trunc_ln37_6_fu_1693_p1;
wire   [0:0] icmp_ln37_7_fu_1687_p2;
wire   [5:0] sub_ln37_3_fu_1697_p2;
wire   [5:0] select_ln37_8_fu_1703_p3;
wire   [53:0] zext_ln37_5_fu_1711_p1;
wire   [53:0] lshr_ln37_2_fu_1715_p2;
wire   [53:0] and_ln37_17_fu_1721_p2;
wire   [0:0] icmp_ln37_6_fu_1675_p2;
wire   [0:0] icmp_ln37_8_fu_1727_p2;
wire   [31:0] select_ln37_2_fu_1614_p3;
wire   [0:0] trunc_ln37_7_fu_1747_p1;
wire   [0:0] cond85_i_fu_1733_p2;
wire   [0:0] or_ln37_fu_1751_p2;
wire   [0:0] cond63_i_fu_1668_p3;
wire   [0:0] and_ln37_fu_1757_p2;
wire   [31:0] zext_ln37_3_fu_1763_p1;
wire   [31:0] add_ln37_4_fu_1767_p2;
wire   [0:0] tmp_8_fu_1773_p3;
wire   [0:0] icmp_ln37_2_fu_1577_p2;
wire   [0:0] xor_ln37_2_fu_1787_p2;
wire   [7:0] tmp_9_fu_1799_p4;
wire   [0:0] icmp_ln37_11_fu_1809_p2;
wire   [0:0] icmp_ln37_9_fu_1638_p2;
wire   [0:0] and_ln37_1_fu_1793_p2;
wire   [0:0] and_ln37_11_fu_1815_p2;
wire   [31:0] ref_tmp_i_i_fu_1831_p6;
wire   [31:0] ref_tmp_i_i_fu_1831_p9;
wire   [2:0] ref_tmp_i_i_fu_1831_p10;
wire   [0:0] tmp_7_fu_1739_p3;
wire   [0:0] and_ln37_12_fu_1855_p2;
wire   [0:0] xor_ln37_fu_1781_p2;
wire   [11:0] select_ln37_9_fu_1867_p3;
wire   [11:0] add_ln37_fu_1498_p2;
wire   [11:0] add_ln37_5_fu_1875_p2;
wire   [7:0] tmp_10_fu_1881_p4;
wire  signed [11:0] add_ln37_6_fu_1897_p2;
wire   [31:0] ref_tmp_i_i_fu_1831_p11;
wire   [0:0] tmp_12_fu_1927_p3;
wire  signed [31:0] sext_ln37_1_fu_1903_p1;
wire   [0:0] icmp_ln37_12_fu_1941_p2;
wire   [0:0] tobool130_i_fu_1947_p3;
wire  signed [11:0] add_ln37_7_fu_1907_p2;
wire   [0:0] tmp_11_fu_1913_p3;
wire  signed [31:0] sext_ln37_2_fu_1978_p1;
wire   [53:0] zext_ln37_6_fu_1982_p1;
wire   [53:0] lshr_ln37_fu_1986_p2;
wire   [53:0] lshr_ln37_1_fu_1992_p2;
wire   [0:0] tmp_13_fu_2004_p3;
wire   [0:0] icmp_ln37_14_fu_1967_p2;
wire   [0:0] icmp_ln37_15_fu_1998_p2;
wire   [0:0] xor_ln37_9_fu_2012_p2;
wire   [0:0] icmp_ln37_13_fu_1961_p2;
wire   [0:0] xor_ln37_8_fu_1935_p2;
wire   [0:0] Range2_all_ones_1_i_fu_2018_p3;
wire   [0:0] lD_0_i_fu_1955_p2;
wire   [0:0] icmp_ln37_17_fu_2044_p2;
wire   [0:0] xor_ln37_1_fu_2038_p2;
wire   [0:0] icmp_ln37_18_fu_2056_p2;
wire   [0:0] and_ln37_3_fu_2026_p2;
wire   [0:0] and_ln37_4_fu_2032_p2;
wire   [0:0] select_ln37_6_fu_2062_p3;
wire   [0:0] and_ln37_5_fu_2050_p2;
wire   [0:0] select_ln37_7_fu_2070_p3;
wire   [0:0] carry_1_i_fu_1861_p2;
wire   [0:0] Range1_all_ones_2_i_fu_2078_p3;
wire   [0:0] Range1_all_zeros_2_i_fu_2086_p3;
wire   [0:0] or_ln37_1_fu_2102_p2;
wire   [0:0] and_ln37_6_fu_2108_p2;
wire   [0:0] and_ln37_7_fu_2122_p2;
wire   [0:0] icmp_ln37_10_fu_1921_p2;
wire   [0:0] cond189_i_fu_2114_p3;
wire   [0:0] not_icmp_ln37_1062_fu_2134_p2;
wire   [0:0] and_ln37_13_fu_2146_p2;
wire   [0:0] neg_src_0_i_fu_2159_p2;
wire   [0:0] neg_src_0_i_fu_2159_p4;
wire   [0:0] neg_src_0_i_fu_2159_p7;
wire   [1:0] neg_src_0_i_fu_2159_p8;
wire   [0:0] select_ln37_4_fu_2094_p3;
wire   [0:0] xor_ln37_4_fu_2179_p2;
wire   [0:0] and_ln37_14_fu_2185_p2;
wire   [0:0] or_ln37_2_fu_2191_p2;
wire   [0:0] xor_ln37_5_fu_2197_p2;
wire   [0:0] deleted_ones_0_i_fu_2140_p2;
wire   [0:0] and_ln37_9_fu_2208_p2;
wire   [0:0] neg_src_0_i_fu_2159_p9;
wire   [0:0] xor_ln37_6_fu_2214_p2;
wire   [0:0] and_ln37_10_fu_2220_p2;
wire   [0:0] and_ln37_8_fu_2202_p2;
wire   [0:0] icmp_ln37_fu_1528_p2;
wire   [0:0] or_ln37_3_fu_2226_p2;
wire   [0:0] xor_ln37_7_fu_2240_p2;
wire   [0:0] and_ln37_15_fu_2246_p2;
wire   [0:0] icmp_ln37_16_fu_1891_p2;
wire   [0:0] and_ln37_16_fu_2252_p2;
wire   [31:0] lfo_fu_2266_p4;
wire   [31:0] lfo_fu_2266_p7;
wire   [1:0] lfo_fu_2266_p8;
wire   [31:0] lfo_fu_2266_p9;
wire  signed [32:0] sext_ln39_fu_2286_p1;
wire   [62:0] shl_ln_fu_2296_p3;
wire   [62:0] add_ln39_1_fu_2303_p2;
wire   [30:0] mod_fu_2317_p4;
wire   [30:0] trunc_ln39_fu_2339_p1;
wire   [0:0] tmp_16_fu_2349_p3;
wire   [0:0] icmp_ln39_fu_2343_p2;
wire   [0:0] or_ln39_fu_2357_p2;
wire   [0:0] tmp_15_fu_2331_p3;
wire   [0:0] and_ln39_fu_2363_p2;
wire  signed [31:0] sext_ln39_1_fu_2327_p1;
wire   [31:0] zext_ln39_fu_2369_p1;
wire   [31:0] mod_1_fu_2373_p2;
wire   [0:0] tmp_14_fu_2309_p3;
wire   [0:0] tmp_17_fu_2379_p3;
wire   [0:0] xor_ln39_fu_2387_p2;
wire   [0:0] or_ln39_2_fu_2393_p2;
wire   [0:0] xor_ln39_1_fu_2399_p2;
wire   [0:0] xor_ln39_2_fu_2405_p2;
wire   [0:0] or_ln39_1_fu_2411_p2;
wire   [0:0] and_ln39_1_fu_2417_p2;
wire  signed [31:0] mod_2_fu_2423_p3;
wire  signed [62:0] mul_ln40_fu_417_p2;
wire   [30:0] tmp_21_fu_2444_p4;
wire  signed [63:0] sext_ln40_2_fu_2440_p1;
wire   [31:0] trunc_ln40_fu_2466_p1;
wire  signed [31:0] sext_ln40_3_fu_2454_p1;
wire   [0:0] icmp_ln40_2_fu_2470_p2;
wire   [31:0] add_ln40_fu_2476_p2;
wire   [0:0] tmp_22_fu_2458_p3;
wire   [31:0] select_ln40_2_fu_2482_p3;
reg    grp_fu_392_ce;
reg    grp_fu_397_ce;
reg    grp_fu_402_ce;
wire   [31:0] ref_tmp_i_0_fu_2490_p3;
reg    ap_ce_reg;
reg   [31:0] data_int_reg;
reg   [31:0] count_int_reg;
reg   [31:0] ap_return_int_reg;
wire   [79:0] h_fu_421_p10;
wire   [44:0] mul_ln29_fu_409_p10;
wire   [29:0] mul_ln30_fu_1159_p00;
wire   [57:0] mul_ln32_fu_413_p10;
wire   [2:0] cos_basis_fu_771_p1;
wire   [2:0] cos_basis_fu_771_p3;
wire   [2:0] cos_basis_fu_771_p5;
wire   [2:0] cos_basis_fu_771_p7;
wire  signed [2:0] cos_basis_fu_771_p9;
wire  signed [2:0] cos_basis_fu_771_p11;
wire  signed [2:0] cos_basis_fu_771_p13;
wire  signed [2:0] cos_basis_fu_771_p15;
wire   [3:0] tmp_145_i_fu_818_p1;
wire   [3:0] tmp_145_i_fu_818_p3;
wire   [3:0] tmp_145_i_fu_818_p5;
wire   [3:0] tmp_145_i_fu_818_p7;
wire   [3:0] tmp_145_i_fu_818_p9;
wire   [3:0] tmp_145_i_fu_818_p11;
wire   [3:0] tmp_145_i_fu_818_p13;
wire   [3:0] tmp_145_i_fu_818_p15;
wire  signed [3:0] tmp_145_i_fu_818_p17;
wire  signed [3:0] tmp_145_i_fu_818_p19;
wire  signed [3:0] tmp_145_i_fu_818_p21;
wire  signed [3:0] tmp_145_i_fu_818_p23;
wire  signed [3:0] tmp_145_i_fu_818_p25;
wire  signed [3:0] tmp_145_i_fu_818_p27;
wire  signed [3:0] tmp_145_i_fu_818_p29;
wire  signed [3:0] tmp_145_i_fu_818_p31;
wire   [3:0] tmp_146_i_fu_890_p1;
wire   [3:0] tmp_146_i_fu_890_p3;
wire   [3:0] tmp_146_i_fu_890_p5;
wire   [3:0] tmp_146_i_fu_890_p7;
wire   [3:0] tmp_146_i_fu_890_p9;
wire   [3:0] tmp_146_i_fu_890_p11;
wire   [3:0] tmp_146_i_fu_890_p13;
wire   [3:0] tmp_146_i_fu_890_p15;
wire  signed [3:0] tmp_146_i_fu_890_p17;
wire  signed [3:0] tmp_146_i_fu_890_p19;
wire  signed [3:0] tmp_146_i_fu_890_p21;
wire  signed [3:0] tmp_146_i_fu_890_p23;
wire  signed [3:0] tmp_146_i_fu_890_p25;
wire  signed [3:0] tmp_146_i_fu_890_p27;
wire  signed [3:0] tmp_146_i_fu_890_p29;
wire  signed [3:0] tmp_146_i_fu_890_p31;
wire  signed [2:0] ref_tmp_i_i_fu_1831_p1;
wire   [2:0] ref_tmp_i_i_fu_1831_p3;
wire   [2:0] ref_tmp_i_i_fu_1831_p5;
wire   [2:0] ref_tmp_i_i_fu_1831_p7;
wire  signed [1:0] neg_src_0_i_fu_2159_p1;
wire   [1:0] neg_src_0_i_fu_2159_p3;
wire   [1:0] neg_src_0_i_fu_2159_p5;
wire  signed [1:0] lfo_fu_2266_p1;
wire   [1:0] lfo_fu_2266_p3;
wire   [1:0] lfo_fu_2266_p5;

pedal_top_tremolo_ref_4oPi_table_100_ROM_1P_LUTRAM_1R #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_address0),
    .ce0(ref_4oPi_table_100_ce0_local),
    .q0(ref_4oPi_table_100_q0)
);

pedal_top_tremolo_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K0_address0),
    .ce0(second_order_float_sin_cos_K0_ce0_local),
    .q0(second_order_float_sin_cos_K0_q0)
);

pedal_top_tremolo_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K1_address0),
    .ce0(second_order_float_sin_cos_K1_ce0_local),
    .q0(second_order_float_sin_cos_K1_q0)
);

pedal_top_tremolo_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K2_address0),
    .ce0(second_order_float_sin_cos_K2_ce0_local),
    .q0(second_order_float_sin_cos_K2_q0)
);

pedal_top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(div_reg_2513),
    .din1(32'd1106990020),
    .ce(grp_fu_392_ce),
    .dout(grp_fu_392_p2)
);

pedal_top_fdiv_32ns_32ns_32_7_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_7_no_dsp_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv1_reg_2508),
    .din1(32'd1194083328),
    .ce(grp_fu_397_ce),
    .dout(grp_fu_397_p2)
);

pedal_top_sitofp_32ns_32_2_no_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_2_no_dsp_0_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(count_int_reg),
    .ce(grp_fu_402_ce),
    .dout(grp_fu_402_p1)
);

pedal_top_fpext_32ns_64_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_1_no_dsp_1_U52(
    .din0(pf_fu_406_p0),
    .dout(pf_fu_406_p1)
);

pedal_top_mul_23s_22ns_45_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 45 ))
mul_23s_22ns_45_1_0_U53(
    .din0(second_order_float_sin_cos_K1_q0),
    .din1(mul_ln29_fu_409_p1),
    .dout(mul_ln29_fu_409_p2)
);

pedal_top_mul_30s_29ns_58_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
mul_30s_29ns_58_1_0_U54(
    .din0(add_ln32_1_fu_1193_p2),
    .din1(mul_ln32_fu_413_p1),
    .dout(mul_ln32_fu_413_p2)
);

pedal_top_mul_32s_32s_63_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_32s_32s_63_1_0_U55(
    .din0(select_ln40_1_reg_2503_pp0_iter15_reg),
    .din1(mod_2_fu_2423_p3),
    .dout(mul_ln40_fu_417_p2)
);

pedal_top_mul_80s_24ns_80_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 80 ))
mul_80s_24ns_80_1_0_U56(
    .din0(h_fu_421_p0),
    .din1(h_fu_421_p1),
    .dout(h_fu_421_p2)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_17_3_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_0_U57(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .def(cos_basis_fu_771_p17),
    .sel(k_1_fu_656_p3),
    .dout(cos_basis_fu_771_p19)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_33_4_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_0_U58(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_145_i_fu_818_p33),
    .sel(index_fu_811_p3),
    .dout(tmp_145_i_fu_818_p35)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_33_4_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_0_U59(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_146_i_fu_890_p33),
    .sel(index_fu_811_p3),
    .dout(tmp_146_i_fu_890_p35)
);

pedal_top_mul_15ns_15ns_30_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15ns_30_1_0_U60(
    .din0(mul_ln23_fu_1075_p0),
    .din1(mul_ln23_fu_1075_p1),
    .dout(mul_ln23_fu_1075_p2)
);

pedal_top_mul_15ns_15s_30_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15s_30_1_0_U61(
    .din0(mul_ln30_fu_1159_p0),
    .din1(second_order_float_sin_cos_K2_q0),
    .dout(mul_ln30_fu_1159_p2)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_9_3_32_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_9_3_32_1_0_U62(
    .din0(trunc_ln37_4_fu_1583_p1),
    .din1(add_ln37_4_fu_1767_p2),
    .din2(ref_tmp_i_i_fu_1831_p6),
    .din3(32'd0),
    .def(ref_tmp_i_i_fu_1831_p9),
    .sel(ref_tmp_i_i_fu_1831_p10),
    .dout(ref_tmp_i_i_fu_1831_p11)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_7_2_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_0_U63(
    .din0(neg_src_0_i_fu_2159_p2),
    .din1(neg_src_0_i_fu_2159_p4),
    .din2(1'd0),
    .def(neg_src_0_i_fu_2159_p7),
    .sel(neg_src_0_i_fu_2159_p8),
    .dout(neg_src_0_i_fu_2159_p9)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_7_2_32_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_0_U64(
    .din0(32'd0),
    .din1(lfo_fu_2266_p4),
    .din2(ref_tmp_i_i_fu_1831_p11),
    .def(lfo_fu_2266_p7),
    .sel(lfo_fu_2266_p8),
    .dout(lfo_fu_2266_p9)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        B_reg_2597 <= B_fu_1047_p1;
        B_squared_reg_2602 <= {{mul_ln23_fu_1075_p2[29:15]}};
        Ex_1_reg_2559 <= Ex_1_fu_757_p2;
        Ex_1_reg_2559_pp0_iter12_reg <= Ex_1_reg_2559;
        Mx_reg_2553 <= {{shl_ln504_fu_737_p2[57:29]}};
        Mx_reg_2553_pp0_iter12_reg <= Mx_reg_2553;
        add_ln39_reg_2672 <= add_ln39_fu_2290_p2;
        and_ln271_reg_2579 <= and_ln271_fu_980_p2;
        and_ln271_reg_2579_pp0_iter12_reg <= and_ln271_reg_2579;
        and_ln271_reg_2579_pp0_iter13_reg <= and_ln271_reg_2579_pp0_iter12_reg;
        closepath_reg_2537 <= closepath_fu_553_p2;
        conv1_reg_2508 <= grp_fu_402_p1;
        cos_basis_reg_2572 <= cos_basis_fu_771_p19;
        cos_basis_reg_2572_pp0_iter12_reg <= cos_basis_reg_2572;
        din_exp_reg_2524 <= {{data_1_fu_527_p1[30:23]}};
        din_sig_reg_2531 <= din_sig_fu_549_p1;
        din_sign_reg_2518 <= data_1_fu_527_p1[32'd31];
        div_reg_2513 <= grp_fu_397_p2;
        icmp_ln282_reg_2585 <= icmp_ln282_fu_986_p2;
        icmp_ln282_reg_2585_pp0_iter12_reg <= icmp_ln282_reg_2585;
        icmp_ln282_reg_2585_pp0_iter13_reg <= icmp_ln282_reg_2585_pp0_iter12_reg;
        icmp_ln292_reg_2627 <= icmp_ln292_fu_1309_p2;
        or_ln282_reg_2637 <= or_ln282_fu_1386_p2;
        results_exp_1_reg_2642 <= results_exp_1_fu_1399_p3;
        results_sign_2_reg_2592 <= results_sign_2_fu_1003_p3;
        results_sign_2_reg_2592_pp0_iter12_reg <= results_sign_2_reg_2592;
        results_sign_2_reg_2592_pp0_iter13_reg <= results_sign_2_reg_2592_pp0_iter12_reg;
        select_ln40_1_reg_2503 <= select_ln40_1_fu_519_p3;
        select_ln40_1_reg_2503_pp0_iter10_reg <= select_ln40_1_reg_2503_pp0_iter9_reg;
        select_ln40_1_reg_2503_pp0_iter11_reg <= select_ln40_1_reg_2503_pp0_iter10_reg;
        select_ln40_1_reg_2503_pp0_iter12_reg <= select_ln40_1_reg_2503_pp0_iter11_reg;
        select_ln40_1_reg_2503_pp0_iter13_reg <= select_ln40_1_reg_2503_pp0_iter12_reg;
        select_ln40_1_reg_2503_pp0_iter14_reg <= select_ln40_1_reg_2503_pp0_iter13_reg;
        select_ln40_1_reg_2503_pp0_iter15_reg <= select_ln40_1_reg_2503_pp0_iter14_reg;
        select_ln40_1_reg_2503_pp0_iter1_reg <= select_ln40_1_reg_2503;
        select_ln40_1_reg_2503_pp0_iter2_reg <= select_ln40_1_reg_2503_pp0_iter1_reg;
        select_ln40_1_reg_2503_pp0_iter3_reg <= select_ln40_1_reg_2503_pp0_iter2_reg;
        select_ln40_1_reg_2503_pp0_iter4_reg <= select_ln40_1_reg_2503_pp0_iter3_reg;
        select_ln40_1_reg_2503_pp0_iter5_reg <= select_ln40_1_reg_2503_pp0_iter4_reg;
        select_ln40_1_reg_2503_pp0_iter6_reg <= select_ln40_1_reg_2503_pp0_iter5_reg;
        select_ln40_1_reg_2503_pp0_iter7_reg <= select_ln40_1_reg_2503_pp0_iter6_reg;
        select_ln40_1_reg_2503_pp0_iter8_reg <= select_ln40_1_reg_2503_pp0_iter7_reg;
        select_ln40_1_reg_2503_pp0_iter9_reg <= select_ln40_1_reg_2503_pp0_iter8_reg;
        shl_ln291_1_reg_2632 <= shl_ln291_1_fu_1325_p2;
        shl_ln291_reg_2622 <= shl_ln291_fu_1299_p2;
        tmp_1_reg_2662 <= {{bitcast_ln716_fu_1465_p1[62:52]}};
        tmp_2_reg_2566 <= Ex_1_fu_757_p2[32'd7];
        tmp_4_reg_2652 <= bitcast_ln716_fu_1465_p1[32'd63];
        trunc_ln379_reg_2548 <= trunc_ln379_fu_588_p1;
        trunc_ln37_1_reg_2667 <= trunc_ln37_1_fu_1491_p1;
        trunc_ln37_reg_2647 <= trunc_ln37_fu_1469_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= ref_tmp_i_0_fu_2490_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        count_int_reg <= count;
        data_int_reg <= data;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = ref_tmp_i_0_fu_2490_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_392_ce = 1'b1;
    end else begin
        grp_fu_392_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_397_ce = 1'b1;
    end else begin
        grp_fu_397_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_402_ce = 1'b1;
    end else begin
        grp_fu_402_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        ref_4oPi_table_100_ce0_local = 1'b1;
    end else begin
        ref_4oPi_table_100_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        second_order_float_sin_cos_K0_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        second_order_float_sin_cos_K1_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        second_order_float_sin_cos_K2_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K2_ce0_local = 1'b0;
    end
end

assign A_fu_1096_p3 = {{sin_basis_fu_1091_p2}, {tmp_140_i_fu_1051_p4}};

assign B_fu_1047_p1 = select_ln506_1_fu_1040_p3[21:0];

assign B_trunc_fu_1061_p4 = {{select_ln506_1_fu_1040_p3[21:7]}};

assign Ex_1_fu_757_p2 = (select_ln453_fu_597_p3 - zext_ln505_fu_753_p1);

assign Ex_2_fu_1117_p3 = ((cos_basis_reg_2572_pp0_iter12_reg[0:0] == 1'b1) ? 8'd0 : Ex_1_reg_2559_pp0_iter12_reg);

assign Ex_fu_592_p2 = ($signed(din_exp_reg_2524) + $signed(8'd131));

assign Mx_1_fu_1111_p3 = ((cos_basis_reg_2572_pp0_iter12_reg[0:0] == 1'b1) ? 29'd536870911 : Mx_reg_2553_pp0_iter12_reg);

assign Mx_bits_1_fu_667_p2 = (58'd0 - Mx_bits_fu_636_p4);

assign Mx_bits_2_fu_673_p3 = ((trunc_ln491_fu_663_p1[0:0] == 1'b1) ? Mx_bits_1_fu_667_p2 : Mx_bits_fu_636_p4);

assign Mx_bits_fu_636_p4 = {{h_fu_421_p2[76:19]}};

assign Mx_zeros_fu_729_p1 = tmp_139_i_fu_721_p3[5:0];

assign Range1_all_ones_2_i_fu_2078_p3 = ((and_ln37_3_fu_2026_p2[0:0] == 1'b1) ? and_ln37_4_fu_2032_p2 : select_ln37_6_fu_2062_p3);

assign Range1_all_zeros_2_i_fu_2086_p3 = ((and_ln37_3_fu_2026_p2[0:0] == 1'b1) ? and_ln37_5_fu_2050_p2 : select_ln37_7_fu_2070_p3);

assign Range2_all_ones_1_i_fu_2018_p3 = ((icmp_ln37_14_fu_1967_p2[0:0] == 1'b1) ? icmp_ln37_15_fu_1998_p2 : xor_ln37_9_fu_2012_p2);

assign X_fu_604_p3 = {{1'd1}, {din_sig_reg_2531}};

assign add_ln300_fu_1339_p2 = ($signed(sext_ln252_fu_1219_p1) + $signed(9'd127));

assign add_ln32_1_fu_1193_p2 = ($signed(add_ln32_fu_1183_p2) + $signed(sext_ln32_2_fu_1189_p1));

assign add_ln32_fu_1183_p2 = ($signed(sext_ln32_fu_1175_p1) + $signed(sext_ln32_1_fu_1179_p1));

assign add_ln376_fu_559_p2 = ($signed(din_exp_fu_539_p4) + $signed(8'd194));

assign add_ln37_1_fu_1549_p2 = ($signed(sub_ln37_1_fu_1533_p2) + $signed(12'd4080));

assign add_ln37_2_fu_1644_p2 = ($signed(sub_ln37_1_fu_1533_p2) + $signed(12'd4079));

assign add_ln37_3_fu_1681_p2 = ($signed(sub_ln37_1_fu_1533_p2) + $signed(12'd4078));

assign add_ln37_4_fu_1767_p2 = (select_ln37_2_fu_1614_p3 + zext_ln37_3_fu_1763_p1);

assign add_ln37_5_fu_1875_p2 = (select_ln37_9_fu_1867_p3 + add_ln37_fu_1498_p2);

assign add_ln37_6_fu_1897_p2 = (sub_ln37_1_fu_1533_p2 + 12'd16);

assign add_ln37_7_fu_1907_p2 = (sub_ln37_1_fu_1533_p2 + 12'd17);

assign add_ln37_fu_1498_p2 = ($signed(zext_ln37_fu_1495_p1) + $signed(12'd3073));

assign add_ln39_1_fu_2303_p2 = (shl_ln_fu_2296_p3 + 63'd140737488355328);

assign add_ln39_fu_2290_p2 = ($signed(sext_ln39_fu_2286_p1) + $signed(33'd65536));

assign add_ln40_fu_2476_p2 = ($signed(sext_ln40_3_fu_2454_p1) + $signed(32'd1));

assign addr_fu_565_p3 = ((closepath_fu_553_p2[0:0] == 1'b1) ? 8'd63 : add_ln376_fu_559_p2);

assign and_ln271_fu_980_p2 = (icmp_ln271_fu_970_p2 & icmp_ln271_1_fu_975_p2);

assign and_ln37_10_fu_2220_p2 = (xor_ln37_6_fu_2214_p2 & neg_src_0_i_fu_2159_p9);

assign and_ln37_11_fu_1815_p2 = (icmp_ln37_9_fu_1638_p2 & icmp_ln37_11_fu_1809_p2);

assign and_ln37_12_fu_1855_p2 = (tmp_7_fu_1739_p3 & and_ln37_1_fu_1793_p2);

assign and_ln37_13_fu_2146_p2 = (tmp_4_reg_2652 & icmp_ln37_10_fu_1921_p2);

assign and_ln37_14_fu_2185_p2 = (xor_ln37_4_fu_2179_p2 & icmp_ln37_10_fu_1921_p2);

assign and_ln37_15_fu_2246_p2 = (xor_ln37_7_fu_2240_p2 & or_ln37_3_fu_2226_p2);

assign and_ln37_16_fu_2252_p2 = (icmp_ln37_16_fu_1891_p2 & and_ln37_15_fu_2246_p2);

assign and_ln37_17_fu_1721_p2 = (select_ln37_fu_1521_p3 & lshr_ln37_2_fu_1715_p2);

assign and_ln37_1_fu_1793_p2 = (xor_ln37_2_fu_1787_p2 & icmp_ln37_1_fu_1543_p2);

assign and_ln37_3_fu_2026_p2 = (xor_ln37_8_fu_1935_p2 & icmp_ln37_13_fu_1961_p2);

assign and_ln37_4_fu_2032_p2 = (lD_0_i_fu_1955_p2 & Range2_all_ones_1_i_fu_2018_p3);

assign and_ln37_5_fu_2050_p2 = (xor_ln37_1_fu_2038_p2 & icmp_ln37_17_fu_2044_p2);

assign and_ln37_6_fu_2108_p2 = (or_ln37_1_fu_2102_p2 & Range2_all_ones_1_i_fu_2018_p3);

assign and_ln37_7_fu_2122_p2 = (carry_1_i_fu_1861_p2 & Range1_all_ones_2_i_fu_2078_p3);

assign and_ln37_8_fu_2202_p2 = (xor_ln37_5_fu_2197_p2 & or_ln37_2_fu_2191_p2);

assign and_ln37_9_fu_2208_p2 = (tmp_11_fu_1913_p3 & deleted_ones_0_i_fu_2140_p2);

assign and_ln37_fu_1757_p2 = (or_ln37_fu_1751_p2 & cond63_i_fu_1668_p3);

assign and_ln39_1_fu_2417_p2 = (xor_ln39_fu_2387_p2 & or_ln39_1_fu_2411_p2);

assign and_ln39_fu_2363_p2 = (tmp_15_fu_2331_p3 & or_ln39_fu_2357_p2);

assign and_ln40_1_fu_499_p2 = (tmp_18_fu_425_p3 & or_ln40_1_fu_493_p2);

assign and_ln40_fu_475_p2 = (xor_ln40_fu_469_p2 & or_ln40_fu_463_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ashr_ln37_fu_1604_p2 = $signed(select_ln37_fu_1521_p3) >>> zext_ln37_2_fu_1600_p1;

assign bitcast_ln716_fu_1465_p1 = pf_fu_406_p1;


always @ (tmp_144_i_fu_1277_p4) begin
    if (tmp_144_i_fu_1277_p4[0] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd0;
    end else if (tmp_144_i_fu_1277_p4[1] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd1;
    end else if (tmp_144_i_fu_1277_p4[2] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd2;
    end else if (tmp_144_i_fu_1277_p4[3] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd3;
    end else if (tmp_144_i_fu_1277_p4[4] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd4;
    end else if (tmp_144_i_fu_1277_p4[5] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd5;
    end else if (tmp_144_i_fu_1277_p4[6] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd6;
    end else if (tmp_144_i_fu_1277_p4[7] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd7;
    end else if (tmp_144_i_fu_1277_p4[8] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd8;
    end else if (tmp_144_i_fu_1277_p4[9] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd9;
    end else if (tmp_144_i_fu_1277_p4[10] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd10;
    end else if (tmp_144_i_fu_1277_p4[11] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd11;
    end else if (tmp_144_i_fu_1277_p4[12] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd12;
    end else if (tmp_144_i_fu_1277_p4[13] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd13;
    end else if (tmp_144_i_fu_1277_p4[14] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd14;
    end else if (tmp_144_i_fu_1277_p4[15] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd15;
    end else if (tmp_144_i_fu_1277_p4[16] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd16;
    end else if (tmp_144_i_fu_1277_p4[17] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd17;
    end else if (tmp_144_i_fu_1277_p4[18] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd18;
    end else if (tmp_144_i_fu_1277_p4[19] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd19;
    end else if (tmp_144_i_fu_1277_p4[20] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd20;
    end else if (tmp_144_i_fu_1277_p4[21] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd21;
    end else if (tmp_144_i_fu_1277_p4[22] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd22;
    end else if (tmp_144_i_fu_1277_p4[23] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd23;
    end else if (tmp_144_i_fu_1277_p4[24] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd24;
    end else if (tmp_144_i_fu_1277_p4[25] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd25;
    end else if (tmp_144_i_fu_1277_p4[26] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd26;
    end else if (tmp_144_i_fu_1277_p4[27] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd27;
    end else if (tmp_144_i_fu_1277_p4[28] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd28;
    end else if (tmp_144_i_fu_1277_p4[29] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd29;
    end else if (tmp_144_i_fu_1277_p4[30] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd30;
    end else if (tmp_144_i_fu_1277_p4[31] == 1'b1) begin
        c_1_fu_1287_p3 = 32'd31;
    end else begin
        c_1_fu_1287_p3 = 32'd32;
    end
end


always @ (tmp_143_i_fu_1259_p4) begin
    if (tmp_143_i_fu_1259_p4[0] == 1'b1) begin
        c_fu_1269_p3 = 32'd0;
    end else if (tmp_143_i_fu_1259_p4[1] == 1'b1) begin
        c_fu_1269_p3 = 32'd1;
    end else if (tmp_143_i_fu_1259_p4[2] == 1'b1) begin
        c_fu_1269_p3 = 32'd2;
    end else if (tmp_143_i_fu_1259_p4[3] == 1'b1) begin
        c_fu_1269_p3 = 32'd3;
    end else if (tmp_143_i_fu_1259_p4[4] == 1'b1) begin
        c_fu_1269_p3 = 32'd4;
    end else if (tmp_143_i_fu_1259_p4[5] == 1'b1) begin
        c_fu_1269_p3 = 32'd5;
    end else if (tmp_143_i_fu_1259_p4[6] == 1'b1) begin
        c_fu_1269_p3 = 32'd6;
    end else if (tmp_143_i_fu_1259_p4[7] == 1'b1) begin
        c_fu_1269_p3 = 32'd7;
    end else if (tmp_143_i_fu_1259_p4[8] == 1'b1) begin
        c_fu_1269_p3 = 32'd8;
    end else if (tmp_143_i_fu_1259_p4[9] == 1'b1) begin
        c_fu_1269_p3 = 32'd9;
    end else if (tmp_143_i_fu_1259_p4[10] == 1'b1) begin
        c_fu_1269_p3 = 32'd10;
    end else if (tmp_143_i_fu_1259_p4[11] == 1'b1) begin
        c_fu_1269_p3 = 32'd11;
    end else if (tmp_143_i_fu_1259_p4[12] == 1'b1) begin
        c_fu_1269_p3 = 32'd12;
    end else if (tmp_143_i_fu_1259_p4[13] == 1'b1) begin
        c_fu_1269_p3 = 32'd13;
    end else if (tmp_143_i_fu_1259_p4[14] == 1'b1) begin
        c_fu_1269_p3 = 32'd14;
    end else if (tmp_143_i_fu_1259_p4[15] == 1'b1) begin
        c_fu_1269_p3 = 32'd15;
    end else if (tmp_143_i_fu_1259_p4[16] == 1'b1) begin
        c_fu_1269_p3 = 32'd16;
    end else if (tmp_143_i_fu_1259_p4[17] == 1'b1) begin
        c_fu_1269_p3 = 32'd17;
    end else if (tmp_143_i_fu_1259_p4[18] == 1'b1) begin
        c_fu_1269_p3 = 32'd18;
    end else if (tmp_143_i_fu_1259_p4[19] == 1'b1) begin
        c_fu_1269_p3 = 32'd19;
    end else if (tmp_143_i_fu_1259_p4[20] == 1'b1) begin
        c_fu_1269_p3 = 32'd20;
    end else if (tmp_143_i_fu_1259_p4[21] == 1'b1) begin
        c_fu_1269_p3 = 32'd21;
    end else if (tmp_143_i_fu_1259_p4[22] == 1'b1) begin
        c_fu_1269_p3 = 32'd22;
    end else if (tmp_143_i_fu_1259_p4[23] == 1'b1) begin
        c_fu_1269_p3 = 32'd23;
    end else if (tmp_143_i_fu_1259_p4[24] == 1'b1) begin
        c_fu_1269_p3 = 32'd24;
    end else if (tmp_143_i_fu_1259_p4[25] == 1'b1) begin
        c_fu_1269_p3 = 32'd25;
    end else if (tmp_143_i_fu_1259_p4[26] == 1'b1) begin
        c_fu_1269_p3 = 32'd26;
    end else if (tmp_143_i_fu_1259_p4[27] == 1'b1) begin
        c_fu_1269_p3 = 32'd27;
    end else if (tmp_143_i_fu_1259_p4[28] == 1'b1) begin
        c_fu_1269_p3 = 32'd28;
    end else if (tmp_143_i_fu_1259_p4[29] == 1'b1) begin
        c_fu_1269_p3 = 32'd29;
    end else if (tmp_143_i_fu_1259_p4[30] == 1'b1) begin
        c_fu_1269_p3 = 32'd30;
    end else if (tmp_143_i_fu_1259_p4[31] == 1'b1) begin
        c_fu_1269_p3 = 32'd31;
    end else begin
        c_fu_1269_p3 = 32'd32;
    end
end

assign carry_1_i_fu_1861_p2 = (xor_ln37_fu_1781_p2 & and_ln37_12_fu_1855_p2);

assign closepath_fu_553_p2 = ((din_exp_fu_539_p4 < 8'd126) ? 1'b1 : 1'b0);

assign cond189_i_fu_2114_p3 = ((carry_1_i_fu_1861_p2[0:0] == 1'b1) ? and_ln37_6_fu_2108_p2 : Range1_all_ones_2_i_fu_2078_p3);

assign cond63_i_fu_1668_p3 = ((icmp_ln37_4_fu_1622_p2[0:0] == 1'b1) ? tmp_4_reg_2652 : tmp_6_fu_1654_p3);

assign cond85_i_fu_1733_p2 = (icmp_ln37_8_fu_1727_p2 & icmp_ln37_6_fu_1675_p2);

assign cos_basis_fu_771_p17 = 'bx;

assign data_1_fu_527_p1 = grp_fu_392_p2;

assign deleted_ones_0_i_fu_2140_p2 = (not_icmp_ln37_1062_fu_2134_p2 | cond189_i_fu_2114_p3);

assign din_exp_fu_539_p4 = {{data_1_fu_527_p1[30:23]}};

assign din_sig_fu_549_p1 = data_1_fu_527_p1[22:0];

assign empty_75_fu_1424_p3 = ((icmp_ln292_reg_2627[0:0] == 1'b1) ? tmp_fu_1406_p4 : tmp_s_fu_1415_p4);

assign empty_fu_1375_p1 = newexp_fu_1349_p2[7:0];

assign h_fu_421_p0 = {{shl_ln379_fu_614_p2[99:20]}};

assign h_fu_421_p1 = h_fu_421_p10;

assign h_fu_421_p10 = X_fu_604_p3;

assign icmp_ln271_1_fu_975_p2 = ((din_sig_reg_2531 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_970_p2 = ((din_exp_reg_2524 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln282_fu_986_p2 = ((din_exp_reg_2524 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln292_fu_1309_p2 = ((c_fu_1269_p3 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln306_fu_1363_p2 = ((result_fu_1209_p4 == 29'd0) ? 1'b1 : 1'b0);

assign icmp_ln37_10_fu_1921_p2 = (($signed(add_ln37_6_fu_1897_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln37_11_fu_1809_p2 = (($signed(tmp_9_fu_1799_p4) < $signed(8'd1)) ? 1'b1 : 1'b0);

assign icmp_ln37_12_fu_1941_p2 = ((add_ln37_6_fu_1897_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln37_13_fu_1961_p2 = (($signed(add_ln37_7_fu_1907_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln37_14_fu_1967_p2 = ((add_ln37_7_fu_1907_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln37_15_fu_1998_p2 = ((lshr_ln37_fu_1986_p2 == lshr_ln37_1_fu_1992_p2) ? 1'b1 : 1'b0);

assign icmp_ln37_16_fu_1891_p2 = (($signed(tmp_10_fu_1881_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln37_17_fu_2044_p2 = ((lshr_ln37_fu_1986_p2 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln37_18_fu_2056_p2 = ((add_ln37_7_fu_1907_p2 == 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln37_1_fu_1543_p2 = (($signed(sub_ln37_1_fu_1533_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln37_2_fu_1577_p2 = ((sub_ln37_1_fu_1533_p2 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln37_3_fu_1587_p2 = ((select_ln37_1_fu_1565_p3 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln37_4_fu_1622_p2 = (($signed(add_ln37_1_fu_1549_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln37_6_fu_1675_p2 = (($signed(sub_ln37_1_fu_1533_p2) > $signed(12'd17)) ? 1'b1 : 1'b0);

assign icmp_ln37_7_fu_1687_p2 = (($signed(add_ln37_3_fu_1681_p2) > $signed(12'd53)) ? 1'b1 : 1'b0);

assign icmp_ln37_8_fu_1727_p2 = ((and_ln37_17_fu_1721_p2 != 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln37_9_fu_1638_p2 = ((tmp_5_fu_1628_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_1528_p2 = ((trunc_ln37_reg_2647 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_2343_p2 = ((trunc_ln39_fu_2339_p1 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_1_fu_487_p2 = ((tmp_20_fu_447_p4 != 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln40_2_fu_2470_p2 = ((trunc_ln40_fu_2466_p1 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_457_p2 = ((tmp_20_fu_447_p4 != 16'd0) ? 1'b1 : 1'b0);

assign in_shift_1_fu_1305_p1 = shl_ln291_fu_1299_p2[27:0];

assign index_fu_811_p3 = {{din_sign_reg_2518}, {k_1_fu_656_p3}};

assign k_1_fu_656_p3 = ((closepath_reg_2537[0:0] == 1'b1) ? 3'd0 : k_fu_646_p4);

assign k_fu_646_p4 = {{h_fu_421_p2[79:77]}};

assign lD_0_i_fu_1955_p2 = (tobool130_i_fu_1947_p3 & icmp_ln37_12_fu_1941_p2);

assign lfo_fu_2266_p4 = ((and_ln37_8_fu_2202_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign lfo_fu_2266_p7 = 'bx;

assign lfo_fu_2266_p8 = {{icmp_ln37_fu_1528_p2}, {and_ln37_16_fu_2252_p2}};

assign lshr_ln37_1_fu_1992_p2 = 54'd18014398509481983 >> zext_ln37_6_fu_1982_p1;

assign lshr_ln37_2_fu_1715_p2 = 54'd18014398509481983 >> zext_ln37_5_fu_1711_p1;

assign lshr_ln37_fu_1986_p2 = select_ln37_fu_1521_p3 >> zext_ln37_6_fu_1982_p1;

assign lshr_ln506_fu_1028_p2 = zext_ln506_1_fu_1025_p1 >> zext_ln506_fu_1021_p1;

assign lshr_ln_fu_573_p4 = {{addr_fu_565_p3[7:4]}};

assign mod_1_fu_2373_p2 = ($signed(sext_ln39_1_fu_2327_p1) + $signed(zext_ln39_fu_2369_p1));

assign mod_2_fu_2423_p3 = ((and_ln39_1_fu_2417_p2[0:0] == 1'b1) ? 32'd2147483647 : mod_1_fu_2373_p2);

assign mod_fu_2317_p4 = {{add_ln39_1_fu_2303_p2[62:32]}};

assign mul_ln23_fu_1075_p0 = zext_ln23_fu_1071_p1;

assign mul_ln23_fu_1075_p1 = zext_ln23_fu_1071_p1;

assign mul_ln29_fu_409_p1 = mul_ln29_fu_409_p10;

assign mul_ln29_fu_409_p10 = B_reg_2597;

assign mul_ln30_fu_1159_p0 = mul_ln30_fu_1159_p00;

assign mul_ln30_fu_1159_p00 = B_squared_reg_2602;

assign mul_ln32_fu_413_p1 = mul_ln32_fu_413_p10;

assign mul_ln32_fu_413_p10 = Mx_1_fu_1111_p3;

assign neg_src_0_i_fu_2159_p2 = (tmp_4_reg_2652 & tmp_11_fu_1913_p3);

assign neg_src_0_i_fu_2159_p4 = (1'd1 ^ and_ln37_7_fu_2122_p2);

assign neg_src_0_i_fu_2159_p7 = 'bx;

assign neg_src_0_i_fu_2159_p8 = {{not_icmp_ln37_1062_fu_2134_p2}, {and_ln37_13_fu_2146_p2}};

assign newexp_fu_1349_p2 = ($signed(sext_ln300_fu_1345_p1) - $signed(shift_2_fu_1331_p3));

assign not_icmp_ln37_1062_fu_2134_p2 = (icmp_ln37_10_fu_1921_p2 ^ 1'd1);

assign or_ln282_fu_1386_p2 = (or_ln306_fu_1369_p2 | icmp_ln282_reg_2585_pp0_iter12_reg);

assign or_ln306_fu_1369_p2 = (tmp_3_fu_1355_p3 | icmp_ln306_fu_1363_p2);

assign or_ln37_1_fu_2102_p2 = (xor_ln37_1_fu_2038_p2 | tmp_12_fu_1927_p3);

assign or_ln37_2_fu_2191_p2 = (tmp_11_fu_1913_p3 | and_ln37_14_fu_2185_p2);

assign or_ln37_3_fu_2226_p2 = (and_ln37_8_fu_2202_p2 | and_ln37_10_fu_2220_p2);

assign or_ln37_fu_1751_p2 = (trunc_ln37_7_fu_1747_p1 | cond85_i_fu_1733_p2);

assign or_ln39_1_fu_2411_p2 = (xor_ln39_2_fu_2405_p2 | tmp_17_fu_2379_p3);

assign or_ln39_2_fu_2393_p2 = (xor_ln39_fu_2387_p2 | tmp_17_fu_2379_p3);

assign or_ln39_fu_2357_p2 = (tmp_16_fu_2349_p3 | icmp_ln39_fu_2343_p2);

assign or_ln40_1_fu_493_p2 = (xor_ln40_1_fu_481_p2 | icmp_ln40_1_fu_487_p2);

assign or_ln40_2_fu_513_p2 = (and_ln40_fu_475_p2 | and_ln40_1_fu_499_p2);

assign or_ln40_fu_463_p2 = (tmp_19_fu_439_p3 | icmp_ln40_fu_457_p2);

assign out_bits_2_fu_1251_p3 = {{tmp_142_i_fu_1241_p4}, {19'd262144}};

assign out_bits_fu_1233_p3 = {{tmp_141_i_fu_1223_p4}, {16'd32768}};

assign pf_fu_406_p0 = t_2_fu_1452_p4;

assign ref_4oPi_table_100_address0 = zext_ln378_fu_583_p1;

assign ref_tmp_i_0_fu_2490_p3 = ((tmp_22_fu_2458_p3[0:0] == 1'b1) ? select_ln40_2_fu_2482_p3 : sext_ln40_3_fu_2454_p1);

assign ref_tmp_i_i_fu_1831_p10 = {{{icmp_ln37_2_fu_1577_p2}, {and_ln37_1_fu_1793_p2}}, {and_ln37_11_fu_1815_p2}};

assign ref_tmp_i_i_fu_1831_p6 = trunc_ln37_4_fu_1583_p1 << zext_ln37_4_fu_1573_p1;

assign ref_tmp_i_i_fu_1831_p9 = 'bx;

assign result_fu_1209_p4 = {{mul_ln32_fu_413_p2[57:29]}};

assign results_exp_1_fu_1399_p3 = ((and_ln271_reg_2579_pp0_iter12_reg[0:0] == 1'b1) ? 8'd0 : results_exp_fu_1391_p3);

assign results_exp_fu_1391_p3 = ((or_ln282_fu_1386_p2[0:0] == 1'b1) ? select_ln282_fu_1379_p3 : empty_fu_1375_p1);

assign results_sig_1_fu_1445_p3 = ((and_ln271_reg_2579_pp0_iter13_reg[0:0] == 1'b1) ? 23'd0 : results_sig_fu_1438_p3);

assign results_sig_fu_1438_p3 = ((or_ln282_reg_2637[0:0] == 1'b1) ? select_ln282_2_fu_1431_p3 : empty_75_fu_1424_p3);

assign results_sign_1_fu_997_p2 = (xor_ln282_fu_991_p2 & results_sign_fu_962_p3);

assign results_sign_2_fu_1003_p3 = ((and_ln271_fu_980_p2[0:0] == 1'b1) ? din_sign_reg_2518 : results_sign_1_fu_997_p2);

assign results_sign_fu_962_p3 = ((cos_basis_fu_771_p19[0:0] == 1'b1) ? tmp_145_i_fu_818_p35 : tmp_146_i_fu_890_p35);

assign second_order_float_sin_cos_K0_address0 = zext_ln28_fu_1104_p1;

assign second_order_float_sin_cos_K1_address0 = zext_ln28_fu_1104_p1;

assign second_order_float_sin_cos_K2_address0 = zext_ln28_fu_1104_p1;

assign select_ln282_2_fu_1431_p3 = ((icmp_ln282_reg_2585_pp0_iter13_reg[0:0] == 1'b1) ? 23'd8388607 : 23'd0);

assign select_ln282_fu_1379_p3 = ((icmp_ln282_reg_2585_pp0_iter12_reg[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln37_1_fu_1565_p3 = ((icmp_ln37_1_fu_1543_p2[0:0] == 1'b1) ? trunc_ln37_3_fu_1555_p1 : sub_ln37_2_fu_1559_p2);

assign select_ln37_2_fu_1614_p3 = ((icmp_ln37_3_fu_1587_p2[0:0] == 1'b1) ? trunc_ln37_5_fu_1610_p1 : select_ln37_3_fu_1593_p3);

assign select_ln37_3_fu_1593_p3 = ((tmp_4_reg_2652[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln37_4_fu_2094_p3 = ((carry_1_i_fu_1861_p2[0:0] == 1'b1) ? Range1_all_ones_2_i_fu_2078_p3 : Range1_all_zeros_2_i_fu_2086_p3);

assign select_ln37_6_fu_2062_p3 = ((icmp_ln37_18_fu_2056_p2[0:0] == 1'b1) ? lD_0_i_fu_1955_p2 : xor_ln37_8_fu_1935_p2);

assign select_ln37_7_fu_2070_p3 = ((icmp_ln37_18_fu_2056_p2[0:0] == 1'b1) ? xor_ln37_1_fu_2038_p2 : xor_ln37_8_fu_1935_p2);

assign select_ln37_8_fu_1703_p3 = ((icmp_ln37_7_fu_1687_p2[0:0] == 1'b1) ? 6'd0 : sub_ln37_3_fu_1697_p2);

assign select_ln37_9_fu_1867_p3 = ((icmp_ln37_1_fu_1543_p2[0:0] == 1'b1) ? 12'd2 : 12'd1);

assign select_ln37_fu_1521_p3 = ((tmp_4_reg_2652[0:0] == 1'b1) ? sub_ln37_fu_1515_p2 : zext_ln37_1_fu_1511_p1);

assign select_ln40_1_fu_519_p3 = ((or_ln40_2_fu_513_p2[0:0] == 1'b1) ? select_ln40_fu_505_p3 : shl_ln40_fu_433_p2);

assign select_ln40_2_fu_2482_p3 = ((icmp_ln40_2_fu_2470_p2[0:0] == 1'b1) ? add_ln40_fu_2476_p2 : sext_ln40_3_fu_2454_p1);

assign select_ln40_fu_505_p3 = ((and_ln40_fu_475_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln453_fu_597_p3 = ((closepath_reg_2537[0:0] == 1'b1) ? Ex_fu_592_p2 : 8'd0);

assign select_ln506_1_fu_1040_p3 = ((tmp_2_reg_2566[0:0] == 1'b1) ? lshr_ln506_fu_1028_p2 : shl_ln506_fu_1034_p2);

assign select_ln506_fu_1015_p3 = ((tmp_2_reg_2566[0:0] == 1'b1) ? sub_ln506_fu_1010_p2 : Ex_1_reg_2559);

assign sext_ln252_fu_1219_p1 = $signed(Ex_2_fu_1117_p3);

assign sext_ln300_fu_1345_p1 = $signed(add_ln300_fu_1339_p2);

assign sext_ln32_1_fu_1179_p1 = $signed(trunc_ln_fu_1145_p4);

assign sext_ln32_2_fu_1189_p1 = $signed(trunc_ln1_fu_1165_p4);

assign sext_ln32_fu_1175_p1 = $signed(t1_fu_1126_p4);

assign sext_ln37_1_fu_1903_p1 = add_ln37_6_fu_1897_p2;

assign sext_ln37_2_fu_1978_p1 = add_ln37_7_fu_1907_p2;

assign sext_ln37_fu_1650_p1 = $signed(add_ln37_2_fu_1644_p2);

assign sext_ln39_1_fu_2327_p1 = $signed(mod_fu_2317_p4);

assign sext_ln39_fu_2286_p1 = $signed(lfo_fu_2266_p9);

assign sext_ln40_2_fu_2440_p1 = mul_ln40_fu_417_p2;

assign sext_ln40_3_fu_2454_p1 = $signed(tmp_21_fu_2444_p4);

assign sext_ln75_fu_717_p1 = $signed(tmp_138_i_fu_709_p3);

assign shift_1_fu_1315_p2 = (c_1_fu_1287_p3 + 32'd16);

assign shift_2_fu_1331_p3 = ((icmp_ln292_fu_1309_p2[0:0] == 1'b1) ? shift_1_fu_1315_p2 : c_fu_1269_p3);

assign shl_ln291_1_fu_1325_p2 = zext_ln291_1_fu_1321_p1 << c_1_fu_1287_p3;

assign shl_ln291_fu_1299_p2 = zext_ln291_fu_1295_p1 << c_fu_1269_p3;

assign shl_ln379_fu_614_p2 = ref_4oPi_table_100_q0 << zext_ln379_fu_611_p1;

assign shl_ln40_fu_433_p2 = data_int_reg << 32'd16;

assign shl_ln504_fu_737_p2 = Mx_bits_2_fu_673_p3 << zext_ln504_fu_733_p1;

assign shl_ln506_fu_1034_p2 = zext_ln506_1_fu_1025_p1 << zext_ln506_fu_1021_p1;

assign shl_ln_fu_2296_p3 = {{add_ln39_reg_2672}, {30'd0}};

assign sin_basis_fu_1091_p2 = (cos_basis_reg_2572 ^ 1'd1);

assign sub_ln37_1_fu_1533_p2 = (12'd1075 - zext_ln37_fu_1495_p1);

assign sub_ln37_2_fu_1559_p2 = (11'd16 - trunc_ln37_2_fu_1539_p1);

assign sub_ln37_3_fu_1697_p2 = ($signed(6'd53) - $signed(trunc_ln37_6_fu_1693_p1));

assign sub_ln37_fu_1515_p2 = (54'd0 - zext_ln37_1_fu_1511_p1);

assign sub_ln506_fu_1010_p2 = (8'd0 - Ex_1_reg_2559);

assign t1_fu_1126_p4 = {{second_order_float_sin_cos_K0_q0[29:1]}};

assign t_2_fu_1452_p4 = {{{results_sign_2_reg_2592_pp0_iter13_reg}, {results_exp_1_reg_2642}}, {results_sig_1_fu_1445_p3}};

assign t_fu_691_p3 = {{tmp_136_i3_fu_681_p4}, {1'd1}};

assign tmp_10_fu_1881_p4 = {{add_ln37_5_fu_1875_p2[11:4]}};

assign tmp_11_fu_1913_p3 = ref_tmp_i_i_fu_1831_p11[32'd31];

assign tmp_12_fu_1927_p3 = add_ln37_6_fu_1897_p2[32'd11];

assign tmp_136_i3_fu_681_p4 = {{Mx_bits_2_fu_673_p3[57:29]}};

integer ap_tvar_int_0;

always @ (t_fu_691_p3) begin
    for (ap_tvar_int_0 = 30 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 29 - 0) begin
            tmp_137_i_fu_699_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_137_i_fu_699_p4[ap_tvar_int_0] = t_fu_691_p3[29 - ap_tvar_int_0];
        end
    end
end

assign tmp_138_i_fu_709_p3 = {{1'd1}, {tmp_137_i_fu_699_p4}};


always @ (sext_ln75_fu_717_p1) begin
    if (sext_ln75_fu_717_p1[0] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd0;
    end else if (sext_ln75_fu_717_p1[1] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd1;
    end else if (sext_ln75_fu_717_p1[2] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd2;
    end else if (sext_ln75_fu_717_p1[3] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd3;
    end else if (sext_ln75_fu_717_p1[4] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd4;
    end else if (sext_ln75_fu_717_p1[5] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd5;
    end else if (sext_ln75_fu_717_p1[6] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd6;
    end else if (sext_ln75_fu_717_p1[7] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd7;
    end else if (sext_ln75_fu_717_p1[8] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd8;
    end else if (sext_ln75_fu_717_p1[9] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd9;
    end else if (sext_ln75_fu_717_p1[10] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd10;
    end else if (sext_ln75_fu_717_p1[11] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd11;
    end else if (sext_ln75_fu_717_p1[12] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd12;
    end else if (sext_ln75_fu_717_p1[13] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd13;
    end else if (sext_ln75_fu_717_p1[14] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd14;
    end else if (sext_ln75_fu_717_p1[15] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd15;
    end else if (sext_ln75_fu_717_p1[16] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd16;
    end else if (sext_ln75_fu_717_p1[17] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd17;
    end else if (sext_ln75_fu_717_p1[18] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd18;
    end else if (sext_ln75_fu_717_p1[19] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd19;
    end else if (sext_ln75_fu_717_p1[20] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd20;
    end else if (sext_ln75_fu_717_p1[21] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd21;
    end else if (sext_ln75_fu_717_p1[22] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd22;
    end else if (sext_ln75_fu_717_p1[23] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd23;
    end else if (sext_ln75_fu_717_p1[24] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd24;
    end else if (sext_ln75_fu_717_p1[25] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd25;
    end else if (sext_ln75_fu_717_p1[26] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd26;
    end else if (sext_ln75_fu_717_p1[27] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd27;
    end else if (sext_ln75_fu_717_p1[28] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd28;
    end else if (sext_ln75_fu_717_p1[29] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd29;
    end else if (sext_ln75_fu_717_p1[30] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd30;
    end else if (sext_ln75_fu_717_p1[31] == 1'b1) begin
        tmp_139_i_fu_721_p3 = 32'd31;
    end else begin
        tmp_139_i_fu_721_p3 = 32'd32;
    end
end

assign tmp_13_fu_2004_p3 = add_ln37_7_fu_1907_p2[32'd11];

assign tmp_140_i_fu_1051_p4 = {{select_ln506_1_fu_1040_p3[28:22]}};

assign tmp_141_i_fu_1223_p4 = {{mul_ln32_fu_413_p2[57:42]}};

assign tmp_142_i_fu_1241_p4 = {{mul_ln32_fu_413_p2[41:29]}};

integer ap_tvar_int_1;

always @ (out_bits_fu_1233_p3) begin
    for (ap_tvar_int_1 = 32 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 31 - 0) begin
            tmp_143_i_fu_1259_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_143_i_fu_1259_p4[ap_tvar_int_1] = out_bits_fu_1233_p3[31 - ap_tvar_int_1];
        end
    end
end

integer ap_tvar_int_2;

always @ (out_bits_2_fu_1251_p3) begin
    for (ap_tvar_int_2 = 32 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 31 - 0) begin
            tmp_144_i_fu_1277_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_144_i_fu_1277_p4[ap_tvar_int_2] = out_bits_2_fu_1251_p3[31 - ap_tvar_int_2];
        end
    end
end

assign tmp_145_i_fu_818_p33 = 'bx;

assign tmp_146_i_fu_890_p33 = 'bx;

assign tmp_14_fu_2309_p3 = add_ln39_1_fu_2303_p2[32'd62];

assign tmp_15_fu_2331_p3 = add_ln39_1_fu_2303_p2[32'd31];

assign tmp_16_fu_2349_p3 = add_ln39_1_fu_2303_p2[32'd32];

assign tmp_17_fu_2379_p3 = mod_1_fu_2373_p2[32'd31];

assign tmp_18_fu_425_p3 = data_int_reg[32'd31];

assign tmp_19_fu_439_p3 = data_int_reg[32'd15];

assign tmp_20_fu_447_p4 = {{data_int_reg[31:16]}};

assign tmp_21_fu_2444_p4 = {{mul_ln40_fu_417_p2[62:32]}};

assign tmp_22_fu_2458_p3 = sext_ln40_2_fu_2440_p1[32'd63];

assign tmp_3_fu_1355_p3 = newexp_fu_1349_p2[32'd31];

assign tmp_5_fu_1628_p4 = {{select_ln37_1_fu_1565_p3[10:5]}};

assign tmp_6_fu_1654_p3 = select_ln37_fu_1521_p3[sext_ln37_fu_1650_p1];

assign tmp_7_fu_1739_p3 = select_ln37_2_fu_1614_p3[32'd31];

assign tmp_8_fu_1773_p3 = add_ln37_4_fu_1767_p2[32'd31];

assign tmp_9_fu_1799_p4 = {{sub_ln37_1_fu_1533_p2[11:4]}};

assign tmp_fu_1406_p4 = {{shl_ln291_1_reg_2632[27:5]}};

assign tmp_s_fu_1415_p4 = {{shl_ln291_reg_2622[27:5]}};

assign tobool130_i_fu_1947_p3 = select_ln37_fu_1521_p3[sext_ln37_1_fu_1903_p1];

assign trunc_ln1_fu_1165_p4 = {{mul_ln30_fu_1159_p2[29:16]}};

assign trunc_ln379_fu_588_p1 = addr_fu_565_p3[3:0];

assign trunc_ln37_1_fu_1491_p1 = bitcast_ln716_fu_1465_p1[51:0];

assign trunc_ln37_2_fu_1539_p1 = sub_ln37_1_fu_1533_p2[10:0];

assign trunc_ln37_3_fu_1555_p1 = add_ln37_1_fu_1549_p2[10:0];

assign trunc_ln37_4_fu_1583_p1 = select_ln37_fu_1521_p3[31:0];

assign trunc_ln37_5_fu_1610_p1 = ashr_ln37_fu_1604_p2[31:0];

assign trunc_ln37_6_fu_1693_p1 = add_ln37_3_fu_1681_p2[5:0];

assign trunc_ln37_7_fu_1747_p1 = select_ln37_2_fu_1614_p3[0:0];

assign trunc_ln37_fu_1469_p1 = bitcast_ln716_fu_1465_p1[62:0];

assign trunc_ln39_fu_2339_p1 = add_ln39_1_fu_2303_p2[30:0];

assign trunc_ln40_fu_2466_p1 = mul_ln40_fu_417_p2[31:0];

assign trunc_ln491_fu_663_p1 = k_1_fu_656_p3[0:0];

assign trunc_ln_fu_1145_p4 = {{mul_ln29_fu_409_p2[44:23]}};

assign xor_ln282_fu_991_p2 = (icmp_ln282_fu_986_p2 ^ 1'd1);

assign xor_ln37_1_fu_2038_p2 = (lD_0_i_fu_1955_p2 ^ 1'd1);

assign xor_ln37_2_fu_1787_p2 = (icmp_ln37_2_fu_1577_p2 ^ 1'd1);

assign xor_ln37_4_fu_2179_p2 = (select_ln37_4_fu_2094_p3 ^ 1'd1);

assign xor_ln37_5_fu_2197_p2 = (tmp_4_reg_2652 ^ 1'd1);

assign xor_ln37_6_fu_2214_p2 = (1'd1 ^ and_ln37_9_fu_2208_p2);

assign xor_ln37_7_fu_2240_p2 = (icmp_ln37_fu_1528_p2 ^ 1'd1);

assign xor_ln37_8_fu_1935_p2 = (tmp_12_fu_1927_p3 ^ 1'd1);

assign xor_ln37_9_fu_2012_p2 = (tmp_13_fu_2004_p3 ^ 1'd1);

assign xor_ln37_fu_1781_p2 = (tmp_8_fu_1773_p3 ^ 1'd1);

assign xor_ln39_1_fu_2399_p2 = (tmp_14_fu_2309_p3 ^ or_ln39_2_fu_2393_p2);

assign xor_ln39_2_fu_2405_p2 = (xor_ln39_1_fu_2399_p2 ^ 1'd1);

assign xor_ln39_fu_2387_p2 = (tmp_14_fu_2309_p3 ^ 1'd1);

assign xor_ln40_1_fu_481_p2 = (tmp_19_fu_439_p3 ^ 1'd1);

assign xor_ln40_fu_469_p2 = (tmp_18_fu_425_p3 ^ 1'd1);

assign zext_ln23_fu_1071_p1 = B_trunc_fu_1061_p4;

assign zext_ln28_fu_1104_p1 = A_fu_1096_p3;

assign zext_ln291_1_fu_1321_p1 = in_shift_1_fu_1305_p1;

assign zext_ln291_fu_1295_p1 = result_fu_1209_p4;

assign zext_ln378_fu_583_p1 = lshr_ln_fu_573_p4;

assign zext_ln379_fu_611_p1 = trunc_ln379_reg_2548;

assign zext_ln37_1_cast_fu_1504_p3 = {{1'd1}, {trunc_ln37_1_reg_2667}};

assign zext_ln37_1_fu_1511_p1 = zext_ln37_1_cast_fu_1504_p3;

assign zext_ln37_2_fu_1600_p1 = select_ln37_1_fu_1565_p3;

assign zext_ln37_3_fu_1763_p1 = and_ln37_fu_1757_p2;

assign zext_ln37_4_fu_1573_p1 = select_ln37_1_fu_1565_p3;

assign zext_ln37_5_fu_1711_p1 = select_ln37_8_fu_1703_p3;

assign zext_ln37_6_fu_1982_p1 = $unsigned(sext_ln37_2_fu_1978_p1);

assign zext_ln37_fu_1495_p1 = tmp_1_reg_2662;

assign zext_ln39_fu_2369_p1 = and_ln39_fu_2363_p2;

assign zext_ln504_fu_733_p1 = Mx_zeros_fu_729_p1;

assign zext_ln505_fu_753_p1 = Mx_zeros_fu_729_p1;

assign zext_ln506_1_fu_1025_p1 = Mx_reg_2553;

assign zext_ln506_fu_1021_p1 = select_ln506_fu_1015_p3;

endmodule //pedal_top_tremolo
