// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pedal_top_soft_clipping_distortion (
        ap_clk,
        ap_rst,
        data,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] data;
output  [15:0] ap_return;
input   ap_ce;

reg[15:0] ap_return;

reg   [0:0] tmp_27_reg_1978;
wire    ap_block_pp0_stage0_11001;
wire   [25:0] x_2_fu_498_p2;
reg   [25:0] x_2_reg_1984;
wire   [31:0] x_assign_fu_845_p3;
reg   [31:0] x_assign_reg_1989;
wire   [62:0] trunc_ln31_2_fu_857_p1;
reg   [62:0] trunc_ln31_2_reg_1994;
reg   [0:0] tmp_40_reg_1999;
reg   [10:0] tmp_37_reg_2009;
wire   [51:0] trunc_ln31_3_fu_879_p1;
reg   [51:0] trunc_ln31_3_reg_2014;
wire   [31:0] ref_tmp_i_i42_4_fu_1654_p9;
reg  signed [31:0] ref_tmp_i_i42_4_reg_2019;
wire   [31:0] grp_generic_tanh_float_s_fu_228_ap_return;
reg    grp_generic_tanh_float_s_fu_228_ap_ce;
wire    ap_block_pp0_stage0_11001_ignoreCallOp133;
wire    ap_block_pp0_stage0_ignoreCallOp133;
wire    ap_block_pp0_stage0;
wire   [27:0] mul_ln31_fu_243_p1;
wire   [49:0] mul_ln28_1_fu_248_p1;
wire   [15:0] tmp_s_fu_275_p4;
wire   [0:0] tmp_23_fu_267_p3;
wire   [0:0] icmp_ln28_fu_285_p2;
wire   [0:0] tmp_fu_253_p3;
wire   [0:0] or_ln28_fu_291_p2;
wire   [0:0] xor_ln28_fu_297_p2;
wire   [0:0] icmp_ln28_1_fu_315_p2;
wire   [0:0] xor_ln28_1_fu_309_p2;
wire   [0:0] or_ln28_1_fu_321_p2;
wire   [0:0] and_ln28_fu_303_p2;
wire   [0:0] and_ln28_1_fu_327_p2;
wire   [0:0] or_ln28_2_fu_333_p2;
wire   [31:0] select_ln28_fu_339_p3;
wire   [31:0] shl_ln28_fu_261_p2;
wire   [31:0] select_ln28_1_fu_347_p3;
wire  signed [47:0] shl_ln28_1_fu_355_p3;
wire   [96:0] mul_ln28_1_fu_248_p2;
wire   [96:0] sub_ln28_fu_368_p2;
wire  signed [21:0] tmp_26_fu_392_p4;
wire   [0:0] tmp_24_fu_374_p3;
wire   [21:0] tmp_25_fu_382_p4;
wire   [21:0] select_ln28_4_fu_406_p3;
wire  signed [40:0] sext_ln28_2_fu_414_p1;
wire   [40:0] sub_ln28_1_fu_418_p2;
wire  signed [40:0] sext_ln28_1_fu_402_p1;
wire   [40:0] select_ln28_3_fu_424_p3;
wire   [40:0] shl_ln28_2_fu_432_p2;
wire   [40:0] shl_ln28_3_fu_438_p2;
wire   [40:0] add_ln28_fu_444_p2;
wire   [24:0] x_fu_458_p4;
wire   [0:0] tmp_29_fu_480_p3;
wire   [0:0] tmp_28_fu_472_p3;
wire   [0:0] and_ln28_2_fu_488_p2;
wire  signed [25:0] sext_ln28_3_fu_468_p1;
wire   [25:0] zext_ln28_fu_494_p1;
wire  signed [31:0] sext_ln28_4_fu_504_p1;
wire   [0:0] tmp_30_fu_507_p3;
wire   [0:0] xor_ln28_2_fu_515_p2;
wire   [0:0] or_ln28_3_fu_520_p2;
wire   [0:0] xor_ln28_3_fu_526_p2;
wire   [0:0] xor_ln28_4_fu_531_p2;
wire   [0:0] or_ln28_4_fu_537_p2;
wire   [0:0] and_ln28_3_fu_543_p2;
wire   [31:0] x_3_fu_549_p3;
wire   [0:0] tmp_33_fu_563_p3;
wire   [31:0] sub_ln31_fu_571_p2;
wire   [31:0] select_ln31_fu_577_p3;
reg   [31:0] tmp_22_fu_585_p4;
reg   [31:0] tmp_31_fu_595_p3;
wire   [31:0] sub_ln31_1_fu_607_p2;
wire   [31:0] add_ln31_fu_613_p2;
wire   [30:0] tmp_34_fu_619_p4;
wire   [4:0] trunc_ln31_1_fu_635_p1;
wire   [4:0] sub_ln31_7_fu_639_p2;
wire   [31:0] zext_ln31_5_fu_645_p1;
wire   [31:0] lshr_ln31_4_fu_649_p2;
wire   [31:0] and_ln31_25_fu_655_p2;
wire   [0:0] icmp_ln31_1_fu_629_p2;
wire   [0:0] icmp_ln31_2_fu_661_p2;
wire   [0:0] tmp_35_fu_673_p3;
wire   [0:0] tmp_38_fu_687_p3;
wire   [0:0] xor_ln31_14_fu_681_p2;
wire   [0:0] and_ln31_fu_695_p2;
wire   [0:0] phi_ln31_fu_667_p2;
wire   [0:0] or_ln31_2_fu_701_p2;
wire   [31:0] add_ln31_1_fu_725_p2;
wire   [63:0] zext_ln31_fu_715_p1;
wire   [63:0] zext_ln31_1_fu_731_p1;
wire   [31:0] sub_ln31_2_fu_741_p2;
wire   [63:0] zext_ln31_2_fu_747_p1;
wire   [0:0] icmp_ln31_3_fu_719_p2;
wire   [63:0] lshr_ln31_fu_735_p2;
wire   [63:0] shl_ln31_fu_751_p2;
wire   [1:0] or_ln_fu_707_p3;
wire   [63:0] cond46_i_i_fu_757_p3;
wire   [63:0] zext_ln31_3_fu_765_p1;
wire   [63:0] add_ln31_2_fu_769_p2;
wire   [62:0] lshr_ln31_1_fu_775_p4;
wire   [0:0] tmp_39_fu_789_p3;
wire   [7:0] trunc_ln31_fu_603_p1;
wire   [7:0] sub_ln31_6_fu_805_p2;
wire   [7:0] select_ln31_1_fu_797_p3;
wire   [7:0] add_ln31_3_fu_811_p2;
wire   [63:0] zext_ln31_9_fu_785_p1;
wire   [8:0] tmp_32_fu_817_p3;
wire   [63:0] pi_assign_fu_825_p5;
wire   [31:0] LD_fu_837_p1;
wire   [0:0] icmp_ln31_fu_557_p2;
wire   [31:0] bitcast_ln758_fu_841_p1;
wire   [63:0] pf_fu_239_p1;
wire   [63:0] bitcast_ln716_fu_853_p1;
wire   [11:0] zext_ln31_4_fu_883_p1;
wire   [52:0] zext_ln31_5_cast_fu_892_p3;
wire   [53:0] zext_ln31_11_fu_899_p1;
wire   [53:0] sub_ln31_3_fu_903_p2;
wire   [11:0] sub_ln31_4_fu_921_p2;
wire   [11:0] add_ln31_5_fu_937_p2;
wire   [10:0] trunc_ln31_4_fu_927_p1;
wire   [0:0] icmp_ln31_5_fu_931_p2;
wire   [10:0] trunc_ln31_5_fu_943_p1;
wire   [10:0] sub_ln31_5_fu_947_p2;
wire   [10:0] select_ln31_3_fu_953_p3;
wire   [53:0] select_ln31_2_fu_909_p3;
wire   [53:0] zext_ln31_7_fu_988_p1;
wire   [53:0] ashr_ln31_fu_992_p2;
wire   [0:0] icmp_ln31_7_fu_975_p2;
wire   [31:0] trunc_ln31_7_fu_998_p1;
wire   [31:0] select_ln31_5_fu_981_p3;
wire   [5:0] tmp_41_fu_1016_p4;
wire   [11:0] add_ln31_6_fu_1032_p2;
wire  signed [31:0] sext_ln31_fu_1038_p1;
wire   [31:0] trunc_ln31_6_fu_971_p1;
wire   [31:0] zext_ln31_6_fu_961_p1;
wire   [0:0] icmp_ln31_8_fu_1010_p2;
wire   [0:0] tmp_42_fu_1042_p3;
wire   [11:0] add_ln31_7_fu_1069_p2;
wire   [5:0] trunc_ln31_8_fu_1081_p1;
wire   [0:0] icmp_ln31_11_fu_1075_p2;
wire   [5:0] sub_ln31_8_fu_1085_p2;
wire   [5:0] select_ln31_13_fu_1091_p3;
wire   [53:0] zext_ln31_12_fu_1099_p1;
wire   [53:0] lshr_ln31_5_fu_1103_p2;
wire   [53:0] and_ln31_26_fu_1109_p2;
wire   [0:0] icmp_ln31_10_fu_1063_p2;
wire   [0:0] icmp_ln31_12_fu_1115_p2;
wire   [31:0] select_ln31_4_fu_1002_p3;
wire   [0:0] trunc_ln31_9_fu_1135_p1;
wire   [0:0] cond85_i_fu_1121_p2;
wire   [0:0] or_ln31_1_fu_1139_p2;
wire   [0:0] cond63_i_fu_1056_p3;
wire   [0:0] and_ln31_1_fu_1145_p2;
wire   [31:0] zext_ln31_8_fu_1151_p1;
wire   [31:0] add_ln31_8_fu_1155_p2;
wire   [0:0] tmp_44_fu_1161_p3;
wire   [0:0] icmp_ln31_6_fu_965_p2;
wire   [0:0] xor_ln31_2_fu_1175_p2;
wire   [7:0] tmp_45_fu_1187_p4;
wire   [0:0] icmp_ln31_13_fu_1197_p2;
wire   [0:0] icmp_ln31_9_fu_1026_p2;
wire   [0:0] and_ln31_18_fu_1181_p2;
wire   [0:0] and_ln31_19_fu_1203_p2;
wire   [31:0] ref_tmp_i_i_fu_1219_p6;
wire   [31:0] ref_tmp_i_i_fu_1219_p9;
wire   [2:0] ref_tmp_i_i_fu_1219_p10;
wire   [0:0] tmp_43_fu_1127_p3;
wire   [0:0] and_ln31_20_fu_1243_p2;
wire   [0:0] xor_ln31_fu_1169_p2;
wire   [11:0] select_ln31_14_fu_1255_p3;
wire   [11:0] add_ln31_4_fu_886_p2;
wire   [11:0] add_ln31_9_fu_1263_p2;
wire   [7:0] tmp_46_fu_1269_p4;
wire  signed [11:0] add_ln31_10_fu_1285_p2;
wire   [31:0] ref_tmp_i_i_fu_1219_p11;
wire   [0:0] tmp_48_fu_1315_p3;
wire  signed [31:0] sext_ln31_1_fu_1291_p1;
wire   [0:0] icmp_ln31_16_fu_1329_p2;
wire   [0:0] tobool130_i_fu_1335_p3;
wire  signed [11:0] add_ln31_11_fu_1295_p2;
wire   [0:0] tmp_47_fu_1301_p3;
wire  signed [31:0] sext_ln31_2_fu_1366_p1;
wire   [53:0] zext_ln31_13_fu_1370_p1;
wire   [53:0] lshr_ln31_2_fu_1374_p2;
wire   [53:0] lshr_ln31_3_fu_1380_p2;
wire   [0:0] tmp_49_fu_1392_p3;
wire   [0:0] icmp_ln31_18_fu_1355_p2;
wire   [0:0] icmp_ln31_19_fu_1386_p2;
wire   [0:0] xor_ln31_16_fu_1400_p2;
wire   [0:0] icmp_ln31_17_fu_1349_p2;
wire   [0:0] xor_ln31_15_fu_1323_p2;
wire   [0:0] Range2_all_ones_1_i_fu_1406_p3;
wire   [0:0] lD_0_i_fu_1343_p2;
wire   [0:0] icmp_ln31_20_fu_1432_p2;
wire   [0:0] xor_ln31_1_fu_1426_p2;
wire   [0:0] icmp_ln31_21_fu_1444_p2;
wire   [0:0] and_ln31_3_fu_1414_p2;
wire   [0:0] and_ln31_4_fu_1420_p2;
wire   [0:0] select_ln31_8_fu_1450_p3;
wire   [0:0] and_ln31_5_fu_1438_p2;
wire   [0:0] select_ln31_12_fu_1458_p3;
wire   [0:0] carry_1_i_fu_1249_p2;
wire   [0:0] Range1_all_ones_2_i_fu_1466_p3;
wire   [0:0] Range1_all_zeros_2_i_fu_1474_p3;
wire   [0:0] or_ln31_fu_1490_p2;
wire   [0:0] and_ln31_6_fu_1496_p2;
wire   [0:0] and_ln31_7_fu_1510_p2;
wire   [0:0] icmp_ln31_15_fu_1309_p2;
wire   [0:0] cond189_i_fu_1502_p3;
wire   [0:0] not_icmp_ln31_1538_fu_1522_p2;
wire   [0:0] and_ln31_21_fu_1534_p2;
wire   [0:0] neg_src_0_i_fu_1547_p2;
wire   [0:0] neg_src_0_i_fu_1547_p4;
wire   [0:0] neg_src_0_i_fu_1547_p7;
wire   [1:0] neg_src_0_i_fu_1547_p8;
wire   [0:0] select_ln31_6_fu_1482_p3;
wire   [0:0] xor_ln31_4_fu_1567_p2;
wire   [0:0] and_ln31_22_fu_1573_p2;
wire   [0:0] or_ln31_3_fu_1579_p2;
wire   [0:0] xor_ln31_5_fu_1585_p2;
wire   [0:0] deleted_ones_0_i_fu_1528_p2;
wire   [0:0] and_ln31_9_fu_1596_p2;
wire   [0:0] neg_src_0_i_fu_1547_p9;
wire   [0:0] xor_ln31_6_fu_1602_p2;
wire   [0:0] and_ln31_10_fu_1608_p2;
wire   [0:0] and_ln31_8_fu_1590_p2;
wire   [0:0] icmp_ln31_4_fu_916_p2;
wire   [0:0] or_ln31_4_fu_1614_p2;
wire   [0:0] xor_ln31_7_fu_1628_p2;
wire   [0:0] and_ln31_23_fu_1634_p2;
wire   [0:0] icmp_ln31_14_fu_1279_p2;
wire   [0:0] and_ln31_24_fu_1640_p2;
wire   [31:0] ref_tmp_i_i42_4_fu_1654_p4;
wire   [31:0] ref_tmp_i_i42_4_fu_1654_p7;
wire   [1:0] ref_tmp_i_i42_4_fu_1654_p8;
wire   [58:0] mul_ln31_fu_243_p2;
wire   [14:0] trunc_ln31_10_fu_1704_p1;
wire   [0:0] tmp_53_fu_1722_p3;
wire   [0:0] icmp_ln31_22_fu_1708_p2;
wire   [0:0] or_ln31_5_fu_1730_p2;
wire   [0:0] tmp_51_fu_1696_p3;
wire   [0:0] and_ln31_11_fu_1736_p2;
wire   [31:0] result_fu_1686_p4;
wire   [31:0] zext_ln31_10_fu_1742_p1;
wire   [31:0] result_1_fu_1746_p2;
wire   [0:0] tmp_54_fu_1752_p3;
wire   [0:0] tmp_52_fu_1714_p3;
wire   [0:0] xor_ln31_8_fu_1760_p2;
wire   [9:0] tmp_20_fu_1780_p4;
wire   [10:0] tmp_21_fu_1796_p4;
wire   [0:0] and_ln31_12_fu_1766_p2;
wire   [0:0] icmp_ln31_24_fu_1806_p2;
wire   [0:0] icmp_ln31_25_fu_1812_p2;
wire   [0:0] tmp_55_fu_1772_p3;
wire   [0:0] icmp_ln31_23_fu_1790_p2;
wire   [0:0] xor_ln31_9_fu_1826_p2;
wire   [0:0] and_ln31_13_fu_1832_p2;
wire   [0:0] and_ln31_14_fu_1846_p2;
wire   [0:0] tmp_50_fu_1678_p3;
wire   [0:0] xor_ln31_10_fu_1852_p2;
wire   [0:0] select_ln31_9_fu_1818_p3;
wire   [0:0] xor_ln31_11_fu_1864_p2;
wire   [0:0] or_ln31_6_fu_1870_p2;
wire   [0:0] xor_ln31_12_fu_1876_p2;
wire   [0:0] select_ln31_10_fu_1838_p3;
wire   [0:0] and_ln31_16_fu_1888_p2;
wire   [0:0] empty_fu_1858_p2;
wire   [0:0] xor_ln31_13_fu_1894_p2;
wire   [0:0] and_ln31_15_fu_1882_p2;
wire   [0:0] and_ln31_17_fu_1900_p2;
wire   [0:0] or_ln31_7_fu_1914_p2;
wire   [31:0] select_ln31_11_fu_1906_p3;
wire   [31:0] result_2_fu_1920_p3;
wire   [15:0] trunc_ln32_fu_1946_p1;
wire   [15:0] tmp_56_fu_1928_p4;
wire   [0:0] icmp_ln32_fu_1950_p2;
wire   [15:0] add_ln32_fu_1956_p2;
wire   [0:0] tmp_57_fu_1938_p3;
wire   [15:0] select_ln32_fu_1962_p3;
wire   [15:0] ref_tmp_i_0_fu_1970_p3;
reg    ap_ce_reg;
reg   [31:0] data_int_reg;
reg   [15:0] ap_return_int_reg;
wire  signed [2:0] ref_tmp_i_i_fu_1219_p1;
wire   [2:0] ref_tmp_i_i_fu_1219_p3;
wire   [2:0] ref_tmp_i_i_fu_1219_p5;
wire   [2:0] ref_tmp_i_i_fu_1219_p7;
wire  signed [1:0] neg_src_0_i_fu_1547_p1;
wire   [1:0] neg_src_0_i_fu_1547_p3;
wire   [1:0] neg_src_0_i_fu_1547_p5;
wire  signed [1:0] ref_tmp_i_i42_4_fu_1654_p1;
wire   [1:0] ref_tmp_i_i42_4_fu_1654_p3;
wire   [1:0] ref_tmp_i_i42_4_fu_1654_p5;

pedal_top_generic_tanh_float_s grp_generic_tanh_float_s_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t_in(x_assign_reg_1989),
    .ap_return(grp_generic_tanh_float_s_fu_228_ap_return),
    .ap_ce(grp_generic_tanh_float_s_fu_228_ap_ce)
);

pedal_top_fpext_32ns_64_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_1_no_dsp_1_U37(
    .din0(grp_generic_tanh_float_s_fu_228_ap_return),
    .dout(pf_fu_239_p1)
);

pedal_top_mul_32s_28ns_59_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 28 ),
    .dout_WIDTH( 59 ))
mul_32s_28ns_59_1_0_U38(
    .din0(ref_tmp_i_i42_4_reg_2019),
    .din1(mul_ln31_fu_243_p1),
    .dout(mul_ln31_fu_243_p2)
);

pedal_top_mul_48s_50ns_97_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 48 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 97 ))
mul_48s_50ns_97_1_0_U39(
    .din0(shl_ln28_1_fu_355_p3),
    .din1(mul_ln28_1_fu_248_p1),
    .dout(mul_ln28_1_fu_248_p2)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_9_3_32_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_9_3_32_1_0_U40(
    .din0(trunc_ln31_6_fu_971_p1),
    .din1(add_ln31_8_fu_1155_p2),
    .din2(ref_tmp_i_i_fu_1219_p6),
    .din3(32'd0),
    .def(ref_tmp_i_i_fu_1219_p9),
    .sel(ref_tmp_i_i_fu_1219_p10),
    .dout(ref_tmp_i_i_fu_1219_p11)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_7_2_1_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_0_U41(
    .din0(neg_src_0_i_fu_1547_p2),
    .din1(neg_src_0_i_fu_1547_p4),
    .din2(1'd0),
    .def(neg_src_0_i_fu_1547_p7),
    .sel(neg_src_0_i_fu_1547_p8),
    .dout(neg_src_0_i_fu_1547_p9)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_7_2_32_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_0_U42(
    .din0(32'd0),
    .din1(ref_tmp_i_i42_4_fu_1654_p4),
    .din2(ref_tmp_i_i_fu_1219_p11),
    .def(ref_tmp_i_i42_4_fu_1654_p7),
    .sel(ref_tmp_i_i42_4_fu_1654_p8),
    .dout(ref_tmp_i_i42_4_fu_1654_p9)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= ref_tmp_i_0_fu_1970_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_int_reg <= data;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ref_tmp_i_i42_4_reg_2019 <= ref_tmp_i_i42_4_fu_1654_p9;
        tmp_27_reg_1978 <= add_ln28_fu_444_p2[32'd40];
        tmp_37_reg_2009 <= {{bitcast_ln716_fu_853_p1[62:52]}};
        tmp_40_reg_1999 <= bitcast_ln716_fu_853_p1[32'd63];
        trunc_ln31_2_reg_1994 <= trunc_ln31_2_fu_857_p1;
        trunc_ln31_3_reg_2014 <= trunc_ln31_3_fu_879_p1;
        x_2_reg_1984 <= x_2_fu_498_p2;
        x_assign_reg_1989 <= x_assign_fu_845_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = ref_tmp_i_0_fu_1970_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp133))) begin
        grp_generic_tanh_float_s_fu_228_ap_ce = 1'b1;
    end else begin
        grp_generic_tanh_float_s_fu_228_ap_ce = 1'b0;
    end
end

assign LD_fu_837_p1 = pi_assign_fu_825_p5[31:0];

assign Range1_all_ones_2_i_fu_1466_p3 = ((and_ln31_3_fu_1414_p2[0:0] == 1'b1) ? and_ln31_4_fu_1420_p2 : select_ln31_8_fu_1450_p3);

assign Range1_all_zeros_2_i_fu_1474_p3 = ((and_ln31_3_fu_1414_p2[0:0] == 1'b1) ? and_ln31_5_fu_1438_p2 : select_ln31_12_fu_1458_p3);

assign Range2_all_ones_1_i_fu_1406_p3 = ((icmp_ln31_18_fu_1355_p2[0:0] == 1'b1) ? icmp_ln31_19_fu_1386_p2 : xor_ln31_16_fu_1400_p2);

assign add_ln28_fu_444_p2 = (shl_ln28_2_fu_432_p2 + shl_ln28_3_fu_438_p2);

assign add_ln31_10_fu_1285_p2 = (sub_ln31_4_fu_921_p2 + 12'd16);

assign add_ln31_11_fu_1295_p2 = (sub_ln31_4_fu_921_p2 + 12'd17);

assign add_ln31_1_fu_725_p2 = ($signed(sub_ln31_1_fu_607_p2) + $signed(32'd4294967271));

assign add_ln31_2_fu_769_p2 = (cond46_i_i_fu_757_p3 + zext_ln31_3_fu_765_p1);

assign add_ln31_3_fu_811_p2 = (sub_ln31_6_fu_805_p2 + select_ln31_1_fu_797_p3);

assign add_ln31_4_fu_886_p2 = ($signed(zext_ln31_4_fu_883_p1) + $signed(12'd3073));

assign add_ln31_5_fu_937_p2 = ($signed(sub_ln31_4_fu_921_p2) + $signed(12'd4080));

assign add_ln31_6_fu_1032_p2 = ($signed(sub_ln31_4_fu_921_p2) + $signed(12'd4079));

assign add_ln31_7_fu_1069_p2 = ($signed(sub_ln31_4_fu_921_p2) + $signed(12'd4078));

assign add_ln31_8_fu_1155_p2 = (select_ln31_4_fu_1002_p3 + zext_ln31_8_fu_1151_p1);

assign add_ln31_9_fu_1263_p2 = (select_ln31_14_fu_1255_p3 + add_ln31_4_fu_886_p2);

assign add_ln31_fu_613_p2 = ($signed(sub_ln31_1_fu_607_p2) + $signed(32'd4294967272));

assign add_ln32_fu_1956_p2 = (tmp_56_fu_1928_p4 + 16'd1);

assign and_ln28_1_fu_327_p2 = (tmp_fu_253_p3 & or_ln28_1_fu_321_p2);

assign and_ln28_2_fu_488_p2 = (tmp_29_fu_480_p3 & tmp_28_fu_472_p3);

assign and_ln28_3_fu_543_p2 = (xor_ln28_2_fu_515_p2 & or_ln28_4_fu_537_p2);

assign and_ln28_fu_303_p2 = (xor_ln28_fu_297_p2 & or_ln28_fu_291_p2);

assign and_ln31_10_fu_1608_p2 = (xor_ln31_6_fu_1602_p2 & neg_src_0_i_fu_1547_p9);

assign and_ln31_11_fu_1736_p2 = (tmp_51_fu_1696_p3 & or_ln31_5_fu_1730_p2);

assign and_ln31_12_fu_1766_p2 = (xor_ln31_8_fu_1760_p2 & tmp_52_fu_1714_p3);

assign and_ln31_13_fu_1832_p2 = (xor_ln31_9_fu_1826_p2 & icmp_ln31_23_fu_1790_p2);

assign and_ln31_14_fu_1846_p2 = (icmp_ln31_24_fu_1806_p2 & and_ln31_12_fu_1766_p2);

assign and_ln31_15_fu_1882_p2 = (xor_ln31_12_fu_1876_p2 & or_ln31_6_fu_1870_p2);

assign and_ln31_16_fu_1888_p2 = (tmp_54_fu_1752_p3 & select_ln31_10_fu_1838_p3);

assign and_ln31_17_fu_1900_p2 = (xor_ln31_13_fu_1894_p2 & empty_fu_1858_p2);

assign and_ln31_18_fu_1181_p2 = (xor_ln31_2_fu_1175_p2 & icmp_ln31_5_fu_931_p2);

assign and_ln31_19_fu_1203_p2 = (icmp_ln31_9_fu_1026_p2 & icmp_ln31_13_fu_1197_p2);

assign and_ln31_1_fu_1145_p2 = (or_ln31_1_fu_1139_p2 & cond63_i_fu_1056_p3);

assign and_ln31_20_fu_1243_p2 = (tmp_43_fu_1127_p3 & and_ln31_18_fu_1181_p2);

assign and_ln31_21_fu_1534_p2 = (tmp_40_reg_1999 & icmp_ln31_15_fu_1309_p2);

assign and_ln31_22_fu_1573_p2 = (xor_ln31_4_fu_1567_p2 & icmp_ln31_15_fu_1309_p2);

assign and_ln31_23_fu_1634_p2 = (xor_ln31_7_fu_1628_p2 & or_ln31_4_fu_1614_p2);

assign and_ln31_24_fu_1640_p2 = (icmp_ln31_14_fu_1279_p2 & and_ln31_23_fu_1634_p2);

assign and_ln31_25_fu_655_p2 = (select_ln31_fu_577_p3 & lshr_ln31_4_fu_649_p2);

assign and_ln31_26_fu_1109_p2 = (select_ln31_2_fu_909_p3 & lshr_ln31_5_fu_1103_p2);

assign and_ln31_3_fu_1414_p2 = (xor_ln31_15_fu_1323_p2 & icmp_ln31_17_fu_1349_p2);

assign and_ln31_4_fu_1420_p2 = (lD_0_i_fu_1343_p2 & Range2_all_ones_1_i_fu_1406_p3);

assign and_ln31_5_fu_1438_p2 = (xor_ln31_1_fu_1426_p2 & icmp_ln31_20_fu_1432_p2);

assign and_ln31_6_fu_1496_p2 = (or_ln31_fu_1490_p2 & Range2_all_ones_1_i_fu_1406_p3);

assign and_ln31_7_fu_1510_p2 = (carry_1_i_fu_1249_p2 & Range1_all_ones_2_i_fu_1466_p3);

assign and_ln31_8_fu_1590_p2 = (xor_ln31_5_fu_1585_p2 & or_ln31_3_fu_1579_p2);

assign and_ln31_9_fu_1596_p2 = (tmp_47_fu_1301_p3 & deleted_ones_0_i_fu_1528_p2);

assign and_ln31_fu_695_p2 = (xor_ln31_14_fu_681_p2 & tmp_38_fu_687_p3);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp133 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp133 = ~(1'b1 == 1'b1);

assign ashr_ln31_fu_992_p2 = $signed(select_ln31_2_fu_909_p3) >>> zext_ln31_7_fu_988_p1;

assign bitcast_ln716_fu_853_p1 = pf_fu_239_p1;

assign bitcast_ln758_fu_841_p1 = LD_fu_837_p1;

assign carry_1_i_fu_1249_p2 = (xor_ln31_fu_1169_p2 & and_ln31_20_fu_1243_p2);

assign cond189_i_fu_1502_p3 = ((carry_1_i_fu_1249_p2[0:0] == 1'b1) ? and_ln31_6_fu_1496_p2 : Range1_all_ones_2_i_fu_1466_p3);

assign cond46_i_i_fu_757_p3 = ((icmp_ln31_3_fu_719_p2[0:0] == 1'b1) ? lshr_ln31_fu_735_p2 : shl_ln31_fu_751_p2);

assign cond63_i_fu_1056_p3 = ((icmp_ln31_8_fu_1010_p2[0:0] == 1'b1) ? tmp_40_reg_1999 : tmp_42_fu_1042_p3);

assign cond85_i_fu_1121_p2 = (icmp_ln31_12_fu_1115_p2 & icmp_ln31_10_fu_1063_p2);

assign deleted_ones_0_i_fu_1528_p2 = (not_icmp_ln31_1538_fu_1522_p2 | cond189_i_fu_1502_p3);

assign empty_fu_1858_p2 = (xor_ln31_10_fu_1852_p2 & tmp_50_fu_1678_p3);

assign icmp_ln28_1_fu_315_p2 = ((tmp_s_fu_275_p4 != 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_285_p2 = ((tmp_s_fu_275_p4 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_10_fu_1063_p2 = (($signed(sub_ln31_4_fu_921_p2) > $signed(12'd17)) ? 1'b1 : 1'b0);

assign icmp_ln31_11_fu_1075_p2 = (($signed(add_ln31_7_fu_1069_p2) > $signed(12'd53)) ? 1'b1 : 1'b0);

assign icmp_ln31_12_fu_1115_p2 = ((and_ln31_26_fu_1109_p2 != 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_13_fu_1197_p2 = (($signed(tmp_45_fu_1187_p4) < $signed(8'd1)) ? 1'b1 : 1'b0);

assign icmp_ln31_14_fu_1279_p2 = (($signed(tmp_46_fu_1269_p4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln31_15_fu_1309_p2 = (($signed(add_ln31_10_fu_1285_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln31_16_fu_1329_p2 = ((add_ln31_10_fu_1285_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln31_17_fu_1349_p2 = (($signed(add_ln31_11_fu_1295_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln31_18_fu_1355_p2 = ((add_ln31_11_fu_1295_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln31_19_fu_1386_p2 = ((lshr_ln31_2_fu_1374_p2 == lshr_ln31_3_fu_1380_p2) ? 1'b1 : 1'b0);

assign icmp_ln31_1_fu_629_p2 = (($signed(tmp_34_fu_619_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln31_20_fu_1432_p2 = ((lshr_ln31_2_fu_1374_p2 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_21_fu_1444_p2 = ((add_ln31_11_fu_1295_p2 == 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln31_22_fu_1708_p2 = ((trunc_ln31_10_fu_1704_p1 != 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_23_fu_1790_p2 = ((tmp_20_fu_1780_p4 == 10'd1023) ? 1'b1 : 1'b0);

assign icmp_ln31_24_fu_1806_p2 = ((tmp_21_fu_1796_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln31_25_fu_1812_p2 = ((tmp_21_fu_1796_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_2_fu_661_p2 = ((and_ln31_25_fu_655_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_3_fu_719_p2 = (($signed(add_ln31_fu_613_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln31_4_fu_916_p2 = ((trunc_ln31_2_reg_1994 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_5_fu_931_p2 = (($signed(sub_ln31_4_fu_921_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln31_6_fu_965_p2 = ((sub_ln31_4_fu_921_p2 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln31_7_fu_975_p2 = ((select_ln31_3_fu_953_p3 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln31_8_fu_1010_p2 = (($signed(add_ln31_5_fu_937_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln31_9_fu_1026_p2 = ((tmp_41_fu_1016_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_557_p2 = ((x_3_fu_549_p3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_1950_p2 = ((trunc_ln32_fu_1946_p1 != 16'd0) ? 1'b1 : 1'b0);

assign lD_0_i_fu_1343_p2 = (tobool130_i_fu_1335_p3 & icmp_ln31_16_fu_1329_p2);

assign lshr_ln31_1_fu_775_p4 = {{add_ln31_2_fu_769_p2[63:1]}};

assign lshr_ln31_2_fu_1374_p2 = select_ln31_2_fu_909_p3 >> zext_ln31_13_fu_1370_p1;

assign lshr_ln31_3_fu_1380_p2 = 54'd18014398509481983 >> zext_ln31_13_fu_1370_p1;

assign lshr_ln31_4_fu_649_p2 = 32'd4294967295 >> zext_ln31_5_fu_645_p1;

assign lshr_ln31_5_fu_1103_p2 = 54'd18014398509481983 >> zext_ln31_12_fu_1099_p1;

assign lshr_ln31_fu_735_p2 = zext_ln31_fu_715_p1 >> zext_ln31_1_fu_731_p1;

assign mul_ln28_1_fu_248_p1 = 97'd345876453493117;

assign mul_ln31_fu_243_p1 = 59'd109226666;

assign neg_src_0_i_fu_1547_p2 = (tmp_47_fu_1301_p3 & tmp_40_reg_1999);

assign neg_src_0_i_fu_1547_p4 = (1'd1 ^ and_ln31_7_fu_1510_p2);

assign neg_src_0_i_fu_1547_p7 = 'bx;

assign neg_src_0_i_fu_1547_p8 = {{not_icmp_ln31_1538_fu_1522_p2}, {and_ln31_21_fu_1534_p2}};

assign not_icmp_ln31_1538_fu_1522_p2 = (icmp_ln31_15_fu_1309_p2 ^ 1'd1);

assign or_ln28_1_fu_321_p2 = (xor_ln28_1_fu_309_p2 | icmp_ln28_1_fu_315_p2);

assign or_ln28_2_fu_333_p2 = (and_ln28_fu_303_p2 | and_ln28_1_fu_327_p2);

assign or_ln28_3_fu_520_p2 = (xor_ln28_2_fu_515_p2 | tmp_30_fu_507_p3);

assign or_ln28_4_fu_537_p2 = (xor_ln28_4_fu_531_p2 | tmp_30_fu_507_p3);

assign or_ln28_fu_291_p2 = (tmp_23_fu_267_p3 | icmp_ln28_fu_285_p2);

assign or_ln31_1_fu_1139_p2 = (trunc_ln31_9_fu_1135_p1 | cond85_i_fu_1121_p2);

assign or_ln31_2_fu_701_p2 = (phi_ln31_fu_667_p2 | and_ln31_fu_695_p2);

assign or_ln31_3_fu_1579_p2 = (tmp_47_fu_1301_p3 | and_ln31_22_fu_1573_p2);

assign or_ln31_4_fu_1614_p2 = (and_ln31_8_fu_1590_p2 | and_ln31_10_fu_1608_p2);

assign or_ln31_5_fu_1730_p2 = (tmp_53_fu_1722_p3 | icmp_ln31_22_fu_1708_p2);

assign or_ln31_6_fu_1870_p2 = (xor_ln31_11_fu_1864_p2 | tmp_54_fu_1752_p3);

assign or_ln31_7_fu_1914_p2 = (and_ln31_17_fu_1900_p2 | and_ln31_15_fu_1882_p2);

assign or_ln31_fu_1490_p2 = (xor_ln31_1_fu_1426_p2 | tmp_48_fu_1315_p3);

assign or_ln_fu_707_p3 = {{1'd0}, {or_ln31_2_fu_701_p2}};

assign phi_ln31_fu_667_p2 = (icmp_ln31_2_fu_661_p2 & icmp_ln31_1_fu_629_p2);

assign pi_assign_fu_825_p5 = {{zext_ln31_9_fu_785_p1[63:32]}, {tmp_32_fu_817_p3}, {zext_ln31_9_fu_785_p1[22:0]}};

assign ref_tmp_i_0_fu_1970_p3 = ((tmp_57_fu_1938_p3[0:0] == 1'b1) ? select_ln32_fu_1962_p3 : tmp_56_fu_1928_p4);

assign ref_tmp_i_i42_4_fu_1654_p4 = ((and_ln31_8_fu_1590_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign ref_tmp_i_i42_4_fu_1654_p7 = 'bx;

assign ref_tmp_i_i42_4_fu_1654_p8 = {{icmp_ln31_4_fu_916_p2}, {and_ln31_24_fu_1640_p2}};

assign ref_tmp_i_i_fu_1219_p10 = {{{icmp_ln31_6_fu_965_p2}, {and_ln31_18_fu_1181_p2}}, {and_ln31_19_fu_1203_p2}};

assign ref_tmp_i_i_fu_1219_p6 = trunc_ln31_6_fu_971_p1 << zext_ln31_6_fu_961_p1;

assign ref_tmp_i_i_fu_1219_p9 = 'bx;

assign result_1_fu_1746_p2 = (result_fu_1686_p4 + zext_ln31_10_fu_1742_p1);

assign result_2_fu_1920_p3 = ((or_ln31_7_fu_1914_p2[0:0] == 1'b1) ? select_ln31_11_fu_1906_p3 : result_1_fu_1746_p2);

assign result_fu_1686_p4 = {{mul_ln31_fu_243_p2[47:16]}};

assign select_ln28_1_fu_347_p3 = ((or_ln28_2_fu_333_p2[0:0] == 1'b1) ? select_ln28_fu_339_p3 : shl_ln28_fu_261_p2);

assign select_ln28_3_fu_424_p3 = ((tmp_24_fu_374_p3[0:0] == 1'b1) ? sub_ln28_1_fu_418_p2 : sext_ln28_1_fu_402_p1);

assign select_ln28_4_fu_406_p3 = ((tmp_24_fu_374_p3[0:0] == 1'b1) ? tmp_25_fu_382_p4 : tmp_26_fu_392_p4);

assign select_ln28_fu_339_p3 = ((and_ln28_fu_303_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln31_10_fu_1838_p3 = ((and_ln31_12_fu_1766_p2[0:0] == 1'b1) ? and_ln31_13_fu_1832_p2 : icmp_ln31_24_fu_1806_p2);

assign select_ln31_11_fu_1906_p3 = ((and_ln31_15_fu_1882_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln31_12_fu_1458_p3 = ((icmp_ln31_21_fu_1444_p2[0:0] == 1'b1) ? xor_ln31_1_fu_1426_p2 : xor_ln31_15_fu_1323_p2);

assign select_ln31_13_fu_1091_p3 = ((icmp_ln31_11_fu_1075_p2[0:0] == 1'b1) ? 6'd0 : sub_ln31_8_fu_1085_p2);

assign select_ln31_14_fu_1255_p3 = ((icmp_ln31_5_fu_931_p2[0:0] == 1'b1) ? 12'd2 : 12'd1);

assign select_ln31_1_fu_797_p3 = ((tmp_39_fu_789_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln31_2_fu_909_p3 = ((tmp_40_reg_1999[0:0] == 1'b1) ? sub_ln31_3_fu_903_p2 : zext_ln31_11_fu_899_p1);

assign select_ln31_3_fu_953_p3 = ((icmp_ln31_5_fu_931_p2[0:0] == 1'b1) ? trunc_ln31_5_fu_943_p1 : sub_ln31_5_fu_947_p2);

assign select_ln31_4_fu_1002_p3 = ((icmp_ln31_7_fu_975_p2[0:0] == 1'b1) ? trunc_ln31_7_fu_998_p1 : select_ln31_5_fu_981_p3);

assign select_ln31_5_fu_981_p3 = ((tmp_40_reg_1999[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln31_6_fu_1482_p3 = ((carry_1_i_fu_1249_p2[0:0] == 1'b1) ? Range1_all_ones_2_i_fu_1466_p3 : Range1_all_zeros_2_i_fu_1474_p3);

assign select_ln31_8_fu_1450_p3 = ((icmp_ln31_21_fu_1444_p2[0:0] == 1'b1) ? lD_0_i_fu_1343_p2 : xor_ln31_15_fu_1323_p2);

assign select_ln31_9_fu_1818_p3 = ((and_ln31_12_fu_1766_p2[0:0] == 1'b1) ? icmp_ln31_24_fu_1806_p2 : icmp_ln31_25_fu_1812_p2);

assign select_ln31_fu_577_p3 = ((tmp_33_fu_563_p3[0:0] == 1'b1) ? sub_ln31_fu_571_p2 : x_3_fu_549_p3);

assign select_ln32_fu_1962_p3 = ((icmp_ln32_fu_1950_p2[0:0] == 1'b1) ? add_ln32_fu_1956_p2 : tmp_56_fu_1928_p4);

assign sext_ln28_1_fu_402_p1 = tmp_26_fu_392_p4;

assign sext_ln28_2_fu_414_p1 = $signed(select_ln28_4_fu_406_p3);

assign sext_ln28_3_fu_468_p1 = $signed(x_fu_458_p4);

assign sext_ln28_4_fu_504_p1 = $signed(x_2_reg_1984);

assign sext_ln31_1_fu_1291_p1 = add_ln31_10_fu_1285_p2;

assign sext_ln31_2_fu_1366_p1 = add_ln31_11_fu_1295_p2;

assign sext_ln31_fu_1038_p1 = $signed(add_ln31_6_fu_1032_p2);

assign shl_ln28_1_fu_355_p3 = {{select_ln28_1_fu_347_p3}, {16'd0}};

assign shl_ln28_2_fu_432_p2 = select_ln28_3_fu_424_p3 << 41'd17;

assign shl_ln28_3_fu_438_p2 = select_ln28_3_fu_424_p3 << 41'd15;

assign shl_ln28_fu_261_p2 = data_int_reg << 32'd16;

assign shl_ln31_fu_751_p2 = zext_ln31_fu_715_p1 << zext_ln31_2_fu_747_p1;

assign sub_ln28_1_fu_418_p2 = ($signed(41'd0) - $signed(sext_ln28_2_fu_414_p1));

assign sub_ln28_fu_368_p2 = (97'd0 - mul_ln28_1_fu_248_p2);

assign sub_ln31_1_fu_607_p2 = (32'd32 - tmp_31_fu_595_p3);

assign sub_ln31_2_fu_741_p2 = (32'd25 - sub_ln31_1_fu_607_p2);

assign sub_ln31_3_fu_903_p2 = (54'd0 - zext_ln31_11_fu_899_p1);

assign sub_ln31_4_fu_921_p2 = (12'd1075 - zext_ln31_4_fu_883_p1);

assign sub_ln31_5_fu_947_p2 = (11'd16 - trunc_ln31_4_fu_927_p1);

assign sub_ln31_6_fu_805_p2 = (8'd16 - trunc_ln31_fu_603_p1);

assign sub_ln31_7_fu_639_p2 = ($signed(5'd25) - $signed(trunc_ln31_1_fu_635_p1));

assign sub_ln31_8_fu_1085_p2 = ($signed(6'd53) - $signed(trunc_ln31_8_fu_1081_p1));

assign sub_ln31_fu_571_p2 = (32'd0 - x_3_fu_549_p3);

assign tmp_20_fu_1780_p4 = {{mul_ln31_fu_243_p2[58:49]}};

assign tmp_21_fu_1796_p4 = {{mul_ln31_fu_243_p2[58:48]}};

integer ap_tvar_int_0;

always @ (select_ln31_fu_577_p3) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            tmp_22_fu_585_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_22_fu_585_p4[ap_tvar_int_0] = select_ln31_fu_577_p3[31 - ap_tvar_int_0];
        end
    end
end

assign tmp_23_fu_267_p3 = data_int_reg[32'd15];

assign tmp_24_fu_374_p3 = select_ln28_1_fu_347_p3[32'd31];

assign tmp_25_fu_382_p4 = {{sub_ln28_fu_368_p2[96:75]}};

assign tmp_26_fu_392_p4 = {{mul_ln28_1_fu_248_p2[96:75]}};

assign tmp_28_fu_472_p3 = add_ln28_fu_444_p2[32'd15];

assign tmp_29_fu_480_p3 = add_ln28_fu_444_p2[32'd16];

assign tmp_30_fu_507_p3 = sext_ln28_4_fu_504_p1[32'd31];


always @ (tmp_22_fu_585_p4) begin
    if (tmp_22_fu_585_p4[0] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd0;
    end else if (tmp_22_fu_585_p4[1] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd1;
    end else if (tmp_22_fu_585_p4[2] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd2;
    end else if (tmp_22_fu_585_p4[3] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd3;
    end else if (tmp_22_fu_585_p4[4] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd4;
    end else if (tmp_22_fu_585_p4[5] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd5;
    end else if (tmp_22_fu_585_p4[6] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd6;
    end else if (tmp_22_fu_585_p4[7] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd7;
    end else if (tmp_22_fu_585_p4[8] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd8;
    end else if (tmp_22_fu_585_p4[9] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd9;
    end else if (tmp_22_fu_585_p4[10] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd10;
    end else if (tmp_22_fu_585_p4[11] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd11;
    end else if (tmp_22_fu_585_p4[12] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd12;
    end else if (tmp_22_fu_585_p4[13] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd13;
    end else if (tmp_22_fu_585_p4[14] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd14;
    end else if (tmp_22_fu_585_p4[15] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd15;
    end else if (tmp_22_fu_585_p4[16] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd16;
    end else if (tmp_22_fu_585_p4[17] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd17;
    end else if (tmp_22_fu_585_p4[18] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd18;
    end else if (tmp_22_fu_585_p4[19] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd19;
    end else if (tmp_22_fu_585_p4[20] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd20;
    end else if (tmp_22_fu_585_p4[21] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd21;
    end else if (tmp_22_fu_585_p4[22] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd22;
    end else if (tmp_22_fu_585_p4[23] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd23;
    end else if (tmp_22_fu_585_p4[24] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd24;
    end else if (tmp_22_fu_585_p4[25] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd25;
    end else if (tmp_22_fu_585_p4[26] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd26;
    end else if (tmp_22_fu_585_p4[27] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd27;
    end else if (tmp_22_fu_585_p4[28] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd28;
    end else if (tmp_22_fu_585_p4[29] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd29;
    end else if (tmp_22_fu_585_p4[30] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd30;
    end else if (tmp_22_fu_585_p4[31] == 1'b1) begin
        tmp_31_fu_595_p3 = 32'd31;
    end else begin
        tmp_31_fu_595_p3 = 32'd32;
    end
end

assign tmp_32_fu_817_p3 = {{tmp_33_fu_563_p3}, {add_ln31_3_fu_811_p2}};

assign tmp_33_fu_563_p3 = x_3_fu_549_p3[32'd31];

assign tmp_34_fu_619_p4 = {{add_ln31_fu_613_p2[31:1]}};

assign tmp_35_fu_673_p3 = add_ln31_fu_613_p2[32'd31];

assign tmp_38_fu_687_p3 = select_ln31_fu_577_p3[add_ln31_fu_613_p2];

assign tmp_39_fu_789_p3 = add_ln31_2_fu_769_p2[32'd25];

assign tmp_41_fu_1016_p4 = {{select_ln31_3_fu_953_p3[10:5]}};

assign tmp_42_fu_1042_p3 = select_ln31_2_fu_909_p3[sext_ln31_fu_1038_p1];

assign tmp_43_fu_1127_p3 = select_ln31_4_fu_1002_p3[32'd31];

assign tmp_44_fu_1161_p3 = add_ln31_8_fu_1155_p2[32'd31];

assign tmp_45_fu_1187_p4 = {{sub_ln31_4_fu_921_p2[11:4]}};

assign tmp_46_fu_1269_p4 = {{add_ln31_9_fu_1263_p2[11:4]}};

assign tmp_47_fu_1301_p3 = ref_tmp_i_i_fu_1219_p11[32'd31];

assign tmp_48_fu_1315_p3 = add_ln31_10_fu_1285_p2[32'd11];

assign tmp_49_fu_1392_p3 = add_ln31_11_fu_1295_p2[32'd11];

assign tmp_50_fu_1678_p3 = mul_ln31_fu_243_p2[32'd58];

assign tmp_51_fu_1696_p3 = mul_ln31_fu_243_p2[32'd15];

assign tmp_52_fu_1714_p3 = mul_ln31_fu_243_p2[32'd47];

assign tmp_53_fu_1722_p3 = mul_ln31_fu_243_p2[32'd16];

assign tmp_54_fu_1752_p3 = result_1_fu_1746_p2[32'd31];

assign tmp_55_fu_1772_p3 = mul_ln31_fu_243_p2[32'd48];

assign tmp_56_fu_1928_p4 = {{result_2_fu_1920_p3[31:16]}};

assign tmp_57_fu_1938_p3 = result_2_fu_1920_p3[32'd31];

assign tmp_fu_253_p3 = data_int_reg[32'd31];

assign tmp_s_fu_275_p4 = {{data_int_reg[31:16]}};

assign tobool130_i_fu_1335_p3 = select_ln31_2_fu_909_p3[sext_ln31_1_fu_1291_p1];

assign trunc_ln31_10_fu_1704_p1 = mul_ln31_fu_243_p2[14:0];

assign trunc_ln31_1_fu_635_p1 = sub_ln31_1_fu_607_p2[4:0];

assign trunc_ln31_2_fu_857_p1 = bitcast_ln716_fu_853_p1[62:0];

assign trunc_ln31_3_fu_879_p1 = bitcast_ln716_fu_853_p1[51:0];

assign trunc_ln31_4_fu_927_p1 = sub_ln31_4_fu_921_p2[10:0];

assign trunc_ln31_5_fu_943_p1 = add_ln31_5_fu_937_p2[10:0];

assign trunc_ln31_6_fu_971_p1 = select_ln31_2_fu_909_p3[31:0];

assign trunc_ln31_7_fu_998_p1 = ashr_ln31_fu_992_p2[31:0];

assign trunc_ln31_8_fu_1081_p1 = add_ln31_7_fu_1069_p2[5:0];

assign trunc_ln31_9_fu_1135_p1 = select_ln31_4_fu_1002_p3[0:0];

assign trunc_ln31_fu_603_p1 = tmp_31_fu_595_p3[7:0];

assign trunc_ln32_fu_1946_p1 = result_2_fu_1920_p3[15:0];

assign x_2_fu_498_p2 = ($signed(sext_ln28_3_fu_468_p1) + $signed(zext_ln28_fu_494_p1));

assign x_3_fu_549_p3 = ((and_ln28_3_fu_543_p2[0:0] == 1'b1) ? 32'd2147483647 : sext_ln28_4_fu_504_p1);

assign x_assign_fu_845_p3 = ((icmp_ln31_fu_557_p2[0:0] == 1'b1) ? 32'd0 : bitcast_ln758_fu_841_p1);

assign x_fu_458_p4 = {{add_ln28_fu_444_p2[40:16]}};

assign xor_ln28_1_fu_309_p2 = (tmp_23_fu_267_p3 ^ 1'd1);

assign xor_ln28_2_fu_515_p2 = (tmp_27_reg_1978 ^ 1'd1);

assign xor_ln28_3_fu_526_p2 = (tmp_27_reg_1978 ^ or_ln28_3_fu_520_p2);

assign xor_ln28_4_fu_531_p2 = (xor_ln28_3_fu_526_p2 ^ 1'd1);

assign xor_ln28_fu_297_p2 = (tmp_fu_253_p3 ^ 1'd1);

assign xor_ln31_10_fu_1852_p2 = (1'd1 ^ and_ln31_14_fu_1846_p2);

assign xor_ln31_11_fu_1864_p2 = (select_ln31_9_fu_1818_p3 ^ 1'd1);

assign xor_ln31_12_fu_1876_p2 = (tmp_50_fu_1678_p3 ^ 1'd1);

assign xor_ln31_13_fu_1894_p2 = (1'd1 ^ and_ln31_16_fu_1888_p2);

assign xor_ln31_14_fu_681_p2 = (tmp_35_fu_673_p3 ^ 1'd1);

assign xor_ln31_15_fu_1323_p2 = (tmp_48_fu_1315_p3 ^ 1'd1);

assign xor_ln31_16_fu_1400_p2 = (tmp_49_fu_1392_p3 ^ 1'd1);

assign xor_ln31_1_fu_1426_p2 = (lD_0_i_fu_1343_p2 ^ 1'd1);

assign xor_ln31_2_fu_1175_p2 = (icmp_ln31_6_fu_965_p2 ^ 1'd1);

assign xor_ln31_4_fu_1567_p2 = (select_ln31_6_fu_1482_p3 ^ 1'd1);

assign xor_ln31_5_fu_1585_p2 = (tmp_40_reg_1999 ^ 1'd1);

assign xor_ln31_6_fu_1602_p2 = (1'd1 ^ and_ln31_9_fu_1596_p2);

assign xor_ln31_7_fu_1628_p2 = (icmp_ln31_4_fu_916_p2 ^ 1'd1);

assign xor_ln31_8_fu_1760_p2 = (tmp_54_fu_1752_p3 ^ 1'd1);

assign xor_ln31_9_fu_1826_p2 = (tmp_55_fu_1772_p3 ^ 1'd1);

assign xor_ln31_fu_1169_p2 = (tmp_44_fu_1161_p3 ^ 1'd1);

assign zext_ln28_fu_494_p1 = and_ln28_2_fu_488_p2;

assign zext_ln31_10_fu_1742_p1 = and_ln31_11_fu_1736_p2;

assign zext_ln31_11_fu_899_p1 = zext_ln31_5_cast_fu_892_p3;

assign zext_ln31_12_fu_1099_p1 = select_ln31_13_fu_1091_p3;

assign zext_ln31_13_fu_1370_p1 = $unsigned(sext_ln31_2_fu_1366_p1);

assign zext_ln31_1_fu_731_p1 = add_ln31_1_fu_725_p2;

assign zext_ln31_2_fu_747_p1 = sub_ln31_2_fu_741_p2;

assign zext_ln31_3_fu_765_p1 = or_ln_fu_707_p3;

assign zext_ln31_4_fu_883_p1 = tmp_37_reg_2009;

assign zext_ln31_5_cast_fu_892_p3 = {{1'd1}, {trunc_ln31_3_reg_2014}};

assign zext_ln31_5_fu_645_p1 = sub_ln31_7_fu_639_p2;

assign zext_ln31_6_fu_961_p1 = select_ln31_3_fu_953_p3;

assign zext_ln31_7_fu_988_p1 = select_ln31_3_fu_953_p3;

assign zext_ln31_8_fu_1151_p1 = and_ln31_1_fu_1145_p2;

assign zext_ln31_9_fu_785_p1 = lshr_ln31_1_fu_775_p4;

assign zext_ln31_fu_715_p1 = select_ln31_fu_577_p3;

endmodule //pedal_top_soft_clipping_distortion
