// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pedal_top_generic_tanh_float_s (
        ap_clk,
        ap_rst,
        t_in,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] t_in;
output  [31:0] ap_return;
input   ap_ce;

reg   [31:0] expx_reg_58;
reg   [31:0] expx_reg_58_pp0_iter20_reg;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] expx_reg_58_pp0_iter21_reg;
wire   [31:0] grp_fu_128_p2;
reg   [31:0] reg_149;
reg   [0:0] icmp_ln36_reg_392;
reg   [0:0] icmp_ln36_reg_392_pp0_iter26_reg;
reg   [0:0] icmp_ln45_reg_396;
reg   [0:0] icmp_ln45_reg_396_pp0_iter26_reg;
reg   [0:0] and_ln46_reg_400;
reg   [0:0] and_ln46_reg_400_pp0_iter26_reg;
reg   [0:0] tmp_30_reg_409;
reg   [0:0] tmp_30_reg_409_pp0_iter26_reg;
reg   [0:0] icmp_ln54_reg_413;
reg   [0:0] icmp_ln54_reg_413_pp0_iter26_reg;
reg    ap_predicate_pred47_state29;
reg    ap_predicate_pred55_state29;
reg   [0:0] din_sign_reg_367;
reg   [0:0] din_sign_reg_367_pp0_iter1_reg;
reg   [0:0] din_sign_reg_367_pp0_iter2_reg;
reg   [0:0] din_sign_reg_367_pp0_iter3_reg;
reg   [0:0] din_sign_reg_367_pp0_iter4_reg;
reg   [0:0] din_sign_reg_367_pp0_iter5_reg;
reg   [0:0] din_sign_reg_367_pp0_iter6_reg;
reg   [0:0] din_sign_reg_367_pp0_iter7_reg;
reg   [0:0] din_sign_reg_367_pp0_iter8_reg;
reg   [0:0] din_sign_reg_367_pp0_iter9_reg;
reg   [0:0] din_sign_reg_367_pp0_iter10_reg;
reg   [0:0] din_sign_reg_367_pp0_iter11_reg;
reg   [0:0] din_sign_reg_367_pp0_iter12_reg;
reg   [0:0] din_sign_reg_367_pp0_iter13_reg;
reg   [0:0] din_sign_reg_367_pp0_iter14_reg;
reg   [0:0] din_sign_reg_367_pp0_iter15_reg;
reg   [0:0] din_sign_reg_367_pp0_iter16_reg;
reg   [0:0] din_sign_reg_367_pp0_iter17_reg;
reg   [0:0] din_sign_reg_367_pp0_iter18_reg;
reg   [0:0] din_sign_reg_367_pp0_iter19_reg;
reg   [0:0] din_sign_reg_367_pp0_iter20_reg;
reg   [0:0] din_sign_reg_367_pp0_iter21_reg;
reg   [0:0] din_sign_reg_367_pp0_iter22_reg;
reg   [0:0] din_sign_reg_367_pp0_iter23_reg;
reg   [0:0] din_sign_reg_367_pp0_iter24_reg;
reg   [0:0] din_sign_reg_367_pp0_iter25_reg;
reg   [0:0] din_sign_reg_367_pp0_iter26_reg;
reg   [0:0] din_sign_reg_367_pp0_iter27_reg;
reg   [0:0] din_sign_reg_367_pp0_iter28_reg;
reg   [0:0] din_sign_reg_367_pp0_iter29_reg;
reg   [0:0] din_sign_reg_367_pp0_iter30_reg;
reg   [0:0] din_sign_reg_367_pp0_iter31_reg;
wire   [7:0] din_exp_fu_167_p4;
reg   [7:0] din_exp_reg_372;
wire   [30:0] trunc_ln313_fu_181_p1;
reg   [30:0] trunc_ln313_reg_377;
wire   [31:0] abst_in_fu_193_p1;
reg   [31:0] abst_in_reg_382;
reg   [31:0] abst_in_reg_382_pp0_iter1_reg;
reg   [31:0] abst_in_reg_382_pp0_iter2_reg;
wire   [0:0] icmp_ln36_fu_199_p2;
reg   [0:0] icmp_ln36_reg_392_pp0_iter1_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter2_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter3_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter4_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter5_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter6_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter7_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter8_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter9_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter10_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter11_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter12_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter13_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter14_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter15_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter16_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter17_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter18_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter19_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter20_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter21_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter22_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter23_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter24_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter25_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter27_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter28_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter29_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter30_reg;
reg   [0:0] icmp_ln36_reg_392_pp0_iter31_reg;
wire   [0:0] icmp_ln45_fu_205_p2;
reg   [0:0] icmp_ln45_reg_396_pp0_iter1_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter2_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter3_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter4_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter5_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter6_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter7_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter8_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter9_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter10_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter11_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter12_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter13_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter14_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter15_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter16_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter17_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter18_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter19_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter20_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter21_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter22_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter23_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter24_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter25_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter27_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter28_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter29_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter30_reg;
reg   [0:0] icmp_ln45_reg_396_pp0_iter31_reg;
wire   [0:0] and_ln46_fu_223_p2;
reg   [0:0] and_ln46_reg_400_pp0_iter1_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter2_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter3_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter4_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter5_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter6_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter7_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter8_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter9_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter10_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter11_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter12_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter13_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter14_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter15_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter16_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter17_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter18_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter19_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter20_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter21_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter22_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter23_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter24_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter25_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter27_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter28_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter29_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter30_reg;
reg   [0:0] and_ln46_reg_400_pp0_iter31_reg;
wire   [0:0] icmp_ln38_fu_229_p2;
reg   [0:0] icmp_ln38_reg_404;
reg   [0:0] icmp_ln38_reg_404_pp0_iter1_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter2_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter3_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter4_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter5_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter6_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter7_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter8_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter9_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter10_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter11_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter12_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter13_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter14_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter15_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter16_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter17_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter18_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter19_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter20_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter21_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter22_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter23_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter24_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter25_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter26_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter27_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter28_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter29_reg;
reg   [0:0] icmp_ln38_reg_404_pp0_iter30_reg;
wire   [0:0] grp_fu_139_p2;
reg   [0:0] tmp_30_reg_409_pp0_iter2_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter3_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter4_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter5_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter6_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter7_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter8_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter9_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter10_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter11_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter12_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter13_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter14_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter15_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter16_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter17_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter18_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter19_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter20_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter21_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter22_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter23_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter24_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter25_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter27_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter28_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter29_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter30_reg;
reg   [0:0] tmp_30_reg_409_pp0_iter31_reg;
wire   [0:0] icmp_ln54_fu_235_p2;
reg   [0:0] icmp_ln54_reg_413_pp0_iter2_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter3_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter4_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter5_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter6_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter7_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter8_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter9_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter10_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter11_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter12_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter13_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter14_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter15_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter16_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter17_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter18_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter19_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter20_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter21_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter22_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter23_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter24_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter25_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter27_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter28_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter29_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter30_reg;
reg   [0:0] icmp_ln54_reg_413_pp0_iter31_reg;
wire   [31:0] grp_fu_100_p2;
reg   [31:0] add_reg_423;
wire   [31:0] grp_fu_105_p2;
reg   [31:0] x_reg_428;
wire   [31:0] grp_fu_109_p2;
reg   [31:0] x_4_reg_433;
wire   [31:0] x_6_fu_252_p3;
wire   [0:0] icmp_ln9_fu_272_p2;
reg   [0:0] icmp_ln9_reg_443;
reg   [0:0] icmp_ln9_reg_443_pp0_iter5_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter6_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter7_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter8_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter9_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter10_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter11_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter12_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter13_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter14_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter15_reg;
reg   [0:0] icmp_ln9_reg_443_pp0_iter16_reg;
wire   [0:0] icmp_ln10_fu_278_p2;
reg   [0:0] icmp_ln10_reg_447;
reg   [0:0] icmp_ln10_reg_447_pp0_iter5_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter6_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter7_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter8_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter9_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter10_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter11_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter12_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter13_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter14_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter15_reg;
reg   [0:0] icmp_ln10_reg_447_pp0_iter16_reg;
wire   [63:0] xd_fu_136_p1;
reg   [63:0] xd_reg_451;
wire   [31:0] grp_fu_124_p2;
wire   [63:0] grp_exp_generic_double_s_fu_89_ap_return;
reg   [63:0] tmp_s_reg_461;
wire   [63:0] grp_fu_144_p2;
reg   [63:0] sub_i_reg_466;
wire   [31:0] grp_fu_133_p1;
wire   [31:0] grp_fu_113_p2;
reg   [31:0] add2_reg_476;
wire   [31:0] bitcast_ln66_1_fu_314_p1;
wire   [31:0] grp_fu_119_p2;
reg   [31:0] resultf_2_reg_486;
wire   [31:0] select_ln38_fu_319_p3;
reg    grp_exp_generic_double_s_fu_89_ap_ce;
reg    ap_predicate_op78_call_state6;
wire    ap_block_pp0_stage0_11001_ignoreCallOp78;
wire   [31:0] ap_phi_reg_pp0_iter0_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter1_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter2_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter3_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter4_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter5_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter6_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter7_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter8_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter9_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter10_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter11_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter12_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter13_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter14_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter15_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter16_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter17_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter18_expx_reg_58;
reg   [31:0] ap_phi_reg_pp0_iter19_expx_reg_58;
reg    ap_predicate_pred536_state19;
reg   [31:0] ap_phi_mux_resultf_3_phi_fu_76_p10;
wire   [31:0] ap_phi_reg_pp0_iter0_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter1_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter2_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter3_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter4_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter5_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter6_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter7_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter8_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter9_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter10_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter11_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter12_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter13_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter14_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter15_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter16_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter17_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter18_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter19_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter20_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter21_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter22_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter23_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter24_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter25_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter26_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter27_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter28_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter29_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter30_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter31_resultf_3_reg_72;
reg   [31:0] ap_phi_reg_pp0_iter32_resultf_3_reg_72;
wire    ap_block_pp0_stage0_ignoreCallOp78;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_105_p0;
reg   [31:0] grp_fu_128_p0;
reg    ap_predicate_pred666_state23;
reg    ap_predicate_pred671_state23;
wire   [31:0] data_fu_155_p1;
wire   [31:0] t_fu_185_p3;
wire   [22:0] din_sig_fu_177_p1;
wire   [0:0] icmp_ln46_fu_211_p2;
wire   [0:0] icmp_ln46_1_fu_217_p2;
wire   [31:0] or_ln_fu_240_p3;
wire   [31:0] data_4_fu_258_p1;
wire   [7:0] xs_exp_1_fu_262_p4;
wire   [31:0] bitcast_ln66_fu_284_p1;
wire   [0:0] bit_sel_fu_288_p3;
wire   [0:0] xor_ln66_fu_296_p2;
wire   [30:0] trunc_ln66_fu_302_p1;
wire   [31:0] xor_ln_fu_306_p3;
wire   [31:0] bitcast_ln83_fu_326_p1;
wire   [0:0] bit_sel1_fu_330_p3;
wire   [0:0] xor_ln83_fu_338_p2;
wire   [30:0] trunc_ln83_fu_344_p1;
wire   [31:0] xor_ln1_fu_348_p3;
wire   [31:0] bitcast_ln83_1_fu_356_p1;
reg    grp_fu_100_ce;
reg    grp_fu_105_ce;
reg    grp_fu_109_ce;
reg    grp_fu_113_ce;
reg    grp_fu_119_ce;
reg    grp_fu_124_ce;
reg    grp_fu_128_ce;
reg    grp_fu_133_ce;
reg    grp_fu_139_ce;
reg    ap_predicate_op50_fcmp_state1;
wire    ap_block_pp0_stage0_00001;
reg    grp_fu_144_ce;
reg   [31:0] t_in_int_reg;
reg    ap_condition_633;
reg    ap_condition_556;
reg    ap_condition_561;
reg    ap_condition_601;
wire    ap_ce_reg;

pedal_top_exp_generic_double_s grp_exp_generic_double_s_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(xd_reg_451),
    .ap_return(grp_exp_generic_double_s_fu_89_ap_return),
    .ap_ce(grp_exp_generic_double_s_fu_89_ap_ce)
);

pedal_top_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_fu_193_p1),
    .din1(32'd1065353216),
    .ce(grp_fu_100_ce),
    .dout(grp_fu_100_p2)
);

pedal_top_fsub_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_3_full_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_105_p0),
    .din1(abst_in_reg_382),
    .ce(grp_fu_105_ce),
    .dout(grp_fu_105_p2)
);

pedal_top_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_reg_382),
    .din1(abst_in_reg_382),
    .ce(grp_fu_109_ce),
    .dout(grp_fu_109_p2)
);

pedal_top_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_reg_pp0_iter19_expx_reg_58),
    .din1(32'd1073741824),
    .ce(grp_fu_113_ce),
    .dout(grp_fu_113_p2)
);

pedal_top_fsub_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_3_full_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1065353216),
    .din1(reg_149),
    .ce(grp_fu_119_ce),
    .dout(grp_fu_119_p2)
);

pedal_top_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_reg_382_pp0_iter2_reg),
    .din1(add_reg_423),
    .ce(grp_fu_124_ce),
    .dout(grp_fu_124_p2)
);

pedal_top_fdiv_32ns_32ns_32_7_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_7_no_dsp_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_128_p0),
    .din1(add2_reg_476),
    .ce(grp_fu_128_ce),
    .dout(grp_fu_128_p2)
);

pedal_top_fptrunc_64ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
fptrunc_64ns_32_2_no_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_i_reg_466),
    .ce(grp_fu_133_ce),
    .dout(grp_fu_133_p1)
);

pedal_top_fpext_32ns_64_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_1_no_dsp_1_U25(
    .din0(x_6_fu_252_p3),
    .dout(xd_fu_136_p1)
);

pedal_top_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(abst_in_fu_193_p1),
    .din1(32'd1102053376),
    .ce(grp_fu_139_ce),
    .opcode(5'd4),
    .dout(grp_fu_139_p2)
);

pedal_top_dadd_64ns_64ns_64_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_4_full_dsp_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_reg_461),
    .din1(64'd13830554455654793216),
    .ce(grp_fu_144_ce),
    .dout(grp_fu_144_p2)
);

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_predicate_pred536_state19 == 1'b1)) begin
            ap_phi_reg_pp0_iter19_expx_reg_58 <= grp_fu_133_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter19_expx_reg_58 <= ap_phi_reg_pp0_iter18_expx_reg_58;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_predicate_pred55_state29 == 1'b1)) begin
            ap_phi_reg_pp0_iter29_resultf_3_reg_72 <= grp_fu_128_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter29_resultf_3_reg_72 <= ap_phi_reg_pp0_iter28_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_633)) begin
            ap_phi_reg_pp0_iter2_resultf_3_reg_72 <= 32'd1065353216;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_resultf_3_reg_72 <= ap_phi_reg_pp0_iter1_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((icmp_ln36_reg_392_pp0_iter30_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter32_resultf_3_reg_72 <= select_ln38_fu_319_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter32_resultf_3_reg_72 <= ap_phi_reg_pp0_iter31_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_561)) begin
            ap_phi_reg_pp0_iter5_expx_reg_58 <= x_6_fu_252_p3;
        end else if ((1'b1 == ap_condition_556)) begin
            ap_phi_reg_pp0_iter5_expx_reg_58 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_expx_reg_58 <= ap_phi_reg_pp0_iter4_expx_reg_58;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((1'b1 == ap_condition_601)) begin
            ap_phi_reg_pp0_iter5_resultf_3_reg_72 <= grp_fu_124_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_resultf_3_reg_72 <= ap_phi_reg_pp0_iter4_resultf_3_reg_72;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        abst_in_reg_382[30 : 0] <= abst_in_fu_193_p1[30 : 0];
        abst_in_reg_382_pp0_iter1_reg[30 : 0] <= abst_in_reg_382[30 : 0];
        abst_in_reg_382_pp0_iter2_reg[30 : 0] <= abst_in_reg_382_pp0_iter1_reg[30 : 0];
        add2_reg_476 <= grp_fu_113_p2;
        add_reg_423 <= grp_fu_100_p2;
        and_ln46_reg_400 <= and_ln46_fu_223_p2;
        and_ln46_reg_400_pp0_iter10_reg <= and_ln46_reg_400_pp0_iter9_reg;
        and_ln46_reg_400_pp0_iter11_reg <= and_ln46_reg_400_pp0_iter10_reg;
        and_ln46_reg_400_pp0_iter12_reg <= and_ln46_reg_400_pp0_iter11_reg;
        and_ln46_reg_400_pp0_iter13_reg <= and_ln46_reg_400_pp0_iter12_reg;
        and_ln46_reg_400_pp0_iter14_reg <= and_ln46_reg_400_pp0_iter13_reg;
        and_ln46_reg_400_pp0_iter15_reg <= and_ln46_reg_400_pp0_iter14_reg;
        and_ln46_reg_400_pp0_iter16_reg <= and_ln46_reg_400_pp0_iter15_reg;
        and_ln46_reg_400_pp0_iter17_reg <= and_ln46_reg_400_pp0_iter16_reg;
        and_ln46_reg_400_pp0_iter18_reg <= and_ln46_reg_400_pp0_iter17_reg;
        and_ln46_reg_400_pp0_iter19_reg <= and_ln46_reg_400_pp0_iter18_reg;
        and_ln46_reg_400_pp0_iter1_reg <= and_ln46_reg_400;
        and_ln46_reg_400_pp0_iter20_reg <= and_ln46_reg_400_pp0_iter19_reg;
        and_ln46_reg_400_pp0_iter21_reg <= and_ln46_reg_400_pp0_iter20_reg;
        and_ln46_reg_400_pp0_iter22_reg <= and_ln46_reg_400_pp0_iter21_reg;
        and_ln46_reg_400_pp0_iter23_reg <= and_ln46_reg_400_pp0_iter22_reg;
        and_ln46_reg_400_pp0_iter24_reg <= and_ln46_reg_400_pp0_iter23_reg;
        and_ln46_reg_400_pp0_iter25_reg <= and_ln46_reg_400_pp0_iter24_reg;
        and_ln46_reg_400_pp0_iter26_reg <= and_ln46_reg_400_pp0_iter25_reg;
        and_ln46_reg_400_pp0_iter27_reg <= and_ln46_reg_400_pp0_iter26_reg;
        and_ln46_reg_400_pp0_iter28_reg <= and_ln46_reg_400_pp0_iter27_reg;
        and_ln46_reg_400_pp0_iter29_reg <= and_ln46_reg_400_pp0_iter28_reg;
        and_ln46_reg_400_pp0_iter2_reg <= and_ln46_reg_400_pp0_iter1_reg;
        and_ln46_reg_400_pp0_iter30_reg <= and_ln46_reg_400_pp0_iter29_reg;
        and_ln46_reg_400_pp0_iter31_reg <= and_ln46_reg_400_pp0_iter30_reg;
        and_ln46_reg_400_pp0_iter3_reg <= and_ln46_reg_400_pp0_iter2_reg;
        and_ln46_reg_400_pp0_iter4_reg <= and_ln46_reg_400_pp0_iter3_reg;
        and_ln46_reg_400_pp0_iter5_reg <= and_ln46_reg_400_pp0_iter4_reg;
        and_ln46_reg_400_pp0_iter6_reg <= and_ln46_reg_400_pp0_iter5_reg;
        and_ln46_reg_400_pp0_iter7_reg <= and_ln46_reg_400_pp0_iter6_reg;
        and_ln46_reg_400_pp0_iter8_reg <= and_ln46_reg_400_pp0_iter7_reg;
        and_ln46_reg_400_pp0_iter9_reg <= and_ln46_reg_400_pp0_iter8_reg;
        ap_phi_reg_pp0_iter10_expx_reg_58 <= ap_phi_reg_pp0_iter9_expx_reg_58;
        ap_phi_reg_pp0_iter10_resultf_3_reg_72 <= ap_phi_reg_pp0_iter9_resultf_3_reg_72;
        ap_phi_reg_pp0_iter11_expx_reg_58 <= ap_phi_reg_pp0_iter10_expx_reg_58;
        ap_phi_reg_pp0_iter11_resultf_3_reg_72 <= ap_phi_reg_pp0_iter10_resultf_3_reg_72;
        ap_phi_reg_pp0_iter12_expx_reg_58 <= ap_phi_reg_pp0_iter11_expx_reg_58;
        ap_phi_reg_pp0_iter12_resultf_3_reg_72 <= ap_phi_reg_pp0_iter11_resultf_3_reg_72;
        ap_phi_reg_pp0_iter13_expx_reg_58 <= ap_phi_reg_pp0_iter12_expx_reg_58;
        ap_phi_reg_pp0_iter13_resultf_3_reg_72 <= ap_phi_reg_pp0_iter12_resultf_3_reg_72;
        ap_phi_reg_pp0_iter14_expx_reg_58 <= ap_phi_reg_pp0_iter13_expx_reg_58;
        ap_phi_reg_pp0_iter14_resultf_3_reg_72 <= ap_phi_reg_pp0_iter13_resultf_3_reg_72;
        ap_phi_reg_pp0_iter15_expx_reg_58 <= ap_phi_reg_pp0_iter14_expx_reg_58;
        ap_phi_reg_pp0_iter15_resultf_3_reg_72 <= ap_phi_reg_pp0_iter14_resultf_3_reg_72;
        ap_phi_reg_pp0_iter16_expx_reg_58 <= ap_phi_reg_pp0_iter15_expx_reg_58;
        ap_phi_reg_pp0_iter16_resultf_3_reg_72 <= ap_phi_reg_pp0_iter15_resultf_3_reg_72;
        ap_phi_reg_pp0_iter17_expx_reg_58 <= ap_phi_reg_pp0_iter16_expx_reg_58;
        ap_phi_reg_pp0_iter17_resultf_3_reg_72 <= ap_phi_reg_pp0_iter16_resultf_3_reg_72;
        ap_phi_reg_pp0_iter18_expx_reg_58 <= ap_phi_reg_pp0_iter17_expx_reg_58;
        ap_phi_reg_pp0_iter18_resultf_3_reg_72 <= ap_phi_reg_pp0_iter17_resultf_3_reg_72;
        ap_phi_reg_pp0_iter19_resultf_3_reg_72 <= ap_phi_reg_pp0_iter18_resultf_3_reg_72;
        ap_phi_reg_pp0_iter1_expx_reg_58 <= ap_phi_reg_pp0_iter0_expx_reg_58;
        ap_phi_reg_pp0_iter1_resultf_3_reg_72 <= ap_phi_reg_pp0_iter0_resultf_3_reg_72;
        ap_phi_reg_pp0_iter20_resultf_3_reg_72 <= ap_phi_reg_pp0_iter19_resultf_3_reg_72;
        ap_phi_reg_pp0_iter21_resultf_3_reg_72 <= ap_phi_reg_pp0_iter20_resultf_3_reg_72;
        ap_phi_reg_pp0_iter22_resultf_3_reg_72 <= ap_phi_reg_pp0_iter21_resultf_3_reg_72;
        ap_phi_reg_pp0_iter23_resultf_3_reg_72 <= ap_phi_reg_pp0_iter22_resultf_3_reg_72;
        ap_phi_reg_pp0_iter24_resultf_3_reg_72 <= ap_phi_reg_pp0_iter23_resultf_3_reg_72;
        ap_phi_reg_pp0_iter25_resultf_3_reg_72 <= ap_phi_reg_pp0_iter24_resultf_3_reg_72;
        ap_phi_reg_pp0_iter26_resultf_3_reg_72 <= ap_phi_reg_pp0_iter25_resultf_3_reg_72;
        ap_phi_reg_pp0_iter27_resultf_3_reg_72 <= ap_phi_reg_pp0_iter26_resultf_3_reg_72;
        ap_phi_reg_pp0_iter28_resultf_3_reg_72 <= ap_phi_reg_pp0_iter27_resultf_3_reg_72;
        ap_phi_reg_pp0_iter2_expx_reg_58 <= ap_phi_reg_pp0_iter1_expx_reg_58;
        ap_phi_reg_pp0_iter30_resultf_3_reg_72 <= ap_phi_reg_pp0_iter29_resultf_3_reg_72;
        ap_phi_reg_pp0_iter31_resultf_3_reg_72 <= ap_phi_reg_pp0_iter30_resultf_3_reg_72;
        ap_phi_reg_pp0_iter3_expx_reg_58 <= ap_phi_reg_pp0_iter2_expx_reg_58;
        ap_phi_reg_pp0_iter3_resultf_3_reg_72 <= ap_phi_reg_pp0_iter2_resultf_3_reg_72;
        ap_phi_reg_pp0_iter4_expx_reg_58 <= ap_phi_reg_pp0_iter3_expx_reg_58;
        ap_phi_reg_pp0_iter4_resultf_3_reg_72 <= ap_phi_reg_pp0_iter3_resultf_3_reg_72;
        ap_phi_reg_pp0_iter6_expx_reg_58 <= ap_phi_reg_pp0_iter5_expx_reg_58;
        ap_phi_reg_pp0_iter6_resultf_3_reg_72 <= ap_phi_reg_pp0_iter5_resultf_3_reg_72;
        ap_phi_reg_pp0_iter7_expx_reg_58 <= ap_phi_reg_pp0_iter6_expx_reg_58;
        ap_phi_reg_pp0_iter7_resultf_3_reg_72 <= ap_phi_reg_pp0_iter6_resultf_3_reg_72;
        ap_phi_reg_pp0_iter8_expx_reg_58 <= ap_phi_reg_pp0_iter7_expx_reg_58;
        ap_phi_reg_pp0_iter8_resultf_3_reg_72 <= ap_phi_reg_pp0_iter7_resultf_3_reg_72;
        ap_phi_reg_pp0_iter9_expx_reg_58 <= ap_phi_reg_pp0_iter8_expx_reg_58;
        ap_phi_reg_pp0_iter9_resultf_3_reg_72 <= ap_phi_reg_pp0_iter8_resultf_3_reg_72;
        ap_predicate_pred47_state29 <= ((icmp_ln54_reg_413_pp0_iter26_reg == 1'd0) & (tmp_30_reg_409_pp0_iter26_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter26_reg == 1'd0) & (1'd0 == and_ln46_reg_400_pp0_iter26_reg) & (icmp_ln36_reg_392_pp0_iter26_reg == 1'd0));
        ap_predicate_pred536_state19 <= ((icmp_ln10_reg_447_pp0_iter16_reg == 1'd0) & (icmp_ln9_reg_443_pp0_iter16_reg == 1'd0) & (1'd0 == and_ln46_reg_400_pp0_iter16_reg) & (tmp_30_reg_409_pp0_iter16_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter16_reg == 1'd0) & (icmp_ln36_reg_392_pp0_iter16_reg == 1'd0));
        ap_predicate_pred55_state29 <= ((icmp_ln54_reg_413_pp0_iter26_reg == 1'd1) & (tmp_30_reg_409_pp0_iter26_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter26_reg == 1'd0) & (1'd0 == and_ln46_reg_400_pp0_iter26_reg) & (icmp_ln36_reg_392_pp0_iter26_reg == 1'd0));
        ap_predicate_pred666_state23 <= ((1'd0 == and_ln46_reg_400_pp0_iter20_reg) & (icmp_ln54_reg_413_pp0_iter20_reg == 1'd0) & (tmp_30_reg_409_pp0_iter20_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter20_reg == 1'd0) & (icmp_ln36_reg_392_pp0_iter20_reg == 1'd0));
        ap_predicate_pred671_state23 <= ((1'd0 == and_ln46_reg_400_pp0_iter20_reg) & (icmp_ln54_reg_413_pp0_iter20_reg == 1'd1) & (tmp_30_reg_409_pp0_iter20_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter20_reg == 1'd0) & (icmp_ln36_reg_392_pp0_iter20_reg == 1'd0));
        din_exp_reg_372 <= {{data_fu_155_p1[30:23]}};
        din_sign_reg_367 <= data_fu_155_p1[32'd31];
        din_sign_reg_367_pp0_iter10_reg <= din_sign_reg_367_pp0_iter9_reg;
        din_sign_reg_367_pp0_iter11_reg <= din_sign_reg_367_pp0_iter10_reg;
        din_sign_reg_367_pp0_iter12_reg <= din_sign_reg_367_pp0_iter11_reg;
        din_sign_reg_367_pp0_iter13_reg <= din_sign_reg_367_pp0_iter12_reg;
        din_sign_reg_367_pp0_iter14_reg <= din_sign_reg_367_pp0_iter13_reg;
        din_sign_reg_367_pp0_iter15_reg <= din_sign_reg_367_pp0_iter14_reg;
        din_sign_reg_367_pp0_iter16_reg <= din_sign_reg_367_pp0_iter15_reg;
        din_sign_reg_367_pp0_iter17_reg <= din_sign_reg_367_pp0_iter16_reg;
        din_sign_reg_367_pp0_iter18_reg <= din_sign_reg_367_pp0_iter17_reg;
        din_sign_reg_367_pp0_iter19_reg <= din_sign_reg_367_pp0_iter18_reg;
        din_sign_reg_367_pp0_iter1_reg <= din_sign_reg_367;
        din_sign_reg_367_pp0_iter20_reg <= din_sign_reg_367_pp0_iter19_reg;
        din_sign_reg_367_pp0_iter21_reg <= din_sign_reg_367_pp0_iter20_reg;
        din_sign_reg_367_pp0_iter22_reg <= din_sign_reg_367_pp0_iter21_reg;
        din_sign_reg_367_pp0_iter23_reg <= din_sign_reg_367_pp0_iter22_reg;
        din_sign_reg_367_pp0_iter24_reg <= din_sign_reg_367_pp0_iter23_reg;
        din_sign_reg_367_pp0_iter25_reg <= din_sign_reg_367_pp0_iter24_reg;
        din_sign_reg_367_pp0_iter26_reg <= din_sign_reg_367_pp0_iter25_reg;
        din_sign_reg_367_pp0_iter27_reg <= din_sign_reg_367_pp0_iter26_reg;
        din_sign_reg_367_pp0_iter28_reg <= din_sign_reg_367_pp0_iter27_reg;
        din_sign_reg_367_pp0_iter29_reg <= din_sign_reg_367_pp0_iter28_reg;
        din_sign_reg_367_pp0_iter2_reg <= din_sign_reg_367_pp0_iter1_reg;
        din_sign_reg_367_pp0_iter30_reg <= din_sign_reg_367_pp0_iter29_reg;
        din_sign_reg_367_pp0_iter31_reg <= din_sign_reg_367_pp0_iter30_reg;
        din_sign_reg_367_pp0_iter3_reg <= din_sign_reg_367_pp0_iter2_reg;
        din_sign_reg_367_pp0_iter4_reg <= din_sign_reg_367_pp0_iter3_reg;
        din_sign_reg_367_pp0_iter5_reg <= din_sign_reg_367_pp0_iter4_reg;
        din_sign_reg_367_pp0_iter6_reg <= din_sign_reg_367_pp0_iter5_reg;
        din_sign_reg_367_pp0_iter7_reg <= din_sign_reg_367_pp0_iter6_reg;
        din_sign_reg_367_pp0_iter8_reg <= din_sign_reg_367_pp0_iter7_reg;
        din_sign_reg_367_pp0_iter9_reg <= din_sign_reg_367_pp0_iter8_reg;
        expx_reg_58 <= ap_phi_reg_pp0_iter19_expx_reg_58;
        expx_reg_58_pp0_iter20_reg <= expx_reg_58;
        expx_reg_58_pp0_iter21_reg <= expx_reg_58_pp0_iter20_reg;
        icmp_ln10_reg_447 <= icmp_ln10_fu_278_p2;
        icmp_ln10_reg_447_pp0_iter10_reg <= icmp_ln10_reg_447_pp0_iter9_reg;
        icmp_ln10_reg_447_pp0_iter11_reg <= icmp_ln10_reg_447_pp0_iter10_reg;
        icmp_ln10_reg_447_pp0_iter12_reg <= icmp_ln10_reg_447_pp0_iter11_reg;
        icmp_ln10_reg_447_pp0_iter13_reg <= icmp_ln10_reg_447_pp0_iter12_reg;
        icmp_ln10_reg_447_pp0_iter14_reg <= icmp_ln10_reg_447_pp0_iter13_reg;
        icmp_ln10_reg_447_pp0_iter15_reg <= icmp_ln10_reg_447_pp0_iter14_reg;
        icmp_ln10_reg_447_pp0_iter16_reg <= icmp_ln10_reg_447_pp0_iter15_reg;
        icmp_ln10_reg_447_pp0_iter5_reg <= icmp_ln10_reg_447;
        icmp_ln10_reg_447_pp0_iter6_reg <= icmp_ln10_reg_447_pp0_iter5_reg;
        icmp_ln10_reg_447_pp0_iter7_reg <= icmp_ln10_reg_447_pp0_iter6_reg;
        icmp_ln10_reg_447_pp0_iter8_reg <= icmp_ln10_reg_447_pp0_iter7_reg;
        icmp_ln10_reg_447_pp0_iter9_reg <= icmp_ln10_reg_447_pp0_iter8_reg;
        icmp_ln36_reg_392 <= icmp_ln36_fu_199_p2;
        icmp_ln36_reg_392_pp0_iter10_reg <= icmp_ln36_reg_392_pp0_iter9_reg;
        icmp_ln36_reg_392_pp0_iter11_reg <= icmp_ln36_reg_392_pp0_iter10_reg;
        icmp_ln36_reg_392_pp0_iter12_reg <= icmp_ln36_reg_392_pp0_iter11_reg;
        icmp_ln36_reg_392_pp0_iter13_reg <= icmp_ln36_reg_392_pp0_iter12_reg;
        icmp_ln36_reg_392_pp0_iter14_reg <= icmp_ln36_reg_392_pp0_iter13_reg;
        icmp_ln36_reg_392_pp0_iter15_reg <= icmp_ln36_reg_392_pp0_iter14_reg;
        icmp_ln36_reg_392_pp0_iter16_reg <= icmp_ln36_reg_392_pp0_iter15_reg;
        icmp_ln36_reg_392_pp0_iter17_reg <= icmp_ln36_reg_392_pp0_iter16_reg;
        icmp_ln36_reg_392_pp0_iter18_reg <= icmp_ln36_reg_392_pp0_iter17_reg;
        icmp_ln36_reg_392_pp0_iter19_reg <= icmp_ln36_reg_392_pp0_iter18_reg;
        icmp_ln36_reg_392_pp0_iter1_reg <= icmp_ln36_reg_392;
        icmp_ln36_reg_392_pp0_iter20_reg <= icmp_ln36_reg_392_pp0_iter19_reg;
        icmp_ln36_reg_392_pp0_iter21_reg <= icmp_ln36_reg_392_pp0_iter20_reg;
        icmp_ln36_reg_392_pp0_iter22_reg <= icmp_ln36_reg_392_pp0_iter21_reg;
        icmp_ln36_reg_392_pp0_iter23_reg <= icmp_ln36_reg_392_pp0_iter22_reg;
        icmp_ln36_reg_392_pp0_iter24_reg <= icmp_ln36_reg_392_pp0_iter23_reg;
        icmp_ln36_reg_392_pp0_iter25_reg <= icmp_ln36_reg_392_pp0_iter24_reg;
        icmp_ln36_reg_392_pp0_iter26_reg <= icmp_ln36_reg_392_pp0_iter25_reg;
        icmp_ln36_reg_392_pp0_iter27_reg <= icmp_ln36_reg_392_pp0_iter26_reg;
        icmp_ln36_reg_392_pp0_iter28_reg <= icmp_ln36_reg_392_pp0_iter27_reg;
        icmp_ln36_reg_392_pp0_iter29_reg <= icmp_ln36_reg_392_pp0_iter28_reg;
        icmp_ln36_reg_392_pp0_iter2_reg <= icmp_ln36_reg_392_pp0_iter1_reg;
        icmp_ln36_reg_392_pp0_iter30_reg <= icmp_ln36_reg_392_pp0_iter29_reg;
        icmp_ln36_reg_392_pp0_iter31_reg <= icmp_ln36_reg_392_pp0_iter30_reg;
        icmp_ln36_reg_392_pp0_iter3_reg <= icmp_ln36_reg_392_pp0_iter2_reg;
        icmp_ln36_reg_392_pp0_iter4_reg <= icmp_ln36_reg_392_pp0_iter3_reg;
        icmp_ln36_reg_392_pp0_iter5_reg <= icmp_ln36_reg_392_pp0_iter4_reg;
        icmp_ln36_reg_392_pp0_iter6_reg <= icmp_ln36_reg_392_pp0_iter5_reg;
        icmp_ln36_reg_392_pp0_iter7_reg <= icmp_ln36_reg_392_pp0_iter6_reg;
        icmp_ln36_reg_392_pp0_iter8_reg <= icmp_ln36_reg_392_pp0_iter7_reg;
        icmp_ln36_reg_392_pp0_iter9_reg <= icmp_ln36_reg_392_pp0_iter8_reg;
        icmp_ln38_reg_404 <= icmp_ln38_fu_229_p2;
        icmp_ln38_reg_404_pp0_iter10_reg <= icmp_ln38_reg_404_pp0_iter9_reg;
        icmp_ln38_reg_404_pp0_iter11_reg <= icmp_ln38_reg_404_pp0_iter10_reg;
        icmp_ln38_reg_404_pp0_iter12_reg <= icmp_ln38_reg_404_pp0_iter11_reg;
        icmp_ln38_reg_404_pp0_iter13_reg <= icmp_ln38_reg_404_pp0_iter12_reg;
        icmp_ln38_reg_404_pp0_iter14_reg <= icmp_ln38_reg_404_pp0_iter13_reg;
        icmp_ln38_reg_404_pp0_iter15_reg <= icmp_ln38_reg_404_pp0_iter14_reg;
        icmp_ln38_reg_404_pp0_iter16_reg <= icmp_ln38_reg_404_pp0_iter15_reg;
        icmp_ln38_reg_404_pp0_iter17_reg <= icmp_ln38_reg_404_pp0_iter16_reg;
        icmp_ln38_reg_404_pp0_iter18_reg <= icmp_ln38_reg_404_pp0_iter17_reg;
        icmp_ln38_reg_404_pp0_iter19_reg <= icmp_ln38_reg_404_pp0_iter18_reg;
        icmp_ln38_reg_404_pp0_iter1_reg <= icmp_ln38_reg_404;
        icmp_ln38_reg_404_pp0_iter20_reg <= icmp_ln38_reg_404_pp0_iter19_reg;
        icmp_ln38_reg_404_pp0_iter21_reg <= icmp_ln38_reg_404_pp0_iter20_reg;
        icmp_ln38_reg_404_pp0_iter22_reg <= icmp_ln38_reg_404_pp0_iter21_reg;
        icmp_ln38_reg_404_pp0_iter23_reg <= icmp_ln38_reg_404_pp0_iter22_reg;
        icmp_ln38_reg_404_pp0_iter24_reg <= icmp_ln38_reg_404_pp0_iter23_reg;
        icmp_ln38_reg_404_pp0_iter25_reg <= icmp_ln38_reg_404_pp0_iter24_reg;
        icmp_ln38_reg_404_pp0_iter26_reg <= icmp_ln38_reg_404_pp0_iter25_reg;
        icmp_ln38_reg_404_pp0_iter27_reg <= icmp_ln38_reg_404_pp0_iter26_reg;
        icmp_ln38_reg_404_pp0_iter28_reg <= icmp_ln38_reg_404_pp0_iter27_reg;
        icmp_ln38_reg_404_pp0_iter29_reg <= icmp_ln38_reg_404_pp0_iter28_reg;
        icmp_ln38_reg_404_pp0_iter2_reg <= icmp_ln38_reg_404_pp0_iter1_reg;
        icmp_ln38_reg_404_pp0_iter30_reg <= icmp_ln38_reg_404_pp0_iter29_reg;
        icmp_ln38_reg_404_pp0_iter3_reg <= icmp_ln38_reg_404_pp0_iter2_reg;
        icmp_ln38_reg_404_pp0_iter4_reg <= icmp_ln38_reg_404_pp0_iter3_reg;
        icmp_ln38_reg_404_pp0_iter5_reg <= icmp_ln38_reg_404_pp0_iter4_reg;
        icmp_ln38_reg_404_pp0_iter6_reg <= icmp_ln38_reg_404_pp0_iter5_reg;
        icmp_ln38_reg_404_pp0_iter7_reg <= icmp_ln38_reg_404_pp0_iter6_reg;
        icmp_ln38_reg_404_pp0_iter8_reg <= icmp_ln38_reg_404_pp0_iter7_reg;
        icmp_ln38_reg_404_pp0_iter9_reg <= icmp_ln38_reg_404_pp0_iter8_reg;
        icmp_ln45_reg_396 <= icmp_ln45_fu_205_p2;
        icmp_ln45_reg_396_pp0_iter10_reg <= icmp_ln45_reg_396_pp0_iter9_reg;
        icmp_ln45_reg_396_pp0_iter11_reg <= icmp_ln45_reg_396_pp0_iter10_reg;
        icmp_ln45_reg_396_pp0_iter12_reg <= icmp_ln45_reg_396_pp0_iter11_reg;
        icmp_ln45_reg_396_pp0_iter13_reg <= icmp_ln45_reg_396_pp0_iter12_reg;
        icmp_ln45_reg_396_pp0_iter14_reg <= icmp_ln45_reg_396_pp0_iter13_reg;
        icmp_ln45_reg_396_pp0_iter15_reg <= icmp_ln45_reg_396_pp0_iter14_reg;
        icmp_ln45_reg_396_pp0_iter16_reg <= icmp_ln45_reg_396_pp0_iter15_reg;
        icmp_ln45_reg_396_pp0_iter17_reg <= icmp_ln45_reg_396_pp0_iter16_reg;
        icmp_ln45_reg_396_pp0_iter18_reg <= icmp_ln45_reg_396_pp0_iter17_reg;
        icmp_ln45_reg_396_pp0_iter19_reg <= icmp_ln45_reg_396_pp0_iter18_reg;
        icmp_ln45_reg_396_pp0_iter1_reg <= icmp_ln45_reg_396;
        icmp_ln45_reg_396_pp0_iter20_reg <= icmp_ln45_reg_396_pp0_iter19_reg;
        icmp_ln45_reg_396_pp0_iter21_reg <= icmp_ln45_reg_396_pp0_iter20_reg;
        icmp_ln45_reg_396_pp0_iter22_reg <= icmp_ln45_reg_396_pp0_iter21_reg;
        icmp_ln45_reg_396_pp0_iter23_reg <= icmp_ln45_reg_396_pp0_iter22_reg;
        icmp_ln45_reg_396_pp0_iter24_reg <= icmp_ln45_reg_396_pp0_iter23_reg;
        icmp_ln45_reg_396_pp0_iter25_reg <= icmp_ln45_reg_396_pp0_iter24_reg;
        icmp_ln45_reg_396_pp0_iter26_reg <= icmp_ln45_reg_396_pp0_iter25_reg;
        icmp_ln45_reg_396_pp0_iter27_reg <= icmp_ln45_reg_396_pp0_iter26_reg;
        icmp_ln45_reg_396_pp0_iter28_reg <= icmp_ln45_reg_396_pp0_iter27_reg;
        icmp_ln45_reg_396_pp0_iter29_reg <= icmp_ln45_reg_396_pp0_iter28_reg;
        icmp_ln45_reg_396_pp0_iter2_reg <= icmp_ln45_reg_396_pp0_iter1_reg;
        icmp_ln45_reg_396_pp0_iter30_reg <= icmp_ln45_reg_396_pp0_iter29_reg;
        icmp_ln45_reg_396_pp0_iter31_reg <= icmp_ln45_reg_396_pp0_iter30_reg;
        icmp_ln45_reg_396_pp0_iter3_reg <= icmp_ln45_reg_396_pp0_iter2_reg;
        icmp_ln45_reg_396_pp0_iter4_reg <= icmp_ln45_reg_396_pp0_iter3_reg;
        icmp_ln45_reg_396_pp0_iter5_reg <= icmp_ln45_reg_396_pp0_iter4_reg;
        icmp_ln45_reg_396_pp0_iter6_reg <= icmp_ln45_reg_396_pp0_iter5_reg;
        icmp_ln45_reg_396_pp0_iter7_reg <= icmp_ln45_reg_396_pp0_iter6_reg;
        icmp_ln45_reg_396_pp0_iter8_reg <= icmp_ln45_reg_396_pp0_iter7_reg;
        icmp_ln45_reg_396_pp0_iter9_reg <= icmp_ln45_reg_396_pp0_iter8_reg;
        icmp_ln54_reg_413 <= icmp_ln54_fu_235_p2;
        icmp_ln54_reg_413_pp0_iter10_reg <= icmp_ln54_reg_413_pp0_iter9_reg;
        icmp_ln54_reg_413_pp0_iter11_reg <= icmp_ln54_reg_413_pp0_iter10_reg;
        icmp_ln54_reg_413_pp0_iter12_reg <= icmp_ln54_reg_413_pp0_iter11_reg;
        icmp_ln54_reg_413_pp0_iter13_reg <= icmp_ln54_reg_413_pp0_iter12_reg;
        icmp_ln54_reg_413_pp0_iter14_reg <= icmp_ln54_reg_413_pp0_iter13_reg;
        icmp_ln54_reg_413_pp0_iter15_reg <= icmp_ln54_reg_413_pp0_iter14_reg;
        icmp_ln54_reg_413_pp0_iter16_reg <= icmp_ln54_reg_413_pp0_iter15_reg;
        icmp_ln54_reg_413_pp0_iter17_reg <= icmp_ln54_reg_413_pp0_iter16_reg;
        icmp_ln54_reg_413_pp0_iter18_reg <= icmp_ln54_reg_413_pp0_iter17_reg;
        icmp_ln54_reg_413_pp0_iter19_reg <= icmp_ln54_reg_413_pp0_iter18_reg;
        icmp_ln54_reg_413_pp0_iter20_reg <= icmp_ln54_reg_413_pp0_iter19_reg;
        icmp_ln54_reg_413_pp0_iter21_reg <= icmp_ln54_reg_413_pp0_iter20_reg;
        icmp_ln54_reg_413_pp0_iter22_reg <= icmp_ln54_reg_413_pp0_iter21_reg;
        icmp_ln54_reg_413_pp0_iter23_reg <= icmp_ln54_reg_413_pp0_iter22_reg;
        icmp_ln54_reg_413_pp0_iter24_reg <= icmp_ln54_reg_413_pp0_iter23_reg;
        icmp_ln54_reg_413_pp0_iter25_reg <= icmp_ln54_reg_413_pp0_iter24_reg;
        icmp_ln54_reg_413_pp0_iter26_reg <= icmp_ln54_reg_413_pp0_iter25_reg;
        icmp_ln54_reg_413_pp0_iter27_reg <= icmp_ln54_reg_413_pp0_iter26_reg;
        icmp_ln54_reg_413_pp0_iter28_reg <= icmp_ln54_reg_413_pp0_iter27_reg;
        icmp_ln54_reg_413_pp0_iter29_reg <= icmp_ln54_reg_413_pp0_iter28_reg;
        icmp_ln54_reg_413_pp0_iter2_reg <= icmp_ln54_reg_413;
        icmp_ln54_reg_413_pp0_iter30_reg <= icmp_ln54_reg_413_pp0_iter29_reg;
        icmp_ln54_reg_413_pp0_iter31_reg <= icmp_ln54_reg_413_pp0_iter30_reg;
        icmp_ln54_reg_413_pp0_iter3_reg <= icmp_ln54_reg_413_pp0_iter2_reg;
        icmp_ln54_reg_413_pp0_iter4_reg <= icmp_ln54_reg_413_pp0_iter3_reg;
        icmp_ln54_reg_413_pp0_iter5_reg <= icmp_ln54_reg_413_pp0_iter4_reg;
        icmp_ln54_reg_413_pp0_iter6_reg <= icmp_ln54_reg_413_pp0_iter5_reg;
        icmp_ln54_reg_413_pp0_iter7_reg <= icmp_ln54_reg_413_pp0_iter6_reg;
        icmp_ln54_reg_413_pp0_iter8_reg <= icmp_ln54_reg_413_pp0_iter7_reg;
        icmp_ln54_reg_413_pp0_iter9_reg <= icmp_ln54_reg_413_pp0_iter8_reg;
        icmp_ln9_reg_443 <= icmp_ln9_fu_272_p2;
        icmp_ln9_reg_443_pp0_iter10_reg <= icmp_ln9_reg_443_pp0_iter9_reg;
        icmp_ln9_reg_443_pp0_iter11_reg <= icmp_ln9_reg_443_pp0_iter10_reg;
        icmp_ln9_reg_443_pp0_iter12_reg <= icmp_ln9_reg_443_pp0_iter11_reg;
        icmp_ln9_reg_443_pp0_iter13_reg <= icmp_ln9_reg_443_pp0_iter12_reg;
        icmp_ln9_reg_443_pp0_iter14_reg <= icmp_ln9_reg_443_pp0_iter13_reg;
        icmp_ln9_reg_443_pp0_iter15_reg <= icmp_ln9_reg_443_pp0_iter14_reg;
        icmp_ln9_reg_443_pp0_iter16_reg <= icmp_ln9_reg_443_pp0_iter15_reg;
        icmp_ln9_reg_443_pp0_iter5_reg <= icmp_ln9_reg_443;
        icmp_ln9_reg_443_pp0_iter6_reg <= icmp_ln9_reg_443_pp0_iter5_reg;
        icmp_ln9_reg_443_pp0_iter7_reg <= icmp_ln9_reg_443_pp0_iter6_reg;
        icmp_ln9_reg_443_pp0_iter8_reg <= icmp_ln9_reg_443_pp0_iter7_reg;
        icmp_ln9_reg_443_pp0_iter9_reg <= icmp_ln9_reg_443_pp0_iter8_reg;
        resultf_2_reg_486 <= grp_fu_119_p2;
        sub_i_reg_466 <= grp_fu_144_p2;
        tmp_30_reg_409 <= grp_fu_139_p2;
        tmp_30_reg_409_pp0_iter10_reg <= tmp_30_reg_409_pp0_iter9_reg;
        tmp_30_reg_409_pp0_iter11_reg <= tmp_30_reg_409_pp0_iter10_reg;
        tmp_30_reg_409_pp0_iter12_reg <= tmp_30_reg_409_pp0_iter11_reg;
        tmp_30_reg_409_pp0_iter13_reg <= tmp_30_reg_409_pp0_iter12_reg;
        tmp_30_reg_409_pp0_iter14_reg <= tmp_30_reg_409_pp0_iter13_reg;
        tmp_30_reg_409_pp0_iter15_reg <= tmp_30_reg_409_pp0_iter14_reg;
        tmp_30_reg_409_pp0_iter16_reg <= tmp_30_reg_409_pp0_iter15_reg;
        tmp_30_reg_409_pp0_iter17_reg <= tmp_30_reg_409_pp0_iter16_reg;
        tmp_30_reg_409_pp0_iter18_reg <= tmp_30_reg_409_pp0_iter17_reg;
        tmp_30_reg_409_pp0_iter19_reg <= tmp_30_reg_409_pp0_iter18_reg;
        tmp_30_reg_409_pp0_iter20_reg <= tmp_30_reg_409_pp0_iter19_reg;
        tmp_30_reg_409_pp0_iter21_reg <= tmp_30_reg_409_pp0_iter20_reg;
        tmp_30_reg_409_pp0_iter22_reg <= tmp_30_reg_409_pp0_iter21_reg;
        tmp_30_reg_409_pp0_iter23_reg <= tmp_30_reg_409_pp0_iter22_reg;
        tmp_30_reg_409_pp0_iter24_reg <= tmp_30_reg_409_pp0_iter23_reg;
        tmp_30_reg_409_pp0_iter25_reg <= tmp_30_reg_409_pp0_iter24_reg;
        tmp_30_reg_409_pp0_iter26_reg <= tmp_30_reg_409_pp0_iter25_reg;
        tmp_30_reg_409_pp0_iter27_reg <= tmp_30_reg_409_pp0_iter26_reg;
        tmp_30_reg_409_pp0_iter28_reg <= tmp_30_reg_409_pp0_iter27_reg;
        tmp_30_reg_409_pp0_iter29_reg <= tmp_30_reg_409_pp0_iter28_reg;
        tmp_30_reg_409_pp0_iter2_reg <= tmp_30_reg_409;
        tmp_30_reg_409_pp0_iter30_reg <= tmp_30_reg_409_pp0_iter29_reg;
        tmp_30_reg_409_pp0_iter31_reg <= tmp_30_reg_409_pp0_iter30_reg;
        tmp_30_reg_409_pp0_iter3_reg <= tmp_30_reg_409_pp0_iter2_reg;
        tmp_30_reg_409_pp0_iter4_reg <= tmp_30_reg_409_pp0_iter3_reg;
        tmp_30_reg_409_pp0_iter5_reg <= tmp_30_reg_409_pp0_iter4_reg;
        tmp_30_reg_409_pp0_iter6_reg <= tmp_30_reg_409_pp0_iter5_reg;
        tmp_30_reg_409_pp0_iter7_reg <= tmp_30_reg_409_pp0_iter6_reg;
        tmp_30_reg_409_pp0_iter8_reg <= tmp_30_reg_409_pp0_iter7_reg;
        tmp_30_reg_409_pp0_iter9_reg <= tmp_30_reg_409_pp0_iter8_reg;
        tmp_s_reg_461 <= grp_exp_generic_double_s_fu_89_ap_return;
        trunc_ln313_reg_377 <= trunc_ln313_fu_181_p1;
        x_4_reg_433 <= grp_fu_109_p2;
        x_reg_428 <= grp_fu_105_p2;
        xd_reg_451 <= xd_fu_136_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_pred55_state29 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_pred47_state29 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_149 <= grp_fu_128_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        t_in_int_reg <= t_in;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln46_reg_400_pp0_iter31_reg) & (icmp_ln54_reg_413_pp0_iter31_reg == 1'd0) & (tmp_30_reg_409_pp0_iter31_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter31_reg == 1'd0) & (icmp_ln36_reg_392_pp0_iter31_reg == 1'd0))) begin
        ap_phi_mux_resultf_3_phi_fu_76_p10 = resultf_2_reg_486;
    end else begin
        ap_phi_mux_resultf_3_phi_fu_76_p10 = ap_phi_reg_pp0_iter32_resultf_3_reg_72;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp78))) begin
        grp_exp_generic_double_s_fu_89_ap_ce = 1'b1;
    end else begin
        grp_exp_generic_double_s_fu_89_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_100_ce = 1'b1;
    end else begin
        grp_fu_100_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_105_ce = 1'b1;
    end else begin
        grp_fu_105_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_109_ce = 1'b1;
    end else begin
        grp_fu_109_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_113_ce = 1'b1;
    end else begin
        grp_fu_113_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_119_ce = 1'b1;
    end else begin
        grp_fu_119_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_124_ce = 1'b1;
    end else begin
        grp_fu_124_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_128_ce = 1'b1;
    end else begin
        grp_fu_128_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_pred671_state23 == 1'b1)) begin
            grp_fu_128_p0 = bitcast_ln66_1_fu_314_p1;
        end else if ((ap_predicate_pred666_state23 == 1'b1)) begin
            grp_fu_128_p0 = 32'd1073741824;
        end else begin
            grp_fu_128_p0 = 'bx;
        end
    end else begin
        grp_fu_128_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_133_ce = 1'b1;
    end else begin
        grp_fu_133_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_139_ce = 1'b1;
    end else begin
        grp_fu_139_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_144_ce = 1'b1;
    end else begin
        grp_fu_144_ce = 1'b0;
    end
end

assign abst_in_fu_193_p1 = t_fu_185_p3;

assign and_ln46_fu_223_p2 = (icmp_ln46_fu_211_p2 & icmp_ln46_1_fu_217_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp78 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp78 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_556 = ((icmp_ln9_fu_272_p2 == 1'd1) & (1'd0 == and_ln46_reg_400_pp0_iter3_reg) & (tmp_30_reg_409_pp0_iter3_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter3_reg == 1'd0) & (icmp_ln36_reg_392_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_condition_561 = ((icmp_ln10_fu_278_p2 == 1'd1) & (icmp_ln9_fu_272_p2 == 1'd0) & (1'd0 == and_ln46_reg_400_pp0_iter3_reg) & (tmp_30_reg_409_pp0_iter3_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter3_reg == 1'd0) & (icmp_ln36_reg_392_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_condition_601 = (((icmp_ln45_reg_396_pp0_iter3_reg == 1'd1) & (icmp_ln36_reg_392_pp0_iter3_reg == 1'd0)) | ((1'd1 == and_ln46_reg_400_pp0_iter3_reg) & (icmp_ln36_reg_392_pp0_iter3_reg == 1'd0)));
end

always @ (*) begin
    ap_condition_633 = ((icmp_ln45_reg_396 == 1'd0) & (1'd0 == and_ln46_reg_400) & (icmp_ln36_reg_392 == 1'd0) & (grp_fu_139_p2 == 1'd0));
end

assign ap_phi_reg_pp0_iter0_expx_reg_58 = 'bx;

assign ap_phi_reg_pp0_iter0_resultf_3_reg_72 = 'bx;

always @ (*) begin
    ap_predicate_op50_fcmp_state1 = ((1'd0 == and_ln46_fu_223_p2) & (icmp_ln45_fu_205_p2 == 1'd0) & (icmp_ln36_fu_199_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op78_call_state6 = ((icmp_ln10_reg_447 == 1'd0) & (icmp_ln9_reg_443 == 1'd0) & (1'd0 == and_ln46_reg_400_pp0_iter4_reg) & (tmp_30_reg_409_pp0_iter4_reg == 1'd1) & (icmp_ln45_reg_396_pp0_iter4_reg == 1'd0) & (icmp_ln36_reg_392_pp0_iter4_reg == 1'd0));
end

assign ap_return = ((din_sign_reg_367_pp0_iter31_reg[0:0] == 1'b1) ? bitcast_ln83_1_fu_356_p1 : ap_phi_mux_resultf_3_phi_fu_76_p10);

assign bit_sel1_fu_330_p3 = bitcast_ln83_fu_326_p1[32'd31];

assign bit_sel_fu_288_p3 = bitcast_ln66_fu_284_p1[32'd31];

assign bitcast_ln66_1_fu_314_p1 = xor_ln_fu_306_p3;

assign bitcast_ln66_fu_284_p1 = expx_reg_58_pp0_iter21_reg;

assign bitcast_ln83_1_fu_356_p1 = xor_ln1_fu_348_p3;

assign bitcast_ln83_fu_326_p1 = ap_phi_mux_resultf_3_phi_fu_76_p10;

assign data_4_fu_258_p1 = x_6_fu_252_p3;

assign data_fu_155_p1 = t_in_int_reg;

assign din_exp_fu_167_p4 = {{data_fu_155_p1[30:23]}};

assign din_sig_fu_177_p1 = data_fu_155_p1[22:0];

assign grp_fu_105_p0 = or_ln_fu_240_p3;

assign icmp_ln10_fu_278_p2 = ((xs_exp_1_fu_262_p4 < 8'd96) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_199_p2 = ((din_exp_fu_167_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_229_p2 = ((din_sig_fu_177_p1 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_205_p2 = ((din_exp_fu_167_p4 < 8'd72) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_217_p2 = ((din_sig_fu_177_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_211_p2 = ((din_exp_fu_167_p4 == 8'd72) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_235_p2 = ((din_exp_reg_372 < 8'd127) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_272_p2 = ((xs_exp_1_fu_262_p4 == 8'd0) ? 1'b1 : 1'b0);

assign or_ln_fu_240_p3 = {{1'd1}, {trunc_ln313_reg_377}};

assign select_ln38_fu_319_p3 = ((icmp_ln38_reg_404_pp0_iter30_reg[0:0] == 1'b1) ? 32'd2147483647 : 32'd1065353216);

assign t_fu_185_p3 = {{1'd0}, {trunc_ln313_fu_181_p1}};

assign trunc_ln313_fu_181_p1 = data_fu_155_p1[30:0];

assign trunc_ln66_fu_302_p1 = bitcast_ln66_fu_284_p1[30:0];

assign trunc_ln83_fu_344_p1 = bitcast_ln83_fu_326_p1[30:0];

assign x_6_fu_252_p3 = ((icmp_ln54_reg_413_pp0_iter3_reg[0:0] == 1'b1) ? x_reg_428 : x_4_reg_433);

assign xor_ln1_fu_348_p3 = {{xor_ln83_fu_338_p2}, {trunc_ln83_fu_344_p1}};

assign xor_ln66_fu_296_p2 = (bit_sel_fu_288_p3 ^ 1'd1);

assign xor_ln83_fu_338_p2 = (bit_sel1_fu_330_p3 ^ 1'd1);

assign xor_ln_fu_306_p3 = {{xor_ln66_fu_296_p2}, {trunc_ln66_fu_302_p1}};

assign xs_exp_1_fu_262_p4 = {{data_4_fu_258_p1[30:23]}};

always @ (posedge ap_clk) begin
    abst_in_reg_382[31] <= 1'b0;
    abst_in_reg_382_pp0_iter1_reg[31] <= 1'b0;
    abst_in_reg_382_pp0_iter2_reg[31] <= 1'b0;
end

endmodule //pedal_top_generic_tanh_float_s
