// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pedal_top_exp_generic_double_s (
        ap_clk,
        ap_rst,
        x,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [63:0] x;
output  [63:0] ap_return;
input   ap_ce;

reg[63:0] ap_return;

wire   [7:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [57:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1;
wire   [7:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0;
wire   [41:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0;
wire   [0:0] es_sign_fu_286_p3;
reg   [0:0] es_sign_reg_1129;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] es_sign_reg_1129_pp0_iter1_reg;
reg   [0:0] es_sign_reg_1129_pp0_iter2_reg;
reg   [0:0] es_sign_reg_1129_pp0_iter3_reg;
reg   [0:0] es_sign_reg_1129_pp0_iter4_reg;
reg   [0:0] es_sign_reg_1129_pp0_iter5_reg;
wire   [0:0] icmp_ln18_fu_308_p2;
reg   [0:0] icmp_ln18_reg_1134;
reg   [0:0] icmp_ln18_reg_1134_pp0_iter1_reg;
reg   [0:0] icmp_ln18_reg_1134_pp0_iter2_reg;
reg   [0:0] icmp_ln18_reg_1134_pp0_iter3_reg;
reg   [0:0] icmp_ln18_reg_1134_pp0_iter4_reg;
reg   [0:0] icmp_ln18_reg_1134_pp0_iter5_reg;
wire   [0:0] icmp_ln18_1_fu_314_p2;
reg   [0:0] icmp_ln18_1_reg_1142;
reg   [0:0] icmp_ln18_1_reg_1142_pp0_iter1_reg;
reg   [0:0] icmp_ln18_1_reg_1142_pp0_iter2_reg;
reg   [0:0] icmp_ln18_1_reg_1142_pp0_iter3_reg;
reg   [0:0] icmp_ln18_1_reg_1142_pp0_iter4_reg;
reg   [0:0] icmp_ln18_1_reg_1142_pp0_iter5_reg;
reg   [0:0] tmp_158_reg_1148;
reg   [0:0] tmp_158_reg_1148_pp0_iter1_reg;
wire   [58:0] trunc_ln255_fu_470_p1;
reg   [58:0] trunc_ln255_reg_1158;
reg   [58:0] trunc_ln255_reg_1158_pp0_iter1_reg;
reg   [58:0] trunc_ln255_reg_1158_pp0_iter2_reg;
wire   [0:0] icmp_ln309_fu_474_p2;
reg   [0:0] icmp_ln309_reg_1163;
reg   [0:0] icmp_ln309_reg_1163_pp0_iter1_reg;
reg   [0:0] icmp_ln309_reg_1163_pp0_iter2_reg;
reg   [0:0] icmp_ln309_reg_1163_pp0_iter3_reg;
reg   [0:0] icmp_ln309_reg_1163_pp0_iter4_reg;
reg   [0:0] icmp_ln309_reg_1163_pp0_iter5_reg;
wire   [0:0] icmp_ln309_2_fu_496_p2;
reg   [0:0] icmp_ln309_2_reg_1171;
reg   [0:0] icmp_ln309_2_reg_1171_pp0_iter1_reg;
reg   [0:0] icmp_ln309_2_reg_1171_pp0_iter2_reg;
reg   [0:0] icmp_ln309_2_reg_1171_pp0_iter3_reg;
reg   [0:0] icmp_ln309_2_reg_1171_pp0_iter4_reg;
reg   [0:0] icmp_ln309_2_reg_1171_pp0_iter5_reg;
reg   [0:0] tmp_162_reg_1176;
reg   [0:0] tmp_162_reg_1176_pp0_iter1_reg;
reg   [0:0] tmp_162_reg_1176_pp0_iter2_reg;
reg   [0:0] tmp_162_reg_1176_pp0_iter3_reg;
reg   [0:0] tmp_162_reg_1176_pp0_iter4_reg;
reg   [0:0] tmp_162_reg_1176_pp0_iter5_reg;
wire  signed [12:0] r_exp_fu_560_p3;
reg  signed [12:0] r_exp_reg_1186;
reg  signed [12:0] r_exp_reg_1186_pp0_iter4_reg;
reg  signed [12:0] r_exp_reg_1186_pp0_iter5_reg;
reg   [7:0] m_diff_hi_reg_1192;
reg   [7:0] m_diff_hi_reg_1192_pp0_iter4_reg;
reg   [7:0] Z2_reg_1197;
reg   [7:0] Z2_reg_1197_pp0_iter4_reg;
wire   [7:0] Z3_fu_616_p4;
reg   [7:0] Z3_reg_1204;
wire   [34:0] Z4_fu_626_p1;
reg   [34:0] Z4_reg_1209;
wire   [43:0] exp_Z2P_m_1_fu_720_p2;
reg   [43:0] exp_Z2P_m_1_reg_1224;
reg   [49:0] exp_Z1P_m_1_reg_1240;
wire   [63:0] zext_ln114_fu_640_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln119_fu_645_p1;
wire   [63:0] zext_ln138_fu_726_p1;
wire   [63:0] zext_ln292_fu_730_p1;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
reg    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
reg    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local;
wire   [42:0] mul_ln123_fu_270_p0;
wire   [35:0] mul_ln123_fu_270_p1;
wire   [48:0] mul_ln142_fu_274_p0;
wire   [43:0] mul_ln142_fu_274_p1;
wire   [49:0] mul_ln297_fu_278_p0;
wire   [49:0] mul_ln297_fu_278_p1;
wire   [63:0] data_fu_282_p1;
wire   [10:0] es_exp_fu_294_p4;
wire   [51:0] es_sig_fu_304_p1;
wire   [11:0] zext_ln486_fu_320_p1;
wire   [52:0] e_frac_fu_330_p3;
wire   [53:0] zext_ln221_fu_338_p1;
wire   [53:0] e_frac_1_fu_342_p2;
wire   [53:0] e_frac_3_fu_348_p3;
wire   [60:0] m_frac_l_1_fu_356_p3;
wire   [11:0] m_exp_fu_324_p2;
wire   [10:0] sub_ln229_fu_376_p2;
wire   [0:0] tmp_fu_368_p3;
wire  signed [11:0] sext_ln229_fu_382_p1;
wire   [11:0] select_ln229_fu_386_p3;
wire  signed [31:0] sext_ln229_1_fu_394_p1;
wire  signed [70:0] sext_ln227_fu_364_p1;
wire   [70:0] zext_ln229_fu_398_p1;
wire   [70:0] ashr_ln229_fu_402_p2;
wire   [70:0] shl_ln229_fu_408_p2;
wire   [70:0] m_fix_fu_414_p3;
wire   [63:0] m_fix_l_fu_422_p4;
wire   [63:0] zext_ln230_fu_432_p1;
wire  signed [15:0] m_fix_hi_fu_448_p4;
wire   [63:0] shl_ln230_fu_436_p2;
wire   [63:0] ashr_ln230_fu_442_p2;
wire   [63:0] select_ln230_fu_480_p3;
wire   [70:0] shl_ln7_fu_488_p3;
wire  signed [18:0] shl_ln_fu_510_p3;
wire  signed [30:0] grp_fu_1118_p3;
wire   [17:0] trunc_ln243_fu_537_p1;
wire   [12:0] tmp_176_cast_fu_521_p4;
wire   [0:0] icmp_ln243_fu_540_p2;
wire   [12:0] add_ln243_1_fu_546_p2;
wire   [0:0] tmp_159_fu_530_p3;
wire   [12:0] select_ln243_fu_552_p3;
wire   [70:0] mul_ln249_fu_265_p2;
wire   [57:0] tmp_53_fu_573_p4;
wire   [58:0] and_ln_fu_583_p3;
wire   [58:0] sub_ln255_fu_591_p2;
wire   [7:0] Z4_ind_fu_630_p4;
wire   [9:0] f_Z4_fu_650_p4;
wire   [35:0] zext_ln115_fu_660_p1;
wire   [35:0] zext_ln115_1_fu_663_p1;
wire   [42:0] exp_Z3_m_1_fu_673_p4;
wire   [35:0] exp_Z4_m_1_fu_667_p2;
wire   [78:0] mul_ln123_fu_270_p2;
wire   [19:0] tmp_54_fu_696_p4;
wire   [35:0] zext_ln126_1_fu_706_p1;
wire   [35:0] add_ln126_fu_710_p2;
wire   [43:0] zext_ln126_fu_716_p1;
wire   [43:0] zext_ln120_fu_682_p1;
wire   [39:0] tmp_55_fu_734_p4;
wire   [48:0] exp_Z2_m_1_fu_744_p4;
wire   [50:0] and_ln1_fu_762_p5;
wire   [92:0] mul_ln142_fu_274_p2;
wire   [35:0] tmp_57_fu_777_p4;
wire   [43:0] zext_ln145_2_fu_787_p1;
wire   [43:0] add_ln145_fu_791_p2;
wire   [51:0] zext_ln145_1_fu_796_p1;
wire   [51:0] zext_ln145_fu_773_p1;
wire   [51:0] exp_Z1P_m_1_l_fu_800_p2;
wire   [0:0] xor_ln182_fu_816_p2;
wire   [0:0] and_ln182_1_fu_821_p2;
wire   [0:0] xor_ln18_fu_831_p2;
wire   [0:0] and_ln18_fu_836_p2;
wire   [0:0] and_ln182_fu_826_p2;
wire   [0:0] or_ln185_fu_849_p2;
wire   [63:0] select_ln18_fu_841_p3;
wire   [49:0] exp_Z1_hi_fu_863_p4;
wire   [57:0] add_ln297_fu_873_p2;
wire   [99:0] mul_ln297_fu_278_p2;
wire   [106:0] shl_ln6_fu_888_p3;
wire   [106:0] zext_ln297_2_fu_896_p1;
wire   [106:0] add_ln297_1_fu_900_p2;
wire   [0:0] tmp_160_fu_906_p3;
wire   [12:0] r_exp_1_fu_914_p2;
wire   [12:0] r_exp_2_fu_919_p3;
wire   [2:0] tmp_161_fu_926_p4;
wire   [0:0] icmp_ln309_1_fu_936_p2;
wire   [10:0] trunc_ln336_fu_960_p1;
wire   [51:0] tmp_31_fu_970_p4;
wire   [51:0] tmp_32_fu_980_p4;
wire   [10:0] out_exp_fu_964_p2;
wire   [51:0] select_ln303_fu_990_p3;
wire   [63:0] t_fu_998_p4;
wire   [0:0] or_ln309_fu_942_p2;
wire   [0:0] xor_ln309_fu_1017_p2;
wire   [0:0] and_ln309_fu_1012_p2;
wire   [0:0] and_ln309_1_fu_1022_p2;
wire   [0:0] or_ln309_1_fu_1028_p2;
wire   [0:0] xor_ln18_1_fu_1034_p2;
wire   [0:0] xor_ln309_1_fu_1045_p2;
wire   [0:0] or_ln309_2_fu_1056_p2;
wire   [0:0] and_ln309_3_fu_1051_p2;
wire   [0:0] xor_ln309_2_fu_1061_p2;
wire   [0:0] or_ln309_3_fu_1067_p2;
wire   [0:0] and_ln309_4_fu_1073_p2;
wire   [0:0] icmp_ln326_fu_954_p2;
wire   [0:0] and_ln309_2_fu_1039_p2;
wire   [0:0] and_ln309_5_fu_1079_p2;
wire   [63:0] retval_1_fu_1094_p2;
wire   [63:0] retval_1_fu_1094_p4;
wire   [63:0] retval_1_fu_1094_p8;
wire   [63:0] retval_1_fu_1094_p9;
wire   [2:0] retval_1_fu_1094_p10;
wire   [14:0] grp_fu_1118_p1;
wire   [63:0] retval_1_fu_1094_p11;
reg    grp_fu_1118_ce;
reg    ap_ce_reg;
reg   [63:0] x_int_reg;
reg   [63:0] ap_return_int_reg;
wire   [78:0] mul_ln123_fu_270_p00;
wire   [78:0] mul_ln123_fu_270_p10;
wire   [92:0] mul_ln142_fu_274_p00;
wire   [92:0] mul_ln142_fu_274_p10;
wire   [99:0] mul_ln297_fu_278_p00;
wire   [99:0] mul_ln297_fu_278_p10;
wire  signed [2:0] retval_1_fu_1094_p1;
wire   [2:0] retval_1_fu_1094_p3;
wire   [2:0] retval_1_fu_1094_p5;
wire   [2:0] retval_1_fu_1094_p7;

pedal_top_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb #(
    .DataWidth( 58 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0)
);

pedal_top_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud #(
    .DataWidth( 26 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0),
    .address1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1),
    .ce1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local),
    .q1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1)
);

pedal_top_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe #(
    .DataWidth( 42 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0),
    .ce0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local),
    .q0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0)
);

pedal_top_mul_13s_71s_71_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 71 ),
    .dout_WIDTH( 71 ))
mul_13s_71s_71_1_0_U1(
    .din0(r_exp_fu_560_p3),
    .din1(71'd1636647506585939924452),
    .dout(mul_ln249_fu_265_p2)
);

pedal_top_mul_43ns_36ns_79_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 43 ),
    .din1_WIDTH( 36 ),
    .dout_WIDTH( 79 ))
mul_43ns_36ns_79_1_0_U2(
    .din0(mul_ln123_fu_270_p0),
    .din1(mul_ln123_fu_270_p1),
    .dout(mul_ln123_fu_270_p2)
);

pedal_top_mul_49ns_44ns_93_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 93 ))
mul_49ns_44ns_93_1_0_U3(
    .din0(mul_ln142_fu_274_p0),
    .din1(mul_ln142_fu_274_p1),
    .dout(mul_ln142_fu_274_p2)
);

pedal_top_mul_50ns_50ns_100_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 100 ))
mul_50ns_50ns_100_1_0_U4(
    .din0(mul_ln297_fu_278_p0),
    .din1(mul_ln297_fu_278_p1),
    .dout(mul_ln297_fu_278_p2)
);

(* dissolve_hierarchy = "yes" *) pedal_top_sparsemux_9_3_64_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 64 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 64 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 64 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
sparsemux_9_3_64_1_0_U5(
    .din0(retval_1_fu_1094_p2),
    .din1(retval_1_fu_1094_p4),
    .din2(64'd0),
    .din3(retval_1_fu_1094_p8),
    .def(retval_1_fu_1094_p9),
    .sel(retval_1_fu_1094_p10),
    .dout(retval_1_fu_1094_p11)
);

pedal_top_mac_muladd_16s_15ns_19s_31_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15ns_19s_31_4_0_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m_fix_hi_fu_448_p4),
    .din1(grp_fu_1118_p1),
    .din2(shl_ln_fu_510_p3),
    .ce(grp_fu_1118_ce),
    .dout(grp_fu_1118_p3)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        Z2_reg_1197 <= {{sub_ln255_fu_591_p2[50:43]}};
        Z2_reg_1197_pp0_iter4_reg <= Z2_reg_1197;
        Z3_reg_1204 <= {{sub_ln255_fu_591_p2[42:35]}};
        Z4_reg_1209 <= Z4_fu_626_p1;
        es_sign_reg_1129 <= data_fu_282_p1[32'd63];
        es_sign_reg_1129_pp0_iter1_reg <= es_sign_reg_1129;
        es_sign_reg_1129_pp0_iter2_reg <= es_sign_reg_1129_pp0_iter1_reg;
        es_sign_reg_1129_pp0_iter3_reg <= es_sign_reg_1129_pp0_iter2_reg;
        es_sign_reg_1129_pp0_iter4_reg <= es_sign_reg_1129_pp0_iter3_reg;
        es_sign_reg_1129_pp0_iter5_reg <= es_sign_reg_1129_pp0_iter4_reg;
        exp_Z1P_m_1_reg_1240 <= {{exp_Z1P_m_1_l_fu_800_p2[51:2]}};
        exp_Z2P_m_1_reg_1224 <= exp_Z2P_m_1_fu_720_p2;
        icmp_ln18_1_reg_1142 <= icmp_ln18_1_fu_314_p2;
        icmp_ln18_1_reg_1142_pp0_iter1_reg <= icmp_ln18_1_reg_1142;
        icmp_ln18_1_reg_1142_pp0_iter2_reg <= icmp_ln18_1_reg_1142_pp0_iter1_reg;
        icmp_ln18_1_reg_1142_pp0_iter3_reg <= icmp_ln18_1_reg_1142_pp0_iter2_reg;
        icmp_ln18_1_reg_1142_pp0_iter4_reg <= icmp_ln18_1_reg_1142_pp0_iter3_reg;
        icmp_ln18_1_reg_1142_pp0_iter5_reg <= icmp_ln18_1_reg_1142_pp0_iter4_reg;
        icmp_ln18_reg_1134 <= icmp_ln18_fu_308_p2;
        icmp_ln18_reg_1134_pp0_iter1_reg <= icmp_ln18_reg_1134;
        icmp_ln18_reg_1134_pp0_iter2_reg <= icmp_ln18_reg_1134_pp0_iter1_reg;
        icmp_ln18_reg_1134_pp0_iter3_reg <= icmp_ln18_reg_1134_pp0_iter2_reg;
        icmp_ln18_reg_1134_pp0_iter4_reg <= icmp_ln18_reg_1134_pp0_iter3_reg;
        icmp_ln18_reg_1134_pp0_iter5_reg <= icmp_ln18_reg_1134_pp0_iter4_reg;
        icmp_ln309_2_reg_1171 <= icmp_ln309_2_fu_496_p2;
        icmp_ln309_2_reg_1171_pp0_iter1_reg <= icmp_ln309_2_reg_1171;
        icmp_ln309_2_reg_1171_pp0_iter2_reg <= icmp_ln309_2_reg_1171_pp0_iter1_reg;
        icmp_ln309_2_reg_1171_pp0_iter3_reg <= icmp_ln309_2_reg_1171_pp0_iter2_reg;
        icmp_ln309_2_reg_1171_pp0_iter4_reg <= icmp_ln309_2_reg_1171_pp0_iter3_reg;
        icmp_ln309_2_reg_1171_pp0_iter5_reg <= icmp_ln309_2_reg_1171_pp0_iter4_reg;
        icmp_ln309_reg_1163 <= icmp_ln309_fu_474_p2;
        icmp_ln309_reg_1163_pp0_iter1_reg <= icmp_ln309_reg_1163;
        icmp_ln309_reg_1163_pp0_iter2_reg <= icmp_ln309_reg_1163_pp0_iter1_reg;
        icmp_ln309_reg_1163_pp0_iter3_reg <= icmp_ln309_reg_1163_pp0_iter2_reg;
        icmp_ln309_reg_1163_pp0_iter4_reg <= icmp_ln309_reg_1163_pp0_iter3_reg;
        icmp_ln309_reg_1163_pp0_iter5_reg <= icmp_ln309_reg_1163_pp0_iter4_reg;
        m_diff_hi_reg_1192 <= {{sub_ln255_fu_591_p2[58:51]}};
        m_diff_hi_reg_1192_pp0_iter4_reg <= m_diff_hi_reg_1192;
        r_exp_reg_1186 <= r_exp_fu_560_p3;
        r_exp_reg_1186_pp0_iter4_reg <= r_exp_reg_1186;
        r_exp_reg_1186_pp0_iter5_reg <= r_exp_reg_1186_pp0_iter4_reg;
        tmp_158_reg_1148 <= m_fix_fu_414_p3[32'd70];
        tmp_158_reg_1148_pp0_iter1_reg <= tmp_158_reg_1148;
        tmp_162_reg_1176 <= e_frac_3_fu_348_p3[32'd53];
        tmp_162_reg_1176_pp0_iter1_reg <= tmp_162_reg_1176;
        tmp_162_reg_1176_pp0_iter2_reg <= tmp_162_reg_1176_pp0_iter1_reg;
        tmp_162_reg_1176_pp0_iter3_reg <= tmp_162_reg_1176_pp0_iter2_reg;
        tmp_162_reg_1176_pp0_iter4_reg <= tmp_162_reg_1176_pp0_iter3_reg;
        tmp_162_reg_1176_pp0_iter5_reg <= tmp_162_reg_1176_pp0_iter4_reg;
        trunc_ln255_reg_1158 <= trunc_ln255_fu_470_p1;
        trunc_ln255_reg_1158_pp0_iter1_reg <= trunc_ln255_reg_1158;
        trunc_ln255_reg_1158_pp0_iter2_reg <= trunc_ln255_reg_1158_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= retval_1_fu_1094_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_int_reg <= x;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = retval_1_fu_1094_p11;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1118_ce = 1'b1;
    end else begin
        grp_fu_1118_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_ce1_local = 1'b0;
    end
end

assign Z3_fu_616_p4 = {{sub_ln255_fu_591_p2[42:35]}};

assign Z4_fu_626_p1 = sub_ln255_fu_591_p2[34:0];

assign Z4_ind_fu_630_p4 = {{sub_ln255_fu_591_p2[34:27]}};

assign add_ln126_fu_710_p2 = (exp_Z4_m_1_fu_667_p2 + zext_ln126_1_fu_706_p1);

assign add_ln145_fu_791_p2 = (exp_Z2P_m_1_reg_1224 + zext_ln145_2_fu_787_p1);

assign add_ln243_1_fu_546_p2 = (tmp_176_cast_fu_521_p4 + 13'd1);

assign add_ln297_1_fu_900_p2 = (shl_ln6_fu_888_p3 + zext_ln297_2_fu_896_p1);

assign add_ln297_fu_873_p2 = (table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0 + 58'd16);

assign and_ln182_1_fu_821_p2 = (xor_ln182_fu_816_p2 & icmp_ln18_1_reg_1142_pp0_iter5_reg);

assign and_ln182_fu_826_p2 = (icmp_ln18_reg_1134_pp0_iter5_reg & and_ln182_1_fu_821_p2);

assign and_ln18_fu_836_p2 = (xor_ln18_fu_831_p2 & icmp_ln18_reg_1134_pp0_iter5_reg);

assign and_ln1_fu_762_p5 = {{{{Z2_reg_1197_pp0_iter4_reg}, {1'd0}}, {tmp_55_fu_734_p4}}, {2'd0}};

assign and_ln309_1_fu_1022_p2 = (xor_ln309_fu_1017_p2 & icmp_ln309_1_fu_936_p2);

assign and_ln309_2_fu_1039_p2 = (xor_ln18_1_fu_1034_p2 & or_ln309_1_fu_1028_p2);

assign and_ln309_3_fu_1051_p2 = (xor_ln309_1_fu_1045_p2 & icmp_ln309_reg_1163_pp0_iter5_reg);

assign and_ln309_4_fu_1073_p2 = (xor_ln18_1_fu_1034_p2 & or_ln309_3_fu_1067_p2);

assign and_ln309_5_fu_1079_p2 = (icmp_ln326_fu_954_p2 & and_ln309_4_fu_1073_p2);

assign and_ln309_fu_1012_p2 = (or_ln309_fu_942_p2 & icmp_ln309_reg_1163_pp0_iter5_reg);

assign and_ln_fu_583_p3 = {{tmp_53_fu_573_p4}, {1'd0}};

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ashr_ln229_fu_402_p2 = $signed(sext_ln227_fu_364_p1) >>> zext_ln229_fu_398_p1;

assign ashr_ln230_fu_442_p2 = $signed(m_fix_l_fu_422_p4) >>> zext_ln230_fu_432_p1;

assign data_fu_282_p1 = x_int_reg;

assign e_frac_1_fu_342_p2 = (54'd0 - zext_ln221_fu_338_p1);

assign e_frac_3_fu_348_p3 = ((es_sign_fu_286_p3[0:0] == 1'b1) ? e_frac_1_fu_342_p2 : zext_ln221_fu_338_p1);

assign e_frac_fu_330_p3 = {{1'd1}, {es_sig_fu_304_p1}};

assign es_exp_fu_294_p4 = {{data_fu_282_p1[62:52]}};

assign es_sig_fu_304_p1 = data_fu_282_p1[51:0];

assign es_sign_fu_286_p3 = data_fu_282_p1[32'd63];

assign exp_Z1P_m_1_l_fu_800_p2 = (zext_ln145_1_fu_796_p1 + zext_ln145_fu_773_p1);

assign exp_Z1_hi_fu_863_p4 = {{table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_q0[57:8]}};

assign exp_Z2P_m_1_fu_720_p2 = (zext_ln126_fu_716_p1 + zext_ln120_fu_682_p1);

assign exp_Z2_m_1_fu_744_p4 = {{{Z2_reg_1197_pp0_iter4_reg}, {1'd0}}, {tmp_55_fu_734_p4}};

assign exp_Z3_m_1_fu_673_p4 = {{{Z3_reg_1204}, {9'd0}}, {table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0}};

assign exp_Z4_m_1_fu_667_p2 = (zext_ln115_fu_660_p1 + zext_ln115_1_fu_663_p1);

assign f_Z4_fu_650_p4 = {{table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q1[25:16]}};

assign grp_fu_1118_p1 = 31'd23637;

assign icmp_ln18_1_fu_314_p2 = ((es_sig_fu_304_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_308_p2 = ((es_exp_fu_294_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_540_p2 = ((trunc_ln243_fu_537_p1 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln309_1_fu_936_p2 = (($signed(tmp_161_fu_926_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln309_2_fu_496_p2 = ((shl_ln7_fu_488_p3 != sext_ln227_fu_364_p1) ? 1'b1 : 1'b0);

assign icmp_ln309_fu_474_p2 = (($signed(m_exp_fu_324_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_954_p2 = (($signed(r_exp_2_fu_919_p3) < $signed(13'd7170)) ? 1'b1 : 1'b0);

assign m_exp_fu_324_p2 = ($signed(zext_ln486_fu_320_p1) + $signed(12'd3073));

assign m_fix_fu_414_p3 = ((tmp_fu_368_p3[0:0] == 1'b1) ? ashr_ln229_fu_402_p2 : shl_ln229_fu_408_p2);

assign m_fix_hi_fu_448_p4 = {{m_fix_fu_414_p3[70:55]}};

assign m_fix_l_fu_422_p4 = {{m_fix_fu_414_p3[70:7]}};

assign m_frac_l_1_fu_356_p3 = {{e_frac_3_fu_348_p3}, {7'd0}};

assign mul_ln123_fu_270_p0 = mul_ln123_fu_270_p00;

assign mul_ln123_fu_270_p00 = exp_Z3_m_1_fu_673_p4;

assign mul_ln123_fu_270_p1 = mul_ln123_fu_270_p10;

assign mul_ln123_fu_270_p10 = exp_Z4_m_1_fu_667_p2;

assign mul_ln142_fu_274_p0 = mul_ln142_fu_274_p00;

assign mul_ln142_fu_274_p00 = exp_Z2_m_1_fu_744_p4;

assign mul_ln142_fu_274_p1 = mul_ln142_fu_274_p10;

assign mul_ln142_fu_274_p10 = exp_Z2P_m_1_reg_1224;

assign mul_ln297_fu_278_p0 = mul_ln297_fu_278_p00;

assign mul_ln297_fu_278_p00 = exp_Z1P_m_1_reg_1240;

assign mul_ln297_fu_278_p1 = mul_ln297_fu_278_p10;

assign mul_ln297_fu_278_p10 = exp_Z1_hi_fu_863_p4;

assign or_ln185_fu_849_p2 = (and_ln18_fu_836_p2 | and_ln182_fu_826_p2);

assign or_ln309_1_fu_1028_p2 = (and_ln309_fu_1012_p2 | and_ln309_1_fu_1022_p2);

assign or_ln309_2_fu_1056_p2 = (icmp_ln309_reg_1163_pp0_iter5_reg | icmp_ln309_1_fu_936_p2);

assign or_ln309_3_fu_1067_p2 = (xor_ln309_2_fu_1061_p2 | and_ln309_3_fu_1051_p2);

assign or_ln309_fu_942_p2 = (icmp_ln309_2_reg_1171_pp0_iter5_reg | icmp_ln309_1_fu_936_p2);

assign out_exp_fu_964_p2 = (trunc_ln336_fu_960_p1 + 11'd1023);

assign r_exp_1_fu_914_p2 = ($signed(r_exp_reg_1186_pp0_iter5_reg) + $signed(13'd8191));

assign r_exp_2_fu_919_p3 = ((tmp_160_fu_906_p3[0:0] == 1'b1) ? r_exp_reg_1186_pp0_iter5_reg : r_exp_1_fu_914_p2);

assign r_exp_fu_560_p3 = ((tmp_159_fu_530_p3[0:0] == 1'b1) ? select_ln243_fu_552_p3 : tmp_176_cast_fu_521_p4);

assign retval_1_fu_1094_p10 = {{{icmp_ln18_reg_1134_pp0_iter5_reg}, {and_ln309_2_fu_1039_p2}}, {and_ln309_5_fu_1079_p2}};

assign retval_1_fu_1094_p2 = ((or_ln185_fu_849_p2[0:0] == 1'b1) ? select_ln18_fu_841_p3 : 64'd0);

assign retval_1_fu_1094_p4 = ((tmp_162_reg_1176_pp0_iter5_reg[0:0] == 1'b1) ? 64'd0 : 64'd9218868437227405312);

assign retval_1_fu_1094_p8 = t_fu_998_p4;

assign retval_1_fu_1094_p9 = 'bx;

assign select_ln18_fu_841_p3 = ((and_ln18_fu_836_p2[0:0] == 1'b1) ? 64'd9223372036854775807 : 64'd9218868437227405312);

assign select_ln229_fu_386_p3 = ((tmp_fu_368_p3[0:0] == 1'b1) ? sext_ln229_fu_382_p1 : m_exp_fu_324_p2);

assign select_ln230_fu_480_p3 = ((tmp_fu_368_p3[0:0] == 1'b1) ? shl_ln230_fu_436_p2 : ashr_ln230_fu_442_p2);

assign select_ln243_fu_552_p3 = ((icmp_ln243_fu_540_p2[0:0] == 1'b1) ? add_ln243_1_fu_546_p2 : tmp_176_cast_fu_521_p4);

assign select_ln303_fu_990_p3 = ((tmp_160_fu_906_p3[0:0] == 1'b1) ? tmp_31_fu_970_p4 : tmp_32_fu_980_p4);

assign sext_ln227_fu_364_p1 = $signed(m_frac_l_1_fu_356_p3);

assign sext_ln229_1_fu_394_p1 = $signed(select_ln229_fu_386_p3);

assign sext_ln229_fu_382_p1 = $signed(sub_ln229_fu_376_p2);

assign shl_ln229_fu_408_p2 = sext_ln227_fu_364_p1 << zext_ln229_fu_398_p1;

assign shl_ln230_fu_436_p2 = m_fix_l_fu_422_p4 << zext_ln230_fu_432_p1;

assign shl_ln6_fu_888_p3 = {{add_ln297_fu_873_p2}, {49'd0}};

assign shl_ln7_fu_488_p3 = {{select_ln230_fu_480_p3}, {7'd0}};

assign shl_ln_fu_510_p3 = {{tmp_158_reg_1148_pp0_iter1_reg}, {18'd131072}};

assign sub_ln229_fu_376_p2 = (11'd1023 - es_exp_fu_294_p4);

assign sub_ln255_fu_591_p2 = (trunc_ln255_reg_1158_pp0_iter2_reg - and_ln_fu_583_p3);

assign t_fu_998_p4 = {{{{1'd0}, {out_exp_fu_964_p2}}}, {select_ln303_fu_990_p3}};

assign table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln292_fu_730_p1;

assign table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln138_fu_726_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address0 = zext_ln119_fu_645_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_address1 = zext_ln114_fu_640_p1;

assign tmp_159_fu_530_p3 = grp_fu_1118_p3[32'd30];

assign tmp_160_fu_906_p3 = add_ln297_1_fu_900_p2[32'd106];

assign tmp_161_fu_926_p4 = {{r_exp_2_fu_919_p3[12:10]}};

assign tmp_176_cast_fu_521_p4 = {{grp_fu_1118_p3[30:18]}};

assign tmp_31_fu_970_p4 = {{add_ln297_1_fu_900_p2[105:54]}};

assign tmp_32_fu_980_p4 = {{add_ln297_1_fu_900_p2[104:53]}};

assign tmp_53_fu_573_p4 = {{mul_ln249_fu_265_p2[70:13]}};

assign tmp_54_fu_696_p4 = {{mul_ln123_fu_270_p2[78:59]}};

assign tmp_55_fu_734_p4 = {{table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_q0[41:2]}};

assign tmp_57_fu_777_p4 = {{mul_ln142_fu_274_p2[92:57]}};

assign tmp_fu_368_p3 = m_exp_fu_324_p2[32'd11];

assign trunc_ln243_fu_537_p1 = grp_fu_1118_p3[17:0];

assign trunc_ln255_fu_470_p1 = m_fix_fu_414_p3[58:0];

assign trunc_ln336_fu_960_p1 = r_exp_2_fu_919_p3[10:0];

assign xor_ln182_fu_816_p2 = (es_sign_reg_1129_pp0_iter5_reg ^ 1'd1);

assign xor_ln18_1_fu_1034_p2 = (icmp_ln18_reg_1134_pp0_iter5_reg ^ 1'd1);

assign xor_ln18_fu_831_p2 = (icmp_ln18_1_reg_1142_pp0_iter5_reg ^ 1'd1);

assign xor_ln309_1_fu_1045_p2 = (or_ln309_fu_942_p2 ^ 1'd1);

assign xor_ln309_2_fu_1061_p2 = (or_ln309_2_fu_1056_p2 ^ 1'd1);

assign xor_ln309_fu_1017_p2 = (icmp_ln309_reg_1163_pp0_iter5_reg ^ 1'd1);

assign zext_ln114_fu_640_p1 = Z4_ind_fu_630_p4;

assign zext_ln115_1_fu_663_p1 = f_Z4_fu_650_p4;

assign zext_ln115_fu_660_p1 = Z4_reg_1209;

assign zext_ln119_fu_645_p1 = Z3_fu_616_p4;

assign zext_ln120_fu_682_p1 = exp_Z3_m_1_fu_673_p4;

assign zext_ln126_1_fu_706_p1 = tmp_54_fu_696_p4;

assign zext_ln126_fu_716_p1 = add_ln126_fu_710_p2;

assign zext_ln138_fu_726_p1 = Z2_reg_1197;

assign zext_ln145_1_fu_796_p1 = add_ln145_fu_791_p2;

assign zext_ln145_2_fu_787_p1 = tmp_57_fu_777_p4;

assign zext_ln145_fu_773_p1 = and_ln1_fu_762_p5;

assign zext_ln221_fu_338_p1 = e_frac_fu_330_p3;

assign zext_ln229_fu_398_p1 = $unsigned(sext_ln229_1_fu_394_p1);

assign zext_ln230_fu_432_p1 = $unsigned(sext_ln229_1_fu_394_p1);

assign zext_ln292_fu_730_p1 = m_diff_hi_reg_1192_pp0_iter4_reg;

assign zext_ln297_2_fu_896_p1 = mul_ln297_fu_278_p2;

assign zext_ln486_fu_320_p1 = es_exp_fu_294_p4;

endmodule //pedal_top_exp_generic_double_s
